### ISSUE TITLE
先ほどAquesTalkエラーの相談をしたものです

### ISSUE THREAD

**Issue by shin6shin6** [anoyetta/ACT.Hojoring#11]
はじめました、既出かもしれませんが補助輪4.06のTTSYUKKURIでAquesTalkを選択するとAquesTalkの初期化で例外が発生しましたとエラーが出て選択できなくなっていますどうすればよいでしょうか？

FFXIV_ACT_Plugin.dll のバージョン
１６．１６
ACT.SpecialSpellTimer.dll のバージョン
ACT.UltraScouter.dll のバージョン
ACT.TTSYukkuri.dll のバージョン
上記は補助輪４．０６で上書き導入
ACT本体のログファイル
%APPDATA%\Advanced Combat Traker\Advanced Combat Tracker.log
ACT.SpecialSpellTimer のログファイル
ACT.UltraScouter のログファイル
ACT.TTSYukkuri のログファイル
%APPDATA%\anoyetta\ACT\log\ACT.Hojoring.YYYY-MM-DD.log
3プラグインのログは共通になっています。
すいませんログの確認仕方がわかりません
（あれば）エラーダイアログのスクリーンショット
![a](https://user-images.githubusercontent.com/33512608/32597839-36283a24-c57b-11e7-8f95-07a1d9a08452.jpg)

**Comment by shin6shin6** [comment]
AquesTalkを選択していると思います。また、反復して削除導入を繰り返すとたまにAquesTalkで話してくれることがあるのですがAquesTalkを選択状態で再度ACTを起動すると下のようなエラーメッセージが出ます
![aa](https://user-images.githubusercontent.com/33512608/32599030-a07d8f0c-c57e-11e7-9db5-096b7b12dc40.jpg)

**Comment by anoyetta** [comment]
https://go.microsoft.com/fwlink/?LinkId=746572
をインストールしてください。
