### ISSUE TITLE
Don't work with FZ timeline

### ISSUE THREAD

**Issue by Wild-Sturm** [anoyetta/ACT.Hojoring#12]
Don't work with FZ timeline and error ocurrs when add plugin

**Comment by anoyetta** [comment]
you should use this.
https://github.com/anoyetta/ACT.Timeline/releases/tag/v0.0.7.4

**Comment by Wild-Sturm** [comment]
This timeline don't support TTS such as [define speaker "voice" "Microsoft Zira Desktop" 0 100]

But I have used modified FZ.timeline to support TTS

**Comment by anoyetta** [comment]
In that case, there is no choice but to correct the modified FZ.Timeline.
You can ask "Prism" for the latest version.

**Comment by Wild-Sturm** [comment]
I updated Prism library and mofidied FZ.timeline works well with ACT.Hojoring

Thank you. And I wish TTS is officially supported in the FZ.timeline.
