### ISSUE TITLE
Yukkuri - 'Play Device' could not be loaded

### ISSUE THREAD

**Issue by Akurosia** [anoyetta/ACT.Hojoring#129]
**Describe the bug**
A Fatal Error "Type 'Play Device' could not be loaded" when trying to load any version of Yukkuri.

**To Reproduce**
Precondition: 
ACT is working correctly with Final and all other plugins
Downloaded latest files from Github and made sure to enable/allow the loading of dll files

1. Add the ACT.TTSYukkuri.dll to the plugin section and enable it

**Screenshots**
![yukkuri](https://user-images.githubusercontent.com/7465469/47813101-577e1800-dd4a-11e8-89d8-b182a0a0d061.jpg)

**Environment**
- ACT.Hojoring Version: 5.23.2
- FFXIV_ACT_Plugin Version: 1.7.0.13
 - OS: Windows 10  Pro x64 (no October Update installed)

**Additional context**
The issue happend after changing from the old Yukkuri version to the new one included in Hojoring.
Now neither the new one nor the old one is working and both throw the same issue.

**Comment by TamanegiMage** [comment]
FFXIV.Framework is too old.
Did you upgrade ALL Hojoring components?

**Comment by Akurosia** [comment]
I create a complete new folder with the latest files from the github release section and i am only using Yukkuri from this package currently (i do not have any other/older Hojoring installed)

**Comment by TamanegiMage** [comment]
Is the old DLL in the same folder as "Advanced Combat Tracker.exe"?
The DLL in the same location as the "Advanced Combat Tracker.exe" is loaded with the highest priority.

**Comment by Akurosia** [comment]
Ok after deleting CT completly and reinstalling everything it works now.
