### ISSUE TITLE
[SpecialSpellTimer] 自身以外のパーティメンバを対象とするプレースホルダの実装要望

### ISSUE THREAD

**Issue by LecTea** [anoyetta/ACT.Hojoring#13]
自分以外のパーティメンバが使用した共通アビリティなどのマッチングを行いたいです。
そのため、自身以外のパーティメンバを対象とするプレースホルダの実装要望です。

否定の正規表現で代用できる。が、敵等にも反応してしまう可能性がある。(また、否定は表現が難しい)

**Comment by anoyetta** [comment]
v4.0.9 で実装

**Comment by LecTea** [comment]
ありがとうございます！
