### ISSUE TITLE
Ultrascouter Mob cant detect Treasure coffer from Leve

### ISSUE THREAD

**Issue by altissia86** [anoyetta/ACT.Hojoring#135]
Backstory : Farming Amber-encased Vilekin from Leve
Bug : 
1. Add "Treasure coffer" to Mob-list
2. Treasure coffer didnt show on mob list even though it was in front of me
3. Enable "Dump Combatants" it didnt show on list either

Tried using another mob radar which is xivhunt.net client. It was showing on radar.

**Comment by anoyetta** [comment]
ウルスカでは combatants うち、mob のCategoryに該当するものしか取得してません。
宝箱は object であるため元々表示の対象としていません。

**Comment by altissia86** [comment]
thank you for replying. i take it as object is and will not be supported. if that is your stance then this comment lines inside moblist should be changed. these comment lines use Trap which is an object as an example, because of this i tried making object to be detected.

![capture](https://user-images.githubusercontent.com/43957601/49992038-7e6c7280-ffb5-11e8-8fac-4cdfb04e7dd6.PNG)

**Comment by anoyetta** [comment]
trapは内部的にはObjectではなくmob扱いですね。
ただし参照できる座標情報が実用に足るものではありません。
moblistの定義に残っているのはそれらの検証を行っていたときの名残です。
