### ISSUE TITLE
[SpecialSpellTimer] コマンド等に応じてトリガ状態をクリップボード出力したい

### ISSUE THREAD

**Issue by LecTea** [anoyetta/ACT.Hojoring#14]
コマンドやキーワードに応じて、スキルのリキャスト時間などタイマの状態をクリップボードへコピー出来るようにしたい要望です。

VCの繋がらないパーティメンバ等へ、アビリティのリキャスト状態や、残り時間を知らせたり等が可能になると考えています。

**Comment by anoyetta** [comment]
いっその事discordにテキスト送るほうが実用的だったりしない？

**Comment by LecTea** [comment]
たしかに！！
ディスコードなら送られた側もテキスト読み上げ設定もありますし、そちらの方が良いですね！

**Comment by anoyetta** [comment]
OK, discrod連携の方向で進めるわ。
コマンドの実装のほうが簡単ではあるけどつまらないんだよね。
趣味でやってるものだからテーマに魅力がないと手が動かなくて。

**Comment by anoyetta** [comment]
v4.0.9 で実装

**Comment by LecTea** [comment]
ありがとうございます。
