### ISSUE TITLE
Serious lag with overlay

### ISSUE THREAD

**Issue by Azruine** [anoyetta/ACT.Hojoring#143]
**Describe the bug**
lag with overlay :/

**To Reproduce**
Just play FFXIV with hojoring overlay

**Screenshots**
![honeycam 2019-01-11 05-12-56](https://user-images.githubusercontent.com/6277538/50994412-922cd980-155f-11e9-9c03-d3ca95c520a7.gif)

**Environment**
- ACT.Hojoring Version: 5.24.1, 5.26.6, 5.27.7 all of them
- FFXIV_ACT_Plugin Version: 1.7.0.11 (Korean Server)
 - OS: Win10 v1809 17763.253

**Additional context**
Since I've updated my PC OS to latest release, I suffered with lag on hojoring. Tried: enable CPU render only, higher log polling rates, reinstalling hojoring, reinstalling ACT, and finally reintstalling FFXIV.
Strange thing is, whenever I minimize the game, the overlay works perfectly.

 Of course, when the game maximized, lag again.

**Comment by anoyetta** [comment]
sorry, i'm not support Korean sever.

**Comment by anoyetta** [comment]
私は韓国サーバー、韓国語クライアントではプレイできないため確認するすべがありません。
Hojoringは、FFXIV_ACT_PluginやFFXIV_MemoryReaderに依存して動作するためそれらも含めて正しく動作しているのか？ということを確認する必要があります。しかしそれらを確認するすべがないため私では対処することができません。

そのタイムラインの定義ファイルを作った人や韓国版のFFXIV_ACT_Pluginを作っている方などに問合せてみてはどうでしょうか？
