### ISSUE TITLE
SpeSpe Triggers seem broken

### ISSUE THREAD

**Issue by Itseotle** [anoyetta/ACT.Hojoring#145]
As of recent release, my SpeSpe triggers do not execute off of Boss attacks anymore. After digging, it seems that they still parse, but no longer match upper vs lower case, and no error messages are thrown. This is for regular triggers, no regex, although making it a regex trigger does not seem to help. I'm using the same triggers and settings as before Patch 4.5 updates, and using the latest versions of plugins.

![image](https://user-images.githubusercontent.com/43760221/51075628-b669e280-1653-11e9-8478-2f5ad04836e0.png)
Windows 10 Pro

![image](https://user-images.githubusercontent.com/43760221/51075652-4445cd80-1654-11e9-85b8-226ba8c5490b.png)

Log Line: 00:282b:Chaos readies Chaotic Dispersion.
Will match: chaos readies chaotic dispersion
Will not match: Chaos readies Chaotic Dispersion

Thank you for your time and great work with these tools. ^^

**Comment by anoyetta** [comment]
パッチ4.5からログのキャラクター名にワールド名が付与されるようになりました。
その付与されるワールド名がマッチングにおいて邪魔になってしまうので除去しています。

"Chaos" はボスの固有名でもありますがワールド名でもあります。よって上記の処理の結果、除去されてしまっているからです。
ワールド名の除去はOptionsのTriggerから無効にできます。

**Comment by anoyetta** [comment]
fixed by v5.28.7
