### ISSUE TITLE
Scouter / Yukkuri Plugin initialization failed.

### ISSUE THREAD

**Issue by IrealiTY** [anoyetta/ACT.Hojoring#15]
![image](https://user-images.githubusercontent.com/1223686/32653011-8f3d3822-c606-11e7-86af-7cb3d899c782.png)

FFXIV_ACT_Plugin.dll version: 1.6.1.6
OverlayPlugin.dll: 0.3.3.14

**Comment by anoyetta** [comment]
There is a possibility that old DLL related to SpecialSpellTimer, UltraScouter, TTSYukkuri remains. Please delete old them once and try installing the latest version.

**Comment by IrealiTY** [comment]
Indeed. Deleting existing files from the ACT folder resolved it :)
