### ISSUE TITLE
Hojoringのアップデートが実行できない。

### ISSUE THREAD

**Issue by veraki** [anoyetta/ACT.Hojoring#150]
**現象の詳細**  
以前ACT起動中にフリーズし、その後からアップデートができなくなり、Hojoringv5.24.1以外のバージョンでプラグインを読み込めなくなってしまいました。

**再現方法**  
現象の再現方法を記載します。
プラグインを読み込んだ際のエラー

System.InvalidOperationException

XML ドキュメント (94,6) でエラーが発生しました。
   場所 System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   場所 System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   場所 ACT.SpecialSpellTimer.Models.SpellTable.Load(String file, Boolean isClear)
   場所 ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass25_0.<<InitPluginCore>b__0>d.MoveNext()

Inner Exception :
System.ArgumentNullException

値を Null にすることはできません。
パラメーター名:path1
   場所 System.IO.Path.Combine(String path1, String path2)
   場所 Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderObservableCollection1.Read6_Spell(Boolean isNullable, Boolean checkType)
   場所 Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderObservableCollection1.Read7_ArrayOfSpellTimer()

また、起動時のHojoringアップデートを開いた際のログを添付いたします。

& : 用語 'D:\Advanced Combat Tracker\ACT.Hojoring-v5.23.2.7z\.\ACT.Hojoring.Updater.exe' は、コマンドレット、関数、スク
リプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パスが含
まれている場合はそのパスが正しいことを確認してから、再試行してください。
発生場所 D:\Advanced Combat Tracker\ACT.Hojoring-v5.23.2.7z\update_hojoring.ps1:75 文字:3
+ & $updater $updateDir $isUsePreRelease
+   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Advanced Com...ing.Updater.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**環境**
- 補助輪のバージョン: v5.24.1
- FFXIV_ACT_Pluginのバージョン: v1.7.2.5
- OS: Windows 10 v.1809

お忙しいところ大変申し訳ございません。
あまり詳しくはないのですが、最善は尽くしますので
改善策などありましたら教えていただけると幸いです。

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
    * 現象のスクリーンショットを添付してください

[ACT.Hojoring.HelpMe.2019-01-20.zip](https://github.com/anoyetta/ACT.Hojoring/files/2775805/ACT.Hojoring.HelpMe.2019-01-20.zip)
![2019y01m20d_024103279](https://user-images.githubusercontent.com/46848160/51430323-00a72100-1c5d-11e9-9a25-4ec7cbc7e1fe.jpg)
![2019y01m20d_023406859](https://user-images.githubusercontent.com/46848160/51430325-07359880-1c5d-11e9-9ca5-50b575d55c8c.jpg)

**Comment by anoyetta** [comment]
Updater.exe がないのでしょう。
おそらくはアンチウィルスによって駆除されたなにかだと思います。
アンチウィルスのログを確認して除外するようにしてください。

アップデートについては一旦手動で行うとよいでしょう。

**Comment by veraki** [comment]
迅速なお返事本当にありがとうございます。
Updater.exeを新しくダウンロードしなおしてフォルダに入れたところ、正常にアップデートされました。

本当にありがとうございました。
