### ISSUE TITLE
[ULTRA SCOUTER]内蔵Enmityを表示しているとMob Listの同期が遅れる(フリーズする)

### ISSUE THREAD

**Issue by sanmiri** [anoyetta/ACT.Hojoring#151]
ULTRA SCOUTER内蔵のEnmityを有効にした場合のみ、Mob Listの表示が大きく遅延します。
平均で2,3秒のラグが発生しており、場合によっては1分以上反応がない状態になります。
Enmtiyの「使用する」のチェックを外し、再起動するとこの問題は解消されるようです。

- 補助輪のバージョン: v5.30.7
- FFXIV_ACT_Pluginのバージョン: v1.7.2.5
- OS: Windows 10 Pro v1809

**Comment by anoyetta** [comment]
既知の不具合で解消済みです
