### ISSUE TITLE
プロセスIDの選択をFFXIVプラグインの設定と同期してもらいたいです

### ISSUE THREAD

**Issue by akiotsutsumi** [anoyetta/ACT.Hojoring#153]
FF14の1台のPCで2重起動させて2垢運用しています。
その際ACTのDPS計測やEnmity等についてはFFXIVプラグインの
プロセスID設定から切替が可能なのですがHojoring系のプラグインは
切替える事が出来ない状態です。

DPS計測やEnmity等と同様にHojoring系プラグインも
FFXIVプラグインのプロセスID設定と同期させる事は可能でしょうか？

**Comment by anoyetta** [comment]
補助輪は独自にプロセスを掴んでいません。
常にFFXIV_ACT_Pluginの掴んでいるプロセスオブジェクトを参照しており、更にはプロセスから直接データを参照することはありません。

**Comment by akiotsutsumi** [comment]
早速のご回答ありがとうございます。
現在の補助輪とプロセスからのやり取りについては了解致しました。

それでは後1点教えて頂けますでしょうか。
先にご連絡させて頂いた通り、現在1台のPC上でFF14を2重起動させて2垢運用をしています。
この状況下で補助輪の各種プラグインを各垢毎で使用する術はありますでしょうか？

**Comment by anoyetta** [comment]
やったことがないので分かりません。

**Comment by akiotsutsumi** [comment]
了解しました、ありがとうございましたー
