### ISSUE TITLE
LOGS検索機能は正常に使用できません

### ISSUE THREAD

**Issue by z511640450** [anoyetta/ACT.Hojoring#155]
**現象の詳細**  
中国のプレイヤーはロック検索では読み取れないが、紅玉海の検出時にはHongYuHaiが表示され、データを読み取れない。しかしテスト中に紅玉海を正しく入力すると正常に読み取れる。

これはテストの時
![tim 20190217201418](https://user-images.githubusercontent.com/47716202/52914661-267c2000-3306-11e9-81d5-b3b6cf741da1.png)

これは使用時に
![tim 20190217202224](https://user-images.githubusercontent.com/47716202/52914678-4875a280-3306-11e9-907e-a388ee41841d.png)

早くこの問題を修復していただき、ありがとうございました。

**Comment by ylovez888888** [comment]
The solution to this issue is to translate "HongYuHai" to "红玉海" in worldlist.txt in FFXIV_ACT_Plugin.dll，you can use "Reflector" to fix it by yourself

**Comment by ylovez888888** [comment]
> **現象の詳細**
> 中国のプレイヤーはロック検索では読み取れないが、紅玉海の検出時にはHongYuHaiが表示され、データを読み取れない。しかしテスト中に紅玉海を正しく入力すると正常に読み取れる。
> 
> これはテストの時
> ![tim 20190217201418](https://user-images.githubusercontent.com/47716202/52914661-267c2000-3306-11e9-81d5-b3b6cf741da1.png)
> 
> これは使用時に
> ![tim 20190217202224](https://user-images.githubusercontent.com/47716202/52914678-4875a280-3306-11e9-907e-a388ee41841d.png)
> 
> 早くこの問題を修復していただき、ありがとうございました。

The solution to this issue is to replace "HongYuHai" with "红玉海" in worldlist.txt in FFXIV_ACT_Plugin.dll，you can use "Reflector" to fix it by yourself

**Comment by FlyingStarlight** [comment]
> > **現象の詳細**
> > 中国のプレイヤーはロック検索では読み取れないが、紅玉海の検出時にはHongYuHaiが表示され、データを読み取れない。しかしテスト中に紅玉海を正しく入力すると正常に読み取れる。
> > これはテストの時
> > ![tim 20190217201418](https://user-images.githubusercontent.com/47716202/52914661-267c2000-3306-11e9-81d5-b3b6cf741da1.png)
> > これは使用時に
> > ![tim 20190217202224](https://user-images.githubusercontent.com/47716202/52914678-4875a280-3306-11e9-907e-a388ee41841d.png)
> > 早くこの問題を修復していただき、ありがとうございました。
> 
> The solution to this issue is to replace "HongYuHai" with "红玉海" in worldlist.txt in FFXIV_ACT_Plugin.dll，you can use "Reflector" to fix it by yourself

This method is effective.

However, this issue should not be result from the **ACT** as other related plugins rely on the same file. Therefore, I think may be the translations or unicode transformation in this plugin have some bugs.

**Comment by anoyetta** [comment]
何のことを言っているのかまったく分かりません。
私の作っているプラグインは基本的に中国サーバ、韓国サーバには対応していません。
なぜならば私が動作確認をすることができないからです。

**Comment by wozaiha** [comment]
@z511640450 if you have not done with this problem,I uploaded a patched FFXIV_ACT_Plugin.dll
Which just changed server name in 中国一区 into chinese(I have no time to change all the world name in the file).
[https://github.com/wozaiha/FF14-Timeline-For-Team/raw/master/FFXIV_ACT_Plugin.Patched.dll](url)
所以其实还是汉化不全的锅2333
