### ISSUE TITLE
ultrascouter NO DATA (403)

### ISSUE THREAD

**Issue by adminferiale** [anoyetta/ACT.Hojoring#158]
Hi, i have recently install hojoring on a fresh new ACT all updated
i try to use the FFlog overlay on, ultrascouter  but when i try (on all people and me included with no hidden log)
i use check the use hover target and when i clic on a player i have the overlay who pop 
but he seem empty  with a NO DATA (403) or (401)return on all people

I'm on the EU server
I have try with the private key and the public key on the FFlog setting  the only difference is the number on  the error 401 or 403

If i forgot a configuration thanks to help me .

clic on a player 
wait 2sec for the loading 
and the result 
https://i.imgur.com/3u938ES.jpg

**Environment**
FFXIV_ACT_Plugin v1.7.2.6
FFXIV_MemoryReader v1.4.13.0
ACT.Hojoring v5.32.2
ACT.SpecialSpellTimer v2.11.13
ACT.UltraScouter v1.8.2
ACT.TTSYukkuri v4.2.2
- FFXIV_ACT_Plugin Version: 1.7.2.6
 - OS: Windows 10 pro (french)

**Additional context**
there is a screen with all my plugin list (if i need someone more ?)
https://i.imgur.com/hV4m75P.jpg

and i have no problem  with the specialspelltimer or other atm

thanks in adavance

**Comment by wozaiha** [comment]
What will it return if you manually input the Character Name & Server in UltraScouter and [?](https://www.fflogs.com/v1/docs/#!/Rankings/rankings_character_characterName_serverName_serverRegion_get) ?
In my test, the character in the first pic returns a Code 200  which is correct.
I think we need some more information to find out where the problem is

**Comment by adminferiale** [comment]
hi i have some news i have try many things and .....

sometimes it's work i have all data etc so no problem

but many time i have a new "bug" with "server nothing" under the name of the player

and i must restart all act clear my key  then put it again for make it working

**Comment by anoyetta** [comment]
wozaiha さんが書いているとおり、public key の設定を確認してください。
その上でテスト機能でキャラ名とサーバ名を入力してデータ取得できるかどうか？取得できないならばキャラ名とサーバ名が間違っていないか？それをFFLogsのWebサイトで直接検索してみてデータが登録されているのか確認してください。

またゲーム内で実際にターゲットして使用していて server nothing となる場合は周囲のキャラ数が多くサーバ名を取得する対象から外れているからです。負荷を軽減するため周囲キャラクター情報を取得する数に制限をかけています。その制限によって取得されていないキャラクターについてはターゲットしてもサーバー名が取得できないため server nothing となります。
しかしこれについては v6.x.x 系でキャラクター情報の取得方法を根本的に変更したため発生しなくなっています。

**Comment by Iioneyse** [comment]
I am also having the issue.  No matter what I do (tried reinstalling fully and everything) it keeps giving me a 403 error.  I have double checked and made sure it was a public key and it is still giving me the 403 error.
