### ISSUE TITLE
[TTSYukkuri] .NET Framework Error / Discord bot not connecting

### ISSUE THREAD

**Issue by Neeksy** [anoyetta/ACT.Hojoring#16]
When I start up ACT I get this error window and it automatically closes before I can read it. My Discord bot no longer shows up online... If I try to connect in the Discord tab of YUKKURI it causes ACT to crash.

<img src="https://i.imgur.com/YDL5WFy.png">

Also whenever I close ACT this error window appears: 

<img src="https://i.imgur.com/WTH9frS.png">

**Comment by Neeksy** [comment]
Status update! I reinstalled ACT and my plugins to try to narrow down the issue. I can gather it is just something from TTS Yukkuri. If I remove the bot token none of the above errors show up. When I add in the token and try to connect I get this: 

<img src="https://i.imgur.com/hK8drQX.png">

**Comment by anoyetta** [comment]
Would not it be necessary to configure the bot?

**Comment by Neeksy** [comment]
The bot is configured. It used to work but stopped working when I updated TTS Yukkuri from v3.1.3 to Hojoring v4.0.6

**Comment by anoyetta** [comment]
fixed. v4.0.12
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v4.0.12
