### ISSUE TITLE
[UltraScouter] 大人数のときに内蔵Enmityが正常に動作しない

### ISSUE THREAD

**Issue by 333mm** [anoyetta/ACT.Hojoring#160]
**現象の詳細**  
エウレカやモブハントなど大人数のときにEnmityが正常に動作しません。
表示されなくなったり、状態が更新されなくなります。

- 補助輪のバージョン: v6.1.7
- FFXIV_ACT_Pluginのバージョン: v1.7.2.8

[ACT.Hojoring.HelpMe.2019-03-12.zip](https://github.com/anoyetta/ACT.Hojoring/files/2953496/ACT.Hojoring.HelpMe.2019-03-12.zip)

**Comment by anoyetta** [comment]
Enmityは関係なく負荷の高い環境で例外が発生するようです。
それによって全体の動作が重くなっていると考えられます。

実験的に直してみましたのでこちらを試してみてください。
結果はこちらに報告してください。
[ACT.Hojoring-v6.1.9 for Debug](https://drive.google.com/open?id=1OVBZmj7tR3DQ5YntU4zbzYt1UT83r_ZB)

**Comment by 333mm** [comment]
対応ありがとうございます。
早速 v6.1.9を導入し、エウレカ：ヒュダトス編にて使用してみましたが私の環境では改善は見られませんでした。
おっしゃる通り、Enmity特有ではなく負荷の高い環境で再現できるようで、UltraScouterの他の機能も表示が一時的に停止することが分かりました。
v5.x.x系では高負荷時にスペスペトリガーの大幅な遅延が発生していましたが、
[DxDiag.txt](https://github.com/anoyetta/ACT.Hojoring/files/2955736/DxDiag.txt)
v6.x.x系で大幅に改善されました。

CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
RAM: 16384MB
GPU: NVIDIA GeForce GTX 960

という環境ですが、マシンのスペック不足によるものなのでしょうか？
厚かましいお願いかとは思いますが、他に改善点などあればお助けください。

**Comment by anoyetta** [comment]
何点かあるので。

1. エウレカについて
半ばあきらめています。
モブの数、PCの数、あとはエリア構造の特殊さによって発生するパケット量、ログ量ともに膨大なのだと推測しています。
スペスペがログ量に負けているか？そもそもパケット量が多すぎてFFXIV_ACT_Pluginのパーサが負けているのか？この判断が着きません。後者である可能性もあります。
私自身がエウレカを全くやっていないので現地で確認することも出来ないです。したがって現在もろもろの対策を行っている中で「たまたま動くようになればいいかな」程度の扱いになっています。

2. PCのスペックについて
やや古いものの十分だと思います。
GPUがやや弱いとは思いますがスペスペ系の処理にはほぼ関係がありません。CPUは世代が古いものの4コア8スレッドならば十分です。

**Comment by anoyetta** [comment]
一応もらったログを見ました。
まだ別の例外が発生しているのでこれらを解消させれば、これよりパフォーマンスが改善する可能性があります。次のリリースで直しておきます。

**Comment by anoyetta** [comment]
[ACT.Hojoring v6.2.1 for Debug](https://drive.google.com/open?id=1qqEp0cWHG9bTlcfJ1B3dsidGGram4QBJ)

先程のログで検出した例外の対策版です。
この対応でエウレカ内で例外が発生しなくなればそこそこ使えるようになるんじゃないかと思います。

**Comment by 333mm** [comment]
早速の対応ありがとうございます。
やはりこちらではEnmityに関しては改善されませんでした。
[こちらの動画](https://dl.dropboxusercontent.com/s/ze1i9cmvaocle73/2019-03-12_21-42-56.mp4)のように、エンカウント後数秒でカウントが停止し、終了までそのまま動かなくなってしまいます。
Enmity以外の表示は非常にスムーズにされており、ほぼ止まることはなくなりました。


[ACT.Hojoring.HelpMe.2019-03-12-3.zip](https://github.com/anoyetta/ACT.Hojoring/files/2956861/ACT.Hojoring.HelpMe.2019-03-12-3.zip)

**Comment by anoyetta** [comment]
問題は２つある

1. やはりエウレカの負荷が高すぎる
発生しているログが多すぎる
通常のコンテンツだと1秒間に30～40行程度のところ、もらったログが計測している情報だと1秒間に100～200程度発生している。さすがにこのレベルだとまともに処理できない。
この問題はある程度は設定で回避できる部分でもあるのでその設定は後述します。

2. 新しい例外の発生が見られる
前の例外を潰したことで新しい例外が見られるようになっています。これについては次のバージョン出直します。しかし、発生頻度などから主たる原因ではないように思えます。

#### ログの多さに対する設定
以下、2点の設定を確認、設定してください。
1. スペスペのオプションの設定で周囲の人数が多いときに15:, 16:のログをカットする設定をONにする
この設定をONにすることで周囲の人数が多いときに極端に増えてしまうログを多少は減らせます。ONにしていないならばONにしたほうがよいです。

2. FFXIVのログの設定でダメージ系を全てOFFにする
FFXIVのログフィルタで全てのタブでOFFになっているログはACTにも通知されません（メモリ上に発生しなくなる）。もしもダメージ系のログをONにしている場合は全てOFFにしてください。
ACTの計測ではログは見ていません。パケットからの解析のみとなっています。したがってダメージ系のログの出力の有無は計測とまったく関係がありません。
すなわちダメージログをONにしていると無駄に高負荷な状況を作り出しているということになります。

**Comment by 333mm** [comment]
やはりエウレカなどの高負荷な環境ですと難しそうですか…。
設定に関して挙げて頂いた2つを試してみましたが結果は変わらずでした。
また、私の環境特有の現象なのかと思い友人にも試してもらったところ同じ現象が再現されました。

丁寧に対応して下さりありがとうございます。

**Comment by anoyetta** [comment]
アップデートで対応したものともう一つボトルネックとなりうる問題があったのでお伝えします。

### Hojoring のアップデートについて
v6.3.0 をリリースしました。
機能の結果を踏まえてもろもろ改善しています。これでも現象が改善しなければエウレカについては諦めざるを得ないでしょう。まだ例外が出る場合は別ですが。

* 少し残っていた例外の修正
例外は少なからず影響があるので潰しておきました。この分パフォーマンスが改善すると思います。
* Enmityを大幅に最適化した
まずEnmityの描画が止まってしまうのは「結果」であって「原因」ではないです。しかしそれなりに描画負荷が高い可能性を考慮して全面的に最適化しました。

### TTSYukkuri のステータス通知の設定について
Hojoring全体の大前提ですが最も負荷の高い処理は「TTSからwaveを生成するところ」です。
これは各種TTSエンジンが文字列を解析して合成音声を生成するという大変高度な処理を行っているため当然です。
そこで毎回waveを生成させていては負荷が高すぎてしまうため生成されたwaveはキャッシュして再利用しています。しかし新しい文字列が与えられた場合は当然として生成せざるを得ません。

要するに同じ文字列を発声させている分にはキャッシュが効くのであまり問題ではありません。しかし動的に変化するような文字列を発声させると発声都度にwaveの生成を行うため非常に負荷がかかります。

もらったログですと「にんじゃJ, しんだ」などのステータス監視を使用しています。そしてその直後にLPSが上がっている。すなわち、waveの生成によって大量にCPUリソースを消費しその結果としてログの処理が遅延する。溜まったログを一気に処理するためLPSが跳ね上がるという現象が見られます。

#### 結論
高負荷が予想されるシチュエーションでは以下のいずれかにしましょう。
1. TTSYukkuriのステータス監視を切る
2. 新しく搭載した &lt;job&gt; を使用してキャラ名のイニシャルが入らない名前で通知させる
もともとの &lt;pcname&gt; ですとキャラ名のイニシャルが含まれるためジョブとイニシャルの組合せ毎にwaveを生成してしまいます。&lt;job&gt; ならば一度全てのジョブを読み上げてしまえば以後キャッシュが効きますので有利です。

**Comment by 333mm** [comment]
様々な対策とご指摘ありがとうございます。
v6.3.0にアップデート後、指摘して頂いたことを踏まえて何度かエウレカNMと24人アライアンスレイドに行ってきました。

結論から書きますと、Enmityの挙動に関しては改善は見られませんでした。
ご指摘頂いたYukkuriのStatus AlertのOnとOff 双方で計測を試してみましたが、どちらの状態でもエウレカNM・24人アライアンスレイドのすべての計測で前回の動画と同じようなタイミングで停止後、終了まで動かなくなってしまいます。
今回もEnmity以外の動作に関しては、SPESPEも含め遅延や停止は見受けられませんでした。

[ACT.Hojoring.HelpMe.2019-03-13.zip](https://github.com/anoyetta/ACT.Hojoring/files/2961117/ACT.Hojoring.HelpMe.2019-03-13.zip)

**Comment by anoyetta** [comment]
確認ありがとうございます。

ログを見ました。
例外はなくなりログとしてはきれいな状態にはなっていますね。
LPSも最大で100程度とかなり改善しています。とはいえ、かなり高い値ではありますがエウレカでの人数で考えると妥当な値だと思います。

Enmityの件についてです。
こうなってくると固まってしまう状況下でEnmityとして読み取っているデータに何か変なデータがあるかもしれないという仮設になっています。
この何かを調べないといけないのですが、方法としてはその状況下で私がデバッグするぐらいしか方法がありません。そしてそれは色んな意味で不可能です。
* 私がエウレカにいけない
* 行けたとしてもそんな高負荷な状況でデバッグとかできない
一応こういう課題が残っているという認識で改善などは続けていきます。ひょっとすると何かが効いて治る可能性もありますが、経験上原因の根っこを掴まないで対応しても正解には行き着けないとも思っています。

当面の運用としてはエウレカの高負荷な状況下ではEnmityは切っておくしかないかと思います。

**Comment by 333mm** [comment]
了解しました。
一応素人目ではありますが気がついた点を羅列します。的外れな点は聞き流していただければと思いまます。

- v5系では高負荷時にも動作していた

- 環境によって停止する条件が異なる
(MOB_Aは両方停止したが、MOB_Bは片方の環境でのみ停止した)

- MOB_Aの情報が更新されない状態にある時、同じ負荷状態ですぐ隣のMOB_Bを攻撃した場合は停止せず計測される
(負荷状態というよりは、計測対象に関与した人数が多いと停止する印象がある)

- v6.3.0から、ターゲットを変更しても直前ターゲットの敵視数値情報が表示に残ってしまう
(常時)

Enmity単体においては別途方法もありますので当面必要な際はそちらを使用してしのぎたいと思います。
今後のアップデートの際、解消したタイミングに気がつけばできる限りこちらに報告させていただきます。

**Comment by anoyetta** [comment]
先程原因がはっきりわかったので次のバージョンで直ります。

Enmityのエントリー情報が多すぎると困るのでエントリー人数に上限を設けています。
その上限は16人となっています。
しかし16人まで読み取ってあとは無視するのならばよいのですが、16人を超えている場合読み取ることすら全てやめてしまうという処理になっていました。これはsharlayanのバグだと思います。

よってEnmityが止まってしまうのは負荷が原因ではなく、正しく動作していたがロジック的に人数が多いと更新をやめてしまっていたということでした。

**Comment by anoyetta** [comment]
おそらくこれで問題ないでしょう。
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v6.3.1-190314.1824

**Comment by 333mm** [comment]
v6.3.1において、先程エウレカ内にて問題の解消を確認しました。
数日に渡り対応と様々な対策の実装、ありがとうございました！

[ACT.Hojoring.HelpMe.2019-03-14.zip](https://github.com/anoyetta/ACT.Hojoring/files/2965741/ACT.Hojoring.HelpMe.2019-03-14.zip)

**Comment by anoyetta** [comment]
よかったですね。
結果として負荷は関係なかったですが、負荷を疑って色々と対策したため前よりも数段軽くなっていると思います。
