### ISSUE TITLE
[UltraScouter] Mob検知のオーバレイのレイアウトが崩れる

### ISSUE THREAD

**Issue by 333mm** [anoyetta/ACT.Hojoring#161]
![2019-03-15_23-42-56](https://user-images.githubusercontent.com/47035438/54439611-779ff800-477c-11e9-9794-df12a1301b1c.png)
![BHlmr7N](https://user-images.githubusercontent.com/47035438/54439661-98684d80-477c-11e9-8539-1f06f1abdf24.png)

**現象の詳細**  
初期状態では問題はないのですが、一度シンプル表示を有効にした後に標準表示に戻すと、ジョブアイコンサイズが変更されずレイアウトが崩れます。

**再現方法**  
1. MobListの感知対象にジョブアイコンが表示されるものを設定する
2. シンプル表示を有効にする
3. 標準表示に戻す
4. 再現される

**環境**
- 補助輪のバージョン: v5.32.x ～ v6.x.xいずれも
- FFXIV_ACT_Pluginのバージョン: v1.7.2.8

**追加のコメント**  
複数の環境で確認しております。

[ACT.Hojoring.HelpMe.2019-03-15.zip](https://github.com/anoyetta/ACT.Hojoring/files/2971600/ACT.Hojoring.HelpMe.2019-03-15.zip)

**Comment by anoyetta** [comment]
確認ですがACTを再起動してもジョブアイコンは大きいままでしょうか？

**Comment by 333mm** [comment]
はい、再起動しても大きいままです。

**Comment by anoyetta** [comment]
ありがとうございます。
だいたい分かりましたので次で直します。

**Comment by anoyetta** [comment]
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v6.3.4-190316.0818

**Comment by 333mm** [comment]
v6.3.4にて解消しました。ありがとうございます！
