### ISSUE TITLE
6.3.4配布ファイルにウイルスが含まれています。

### ISSUE THREAD

**Issue by anonsixx** [anoyetta/ACT.Hojoring#162]
**Describe the bug**
6.3.4配布ファイルにウイルスが含まれています。

**Screenshots**
![image](https://user-images.githubusercontent.com/48678048/54555906-0d48bb00-49fb-11e9-858a-a2b5ab78e396.png)

**Environment**
- ACT.Hojoring Version: v6.3.4
- FFXIV_ACT_Plugin Version: 
 - OS: Windows 10

**Additional context**
7z圧縮ファイルを解除するやいなや、Windows Defenderが悪性コードを発見してファイルを隔離したという警告が出力されます。

**Comment by anoyetta** [comment]
アンチウィルスによる誤検出でしょう。
オープンソースなので気になるならソースコードを確認してください。

**Comment by anonsixx** [comment]
Kasperskyで正常動作確認しました
