### ISSUE TITLE
Feature Request: option to hide "Ready" from icon

### ISSUE THREAD

**Issue by possiblyabird** [anoyetta/ACT.Hojoring#163]
Hey,
would love to be able to hide the "Ready" text while keeping the countdown.

Thank you for this addon, rebuilding my entire UI with it currently.

**Comment by exeedz** [comment]
just remove the ready text in Spespe -> Options -> Triggers -> "Text to display at the completion of the forward direction timer (default: "Ready")

![image](https://user-images.githubusercontent.com/5017342/54734470-abdf4280-4bda-11e9-90f7-ccae9e95b7de.png)

**Comment by possiblyabird** [comment]
Just found that myself. Sorry for the bother. :v
