### ISSUE TITLE
スぺスぺの動作不良

### ISSUE THREAD

**Issue by Lunaskye** [anoyetta/ACT.Hojoring#164]
数日前より、カスタムトリガーとスペスペで登録しているトリガーの認識に約5秒の遅延及び、スペスペタイムラインのオーバーレイの遅延(ワイプしているのにそれを認知せずそのままオーバーレイのみが進行、ギミックが着弾後に当該ギミック名の読み上げ等)が発生しております。

**環境**
FFXIV_ACT_Plugin v1.7.2.8
FFXIV_MemoryReader v1.4.13.0
ACT.Hojoring v6.3.4
ACT.SpecialSpellTimer v2.11.13
ACT.UltraScouter v1.8.2
ACT.TTSYukkuri v4.2.2

Act及び補助輪両方をアンインストールし、再度設定しなおしましたが何も改善されませんでした。原因がわかりましたら教えていただけますと幸いです。よろしくお願いいたします。

[ACT.Hojoring.HelpMe.2019-03-21.zip](https://github.com/anoyetta/ACT.Hojoring/files/2991249/ACT.Hojoring.HelpMe.2019-03-21.zip)
![スクリーンショット (11)_LI](https://user-images.githubusercontent.com/48786812/54740732-90d2f980-4bff-11e9-93dc-9da039c4ba97.jpg)

**Comment by anoyetta** [comment]
特に例外等は発生しないです。
ログからは何の異常も見られない状態です。

* OS再インストール
* カスタムトリガを一つだけ登録して試してみる
* スペルを一つだけ登録して試してみる
* 問題なければ更に一つずつ増やしていく
* AfterBurnerなどを使用して正常な状態と異常な状態でのCPU使用率を計測してみる

これらで調査してみてください。

**Comment by Lunaskye** [comment]
ありがとうございます!
簡単なものから試してみます。


2019年3月21日(木) 18:05 anoyetta <notifications@github.com>:
