### ISSUE TITLE
Feature Request: option to hide the entire overlay

### ISSUE THREAD

**Issue by possiblyabird** [anoyetta/ACT.Hojoring#165]
Would love to be able to hide everything during cutscenes, since I'm using SPESPE for hotbars, like so:

![overlay](https://user-images.githubusercontent.com/48782692/54855693-b04d4d80-4cf7-11e9-940a-45ee78307044.jpg)

Apologies if this is also already an option, I've been looking for hours.

**Comment by anoyetta** [comment]
カットシーンを判別する方法がないため無理です。

**Comment by possiblyabird** [comment]
Ah, sorry for the misunderstanding. I meant toggling manually on pressing the hotkey.

**Comment by natyusha** [comment]
You can control it already through ingame macros (which can be put on a hotbar button).

To turn it off:
`/e /spespe off`

To turn it on:
`/e /spespe off`

It would be much nicer if you could use a single command to toggle it  like `/e spespe toggle` or assign a key externally thought like in your screenshot.

**Comment by possiblyabird** [comment]
That works perfectly for my case since I'm using two macros to toggle parts of the hud anyway. Cheers!
