### ISSUE TITLE
TTSゆっくり初期化エラー

### ISSUE THREAD

**Issue by ichikapm** [anoyetta/ACT.Hojoring#17]
![yukkuri_error](https://user-images.githubusercontent.com/33590176/32695951-a19ae2d8-c7ac-11e7-910f-273a946bd3fe.png)

画像のようなエラーが出てしまい、TTSゆっくりが使用できません。
プラグインを削除して再度読み込みなおすと、今度は

![yukkuri_error2](https://user-images.githubusercontent.com/33590176/32695961-49a5b7be-c7ad-11e7-900e-a84143e65e05.png)

このようなエラーが出てしまいます。どのようにしたらゆっくりを使えるようになりますか？

**Comment by anoyetta** [comment]
まずはreadmeを読んで足りない情報を補ってください。

今の情報から推測できるのはセットアップでミスがありそうです。dllの配置が間違っている。古いものが混在している。これらの可能性がありえます。

**Comment by ichikapm** [comment]
[ACT.Hojoring.2017-11-12.log](https://github.com/anoyetta/ACT.Hojoring/files/1464456/ACT.Hojoring.2017-11-12.log)

[Advanced Combat Tracker.log](https://github.com/anoyetta/ACT.Hojoring/files/1464463/Advanced.Combat.Tracker.log)
後者はファイルが大きすぎたため、昨日以前のログを削除して添付しています。

dllはlibフォルダ以外のものはそのままコピーしてACT本体と同じところに、libフォルダの中身はACT本体と同じディレクトリにおいています。
![yukkuri_error3](https://user-images.githubusercontent.com/33590176/32697441-d93c011e-c7d3-11e7-88a9-60b4fa5b1efa.png)
![yukkuri_error4](https://user-images.githubusercontent.com/33590176/32697443-db220e56-c7d3-11e7-8c43-c29b5fa79213.png)

**Comment by anoyetta** [comment]
ワーキングディレクトリに不要なものを配置ししすぎだと思います。
古いDLLがロードされてしまっていると思われます。
一度アインストール（すべてを削除）して、↓で再インストールしてみては？
https://github.com/eai04191/Actor
