### ISSUE TITLE
[UltraScouter] 戦闘時にTarget of TargetのHP参照先が切り替わってしまう

### ISSUE THREAD

**Issue by 333mm** [anoyetta/ACT.Hojoring#170]
**現象の詳細**  
Target of TargetのHP表示を設定した際、Target対象が行動を起こすタイミングでHP値の参照先がTargetのものに切り替わってしまいます。
恐らく対象の実行アクションの種類に影響されているものだと思われます。

(アルファノーマル3層 オメガの例)
マスタードボム → 正常な表示
右舷・左舷 → 切り替わる
アトミックレイ → 切り替わる
プリントアウト → 切り替わる
[[動画]](https://dl.dropboxusercontent.com/s/bu93ykselzdciu1/2019-04-05_15-23-16.mp4)

**再現方法**  
1. Target of TargetのHP表示を設定する
2. 特定のアクションを詠唱(実行)する対象と戦闘する
3. 特定のアクション詠唱(実行)のタイミングでHPの参照先が切り替わる

**環境**
- 補助輪のバージョン: v6.4.9
- FFXIV_ACT_Pluginのバージョン: v1.7.2.8

**追加のコメント**  
v6系になってからの不具合だと思います。よろしくお願い致します。

[ACT.Hojoring.HelpMe.2019-04-05.zip](https://github.com/anoyetta/ACT.Hojoring/files/3046655/ACT.Hojoring.HelpMe.2019-04-05.zip)

**Comment by anoyetta** [comment]
不具合というよりsharlayanがそういうふうに TargetID を更新しているのだと思います。
そしてそれをそのまま表示しているだけです。
実際のFFの内部処理もそういうことなんだと思いますので便利かどうかは別として事実通りということにはなるかと思います。

**Comment by 333mm** [comment]
回答ありがとうございます。
そもそもの仕様ということでしたか。失礼しました。
Targetを指定しないアクションを行っている時に、TargetIDがアクション実行者に更新されているということでしょうか。
手を加えてなんとかなる問題のようでしたら、是非調整の方をお願いしたく思います。

**Comment by anoyetta** [comment]
詳細はその瞬間にデータを見ていないので分かりません。
例えばきちんと調べるならば戦闘中のその瞬間にデバッグして確認する必要があります。
そういうことをやるならば一人では出来ないためデバッグに付き合ってくれる人を7人集めるなどが必要になります。
それらの条件を整えてくれるならば調べます。

**Comment by 333mm** [comment]
なるほど・・・私個人は是非協力したいのですが、人数は揃えられそうにありません。申し訳ありません。

フィールドやコンテンツ内を問わず発生し、ターゲットが対象を指定しないアクション(範囲攻撃や自己強化バフ等)を実行した時に内部的に実行者自身のTargetIDが指定されており、その際にゲーム内HUD表示とウルスカTarget of Target表示との相違が生じている

ということだと思います。
おっしゃる通り、状況を揃えてデバッグしない限り確実なことは確認できないとは思いますので、憶測にすぎないのですが情報になればと思います。

**Comment by anoyetta** [comment]
どんなに補足したところでそれが仮説である限り修正はできないです。
また仮にその仮説が正しかったとしてもゲームのHUDに合わせることは出来ないと思います。
* TargetのTargetIDとTargetIDが同値だったら無視するようにする
すなわち、一時的にTargetOfTargetなしという状態になるためゲームのHUDと合わない
* TargetのTargetIDとTargetIDが同値だったら直前に有効だったTargetのTargetIDを採用する
例えばナイトが自分をターゲットしてクレメンシーを詠唱していた場合それが見えなくなるためゲームのHUDと合わない
