### ISSUE TITLE
絶アルテマ用タイムラインをタイムラインフォルダに入れるとエラーが出ます

### ISSUE THREAD

**Issue by H4LeeSin** [anoyetta/ACT.Hojoring#175]
**現象の詳細**  
現象の詳細を明確に記載します。
すぺすぺたいむを使用するタブに行き、"Get more samples"のzetu arutema.xmlをダウンロードして"Open"で開いたタイムラインフォルダに入れ、actを起動させるとエラーが出てしまい、落ちてしまいます。
**再現方法**  
現象の再現方法を記載します。

**環境**
- 補助輪のバージョン: v6.4.10
- FFXIV_ACT_Pluginのバージョン: v1.7.2.8
- OS: Windows 10 Home

**追加のコメント**  
なにか追加するコメントがあれば記載します。
hojoringにはいつも助けてもらっています。作ってくれてありがとうございます感謝しかないです。よろしくお願いします。
[ACT.Hojoring.HelpMe.2019-04-19.zip](https://github.com/anoyetta/ACT.Hojoring/files/3096330/ACT.Hojoring.HelpMe.2019-04-19.zip)
![1555625445187](https://user-images.githubusercontent.com/30302373/56394661-ff44bf00-6272-11e9-8c8a-a3079b4a6a92.jpg)

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
    * 現象のスクリーンショットを添付してください

**Comment by anoyetta** [comment]
なんだそりゃ？
ということで Google Drive を確認してみました。
結論からいうとそのファイルは壊れているため使用できません。
またそのファイルは私が配布したものではなくユーザさんが誤操作でアップしたもののようです。

ただし、その絶アルテマタイムラインの原本は Aqua Cat さんのブログのものじゃないかと思います。よって、Aqua Cat さんのブログにいけば壊れていないオリジナルが手に入るかと思います。
