### ISSUE TITLE
Ultra Scouter Chocobo detection

### ISSUE THREAD

**Issue by Hyrulean** [anoyetta/ACT.Hojoring#179]
**Describe the bug**
Ultra Scouter is detecting player chocobos when they have the same name as Hunt mobs and relaying them as hunts. Many players are naming their chocobos after S ranks and this causes lots of confusion. I was wondering if it is possible to make Ultra Scouter ignore friendly targets when searching a mob list? Thank you

**To Reproduce**
Use ultra scouter when near a chocobo named after a Hunt mob.

**Comment by rdj** [comment]
Another implementation possibility is adding an optional test for the mob's hp rather than relying solely on the name. The mob dump already shows mob hp so presumably that would be relatively easy to add.

**Comment by rdj** [comment]
In case it's helpful, here is the HP of each S rank (in decimal)

```
Croque-mitaine 2161117
Croakadile 2076443
The Garlok 1993770
Bonnacon 2217594
Nandi 1959517
Chernobog 2034107
Laideronnette 2015994
Wulgaru 2096612
Mindflayer 1935321
Thousand-cast Theda 1983686
Zona Seeker 2066359
Brontes 2179257
Lampalagua 2044191
Nunyunuwi 2227622
Minhocao 2132920
Agrippa the Mighty 2227622
Safat 2189341
Kaiser Behemoth 4517600
Gandarewa 4581120
Senmurv 4498560
The Pale Rider 4474880
Leucrotta 4439520
Bird of Paradise 4397760
Salt and Light 21178492
Udumbara 21178492
Bone Crawler 21178492
Orghana 23533185
Okina 21178492
Gamma 21178492
```

**Comment by allainecactuar** [comment]
ACT now makes the owner field available on AddedCombatant log lines, so it is trivial to ensure the owner is set to 0000 to filter out chocobos.
