### ISSUE TITLE
[Error] SpeakTTS で例外が発生しました。 System.Runtime.InteropServices.COMException (0x800706BE): リモート プロシージャ コールに失敗しました。

### ISSUE THREAD

**Issue by FF14eledc** [anoyetta/ACT.Hojoring#18]
FFXIV_ACT_Plugin v1.6.1.8
ACT.Hojoring v4.0.8
ACT.SpecialSpellTimer v1.23.11
ACT.TTSYukkuri v3.2.8

2017-11-12 23:44:38.7054 [Trace] Yukkuri speak=更新, phonetic=コーシン 
2017-11-12 23:44:39.0403 [Error] SpeakTTS で例外が発生しました。 System.Runtime.InteropServices.COMException (0x800706BE): リモート プロシージャ コールに失敗しました。 (HRESULT からの例外:0x800706BE)
   場所 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   場所 NAudio.CoreAudioApi.AudioClient.IsFormatSupported(AudioClientShareMode shareMode, WaveFormat desiredFormat, WaveFormatExtensible& closestMatchFormat)
   場所 NAudio.Wave.WasapiOut.Init(IWaveProvider waveProvider)
   場所 FFXIV.Framework.Common.WavePlayer.Play(String file, Single volume, WavePlayerTypes playerType, String deviceID)
   場所 ACT.TTSYukkuri.SoundPlayerWrapper.PlayCore(String file, Single volume, WavePlayerTypes playerType, String deviceID)
   場所 ACT.TTSYukkuri.Yukkuri.YukkuriSpeechController.Speak(String text)
   場所 ACT.TTSYukkuri.PluginCore.SpeakTTS(String textToSpeak)
2017-11-12 23:44:44.0318 [Trace] Yukkuri speak=サークル, phonetic=サ'ークル 

![default](https://user-images.githubusercontent.com/33598393/32700192-0de65802-c805-11e7-96c4-43a1d409309a.png)
上記エラーログが出た後FF14 のクライアントが強制終了します。

YukkuriのTTSだと落ちて、Yukkuriのディスコード連携やプラグイン無しのHARUKAだとエラーは出ないようです。
ACTの再インストールも行いHojyoringの古いdllも無い状態です。

解決方法分かりますでしょうか？

[ACT.Hojoring.HelpMe.2017-11-12.zip](https://github.com/anoyetta/ACT.Hojoring/files/1464804/ACT.Hojoring.HelpMe.2017-11-12.zip)

**Comment by anoyetta** [comment]
FFXIV本体の方はスクエニに聞いてください。
TTSYukkuriのほうはサウンドデバイスの取得時にエラーになってる様子。しかし私の環境等では再現しないので詳しいことは分からない。

FFXIV本体のほうもTTSYukkuriのほうもサウンド絡みっぽいので、サウンドカードのドライバ等を最新してセットアップし直してみては？

**Comment by FF14eledc** [comment]
お返事ありがとうございます。
サウンドカードの再インストールしてみます。

**Comment by FF14eledc** [comment]
サウンドカード再インストールでは治らなかったのでFF14の方もやってみます。

**Comment by FF14eledc** [comment]
FFXIV.Framework.TTS.Server.exeが管理者権限で実行になってなく、ファイアウォールを介した通信の許可に設定されてなかったのですがこれは設定する必要性ありますか？

**Comment by anoyetta** [comment]
それは分からないですね。

**Comment by FF14eledc** [comment]
FF14再インストールでも治りませんでした。となるとあとはWindouws10が原因なのかな・・・
