### ISSUE TITLE
ACT.TTSYukkuri起動時にエラー

### ISSUE THREAD

**Issue by kz827584** [anoyetta/ACT.Hojoring#180]
ACT起動時にTTSYukuriを起動しようすると下記エラーが発生します。
Application-Start 2019-05-06T21:23:15 (v3.3.3     Release: 258 | CLR v4.0.30319.42000 | OS Microsoft Windows NT 6.2.9200.0)
***** 2019-05-06T21:23:16 - Entering InitACT
***** 2019-05-06T21:23:16 - Entering LoadNewSettings
***** 2019-05-06T21:23:17 - Config loading plugin from: E:\ACTv3\ACT.SpecialSpellTimer.dll
***** 2019-05-06T21:23:17 - Enabling plugin: E:\ACTv3\ACT.SpecialSpellTimer.dll
***** 2019-05-06T21:23:17 - Config loading plugin from: E:\ACTv3\ACT.TTSYukkuri.dll
***** 2019-05-06T21:23:17 - Enabling plugin: E:\ACTv3\ACT.TTSYukkuri.dll
***** 2019-05-06T21:23:17 - Config loading plugin from: E:\ACTv3\ACT.UltraScouter.dll
***** 2019-05-06T21:23:17 - Enabling plugin: E:\ACTv3\ACT.UltraScouter.dll
***** 2019-05-06T21:23:17 - Config loading plugin from: E:\ACTv3\OverlayPlugin.dll
***** 2019-05-06T21:23:17 - Enabling plugin: E:\ACTv3\OverlayPlugin.dll
***** 2019-05-06T21:23:17 - Config loading plugin from: E:\ACTv3\FFXIV_ACT_Plugin.dll
***** 2019-05-06T21:23:17 - Enabling plugin: E:\ACTv3\FFXIV_ACT_Plugin.dll
***** 2019-05-06T21:23:17 - LogFileChanged: C:\Users\康夫\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20190506.log - 2019-05-06T09:14:07 - 2019-05-06T14:25:10 - 20021654
***** 2019-05-06T21:23:17 - Config loading plugin from: E:\ACTv3\RainbowMage.ActLocalizer.dll
***** 2019-05-06T21:23:17 - Exiting LoadNewSettings
***** 2019-05-06T21:23:17 - LogFileChanged: C:\Users\康夫\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20190506.log - 2019-05-06T09:14:07 - 2019-05-06T21:23:17 - 20021757
***** 2019-05-06T21:23:18 - Checking for program updates
***** 2019-05-06T21:23:18 - Exiting InitACT: 1289.03
Application-Close 2019-05-06T21:23:31
***** 2019-05-06T21:23:31 - Entering SaveNewSettings
***** 2019-05-06T21:23:34 - Exiting SaveNewSettings: 3069
Application-Start 2019-05-06T21:23:35 (v3.3.3     Release: 258 | CLR v4.0.30319.42000 | OS Microsoft Windows NT 6.2.9200.0)
***** 2019-05-06T21:23:35 - Entering InitACT
***** 2019-05-06T21:23:35 - Entering LoadNewSettings
***** 2019-05-06T21:23:36 - Config loading plugin from: E:\ACTv3\ACT.SpecialSpellTimer.dll
***** 2019-05-06T21:23:36 - Enabling plugin: E:\ACTv3\ACT.SpecialSpellTimer.dll
***** 2019-05-06T21:23:36 - Config loading plugin from: E:\ACTv3\ACT.TTSYukkuri.dll
***** 2019-05-06T21:23:36 - Enabling plugin: E:\ACTv3\ACT.TTSYukkuri.dll
***** 2019-05-06T21:23:36 - Config loading plugin from: E:\ACTv3\ACT.UltraScouter.dll
***** 2019-05-06T21:23:36 - Enabling plugin: E:\ACTv3\ACT.UltraScouter.dll
***** 2019-05-06T21:23:36 - Config loading plugin from: E:\ACTv3\OverlayPlugin.dll
***** 2019-05-06T21:23:36 - Enabling plugin: E:\ACTv3\OverlayPlugin.dll
***** 2019-05-06T21:23:36 - Config loading plugin from: E:\ACTv3\FFXIV_ACT_Plugin.dll
***** 2019-05-06T21:23:36 - Enabling plugin: E:\ACTv3\FFXIV_ACT_Plugin.dll
***** 2019-05-06T21:23:36 - LogFileChanged: C:\Users\康夫\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20190506.log - 2019-05-06T09:14:07 - 2019-05-06T21:23:33 - 20021757
***** 2019-05-06T21:23:36 - Config loading plugin from: E:\ACTv3\RainbowMage.ActLocalizer.dll
***** 2019-05-06T21:23:36 - Exiting LoadNewSettings
***** 2019-05-06T21:23:36 - LogFileChanged: C:\Users\康夫\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20190506.log - 2019-05-06T09:14:07 - 2019-05-06T21:23:36 - 20021860
***** 2019-05-06T21:23:36 - Checking for program updates
***** 2019-05-06T21:23:36 - Exiting InitACT: 1061.40
Application-Close 2019-05-06T21:24:06
***** 2019-05-06T21:24:06 - Entering SaveNewSettings
***** 2019-05-06T21:24:06 - ACT.TTSYukkuri Assemblyの解決で例外が発生しました
System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:path1
   場所 System.IO.Path.Combine(String path1, String path2)
   場所 ACT.TTSYukkuri.Plugin.<.ctor>b__3_0(Object s, ResolveEventArgs e)
   場所 Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   場所 ACT.TTSYukkuri.Plugin.<.ctor>b__3_0(Object s, ResolveEventArgs e)
   場所 System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   場所 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   場所 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   場所 System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   場所 System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(Type type, String defaultNamespace, XmlSerializerImplementation& contract)
   場所 System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   場所 ACT.SpecialSpellTimer.Models.SpellTable.Save(String file, List`1 list)
   場所 ACT.SpecialSpellTimer.PluginMainWorker.End()
   場所 ACT.SpecialSpellTimer.PluginCore.DeInitPluginCore()
   場所 ACT.SpecialSpellTimer.Plugin.Advanced_Combat_Tracker.IActPluginV1.DeInitPlugin()
   場所 Advanced_Combat_Tracker.FormActMain.SaveXmlActPlugins(XmlTextWriter xWriter)
   場所 Advanced_Combat_Tracker.FormActMain.SaveNewSettings(String XmlFileName)
   場所 Advanced_Combat_Tracker.FormActMain.FinalizeACT()
   場所 System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   場所 System.Windows.Forms.Form.WmClose(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   場所 System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   場所 System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   場所 System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   場所 System.Windows.Forms.Form.DefWndProc(Message& m)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.Form.WmSysCommand(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   場所 System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   場所 System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   場所 System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   場所 System.Windows.Forms.Form.DefWndProc(Message& m)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.Form.WmNcButtonDown(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   場所 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   場所 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   場所 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   場所 Advanced_Combat_Tracker.ActLoader.Main(String[] args)
*****

**Comment by anoyetta** [comment]
配置が間違っています。正しい手順で再セットアップしましょう。
手順は私のブログにあります。
