### ISSUE TITLE
エラーがでますがどうすればいいですか

### ISSUE THREAD

**Issue by arknoah93** [anoyetta/ACT.Hojoring#181]
[ACT.Hojoring.HelpMe.2019-05-07.zip](https://github.com/anoyetta/ACT.Hojoring/files/3149276/ACT.Hojoring.HelpMe.2019-05-07.zip)

System.ComponentModel.Win32Exception

指定されたファイルが見つかりません。
   場所 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   場所 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   場所 FFXIV.Framework.TTS.Common.RemoteTTSClient.StartTTSServer()
   場所 ACT.TTSYukkuri.TTSServer.TTSServerController.Start()
   場所 ACT.TTSYukkuri.PluginCore.<>c.<InitPlugin>b__26_2()
   場所 System.Threading.Tasks.Task.Execute()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 ACT.TTSYukkuri.PluginCore.<>c__DisplayClass26_0.<<InitPlugin>b__0>d.MoveNext()

モニターを変えたらyukkuriでエラーがでて使えなくなってしまいました。どうしたらいいですか。

**Comment by arknoah93** [comment]
回答が乗ってあるページのURL教えてもらってもいいですか

**Comment by anoyetta** [comment]
https://github.com/anoyetta/ACT.Hojoring/issues/182
