### ISSUE TITLE
スペスペのプレースホルダのハイフン入りのキャラ名について

### ISSUE THREAD

**Issue by sobbat** [anoyetta/ACT.Hojoring#183]
いつもお世話になっております。
スペスペの代名詞についてご報告します。

1. 現象
スペスペのプレースホルダ（<DPS1~4>など）を使用すると、ハイフン-が入った名前だけが正常に動作しない。
代名詞を使わず名前を決め打ちした場合は正常に動作。
例）上は動かず、下は動く。
`^(15|16):<ID8>:<DPS1>:76:バトルボイス`
`^(15|16):<ID8>:Yoshida Naoki-p:76:バトルボイス`

「正規表現を単純にする」「ツールチップ記号を除去する」「キャラ名に付与されるワールド名を除去する」のチェックを外しても変わりはありませんでした。
Informationsの有効なプレースホルダ、アクティブなトリガを見るとどの項目も正常にヒットしています。
一人の名前だけでなく、ハイフン入りのキャラ名は全て正常に動作しませんでした。

2. 環境
ACT.Hojoring:  v6.6.5
FFXIV_ACT_Plugin:  v1.7.2.10
OS:  Windows 10 v1809

[ACT.Hojoring.HelpMe.2019-05-08.zip](https://github.com/anoyetta/ACT.Hojoring/files/3157088/ACT.Hojoring.HelpMe.2019-05-08.zip)

5/9 19:00追記
Yoshida- Naokiというパターンではハイフン入りでも正常に動作することを確認しました。

**Comment by anoyetta** [comment]
ハイフンをエスケープしていないからですね。
直しておきます。
