### ISSUE TITLE
i-notice付きtriggerが２回以上マッチすると、画像が一瞬だけしか表示されない

### ISSUE THREAD

**Issue by hirozou** [anoyetta/ACT.Hojoring#186]
anoyetta様

お世話になっております。
既知のIssueでしたら、申し訳ないですが、
下記、ご確認くださいませ。

 **現象の詳細**  
timelineにi-noticeトリガーを設定し、1回の戦闘で、
2回目にマッチした場合、durationの値が何であろうと、
一瞬表示されて、すぐ消えてしまう。

 **再現方法**  
現象の再現方法を記載します。
【動画】
https://www.youtube.com/watch?v=Smqm-bLKqVE  

1. 添付のtimelineを準備
[sample.zip](https://github.com/anoyetta/ACT.Hojoring/files/3177370/sample.zip)

2. 「/echo 鉄の覇道を照らせ！」をゲームのチャットログに入力
　　→画像がdurationで設定された値の時間表示される正常動作
3. 再度、「/echo 鉄の覇道を照らせ！」を ゲームのチャットログに入力  →画像
　　→画像が一瞬のみ表示され、消えてしまう
4. 2.と異なるマッチングワード「/echo 赤熱し、神敵を焼け！」をゲームのチャットログに入力
　　→画像がdurationで設定された値の時間表示される正常動作
5. 再度、「/echo  赤熱し、神敵を焼け！」を ゲームのチャットログに入力  →画像
　　→3と同様用に画像が一瞬のみ表示され、消えてしまう

**環境**
- 補助輪のバージョン: ACT.Hojoring v6.8.3
- FFXIV_ACT_Pluginのバージョン: v1.7.2.10
- OS: Windows Win10

**追加のコメント**  
動画では、再現方法の3を2回実施しています。
また、ご確認いただいたら、動画は削除予定です。

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
[Advanced Combat Tracker.log](https://github.com/anoyetta/ACT.Hojoring/files/3177371/Advanced.Combat.Tracker.log)

    * 現象のスクリーンショットを添付してください
　　→動画で代替

**Comment by anoyetta** [comment]
私もなんとなくそんな気がしていました。
直しますが、現在私も絶アルテマで立て込んでいるのでなかなか難しいかもしれません。
そうはいってもそちらも絶バハ攻略でキーとなる使い方をしていそうですからなるべく早く対応します。

**Comment by hirozou** [comment]
noticeは問題なく動いてるので、攻略自体はなんとかなっています。
直せるタイムラインで大丈夫です。
絶アルテマ配信見てますよｗ
がんばってください！

**Comment by anoyetta** [comment]
この件、時間かかる的なことを言ってましたが直してみました。
これについては正確に再現させて修正を確認したので問題ないと思います。
一応、今日全体的に動かしてみてデグレードがないことが確認できたら公開します。

**Comment by hirozou** [comment]
早速の対応ありがたいです！
公開待ってます。

**Comment by anoyetta** [comment]
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v6.9.1-190515.2007
致命的なバグがないことを確認できたのでプレリリースしておきました。
i-notice については旧バージョンでの現象の再現、新バージョンでの解消を確認しています。
これで問題ないと思います。

**Comment by hirozou** [comment]
修正ありがとうございました。
私も解消していることを確認しました。

**Comment by anoyetta** [comment]
ご報告ありがとうございます。
絶バハ頑張ってください m(_ _)m
