### ISSUE TITLE
yukkuriを旧バージョンのままで使いたい

### ISSUE THREAD

**Issue by seventh-lease** [anoyetta/ACT.Hojoring#187]
Hojoringを入れたところDiscordでVCをしながらだとyukkuriの読み上げの音声が食い合ってしまうのかどちらの音声もとぎれとぎれで聞こえなくなってしまいました。
yukkuriは旧バージョンのほうではVCしながらでも問題なく使えているのでこのまま旧バージョンを使いながらスペスペやウルスカをHojoringのものを使いたいのですが可能でしょうか？
ちなみにスペスペも旧バージョンのものを使用しています。

一度Hojoringを全部入れてみたところyukkuri以外は問題なくプラグインできました。
yukkuriだけがダメでした。

**Comment by anoyetta** [comment]
原則的に最新版での動作しか考慮していないです。
