### ISSUE TITLE
PCが強制終了になって再起動したらACTがエラーになりました

### ISSUE THREAD

**Issue by ar600m9** [anoyetta/ACT.Hojoring#189]
PCが強制終了になって再起動したらACTがエラーになりました
[ACT.Hojoring.2019-05-18.log](https://github.com/anoyetta/ACT.Hojoring/files/3195285/ACT.Hojoring.2019-05-18.log)
[ACT.Hojoring.2019-05-19.log](https://github.com/anoyetta/ACT.Hojoring/files/3195287/ACT.Hojoring.2019-05-19.log)
[ACT.Hojoring.2019-05-20.log](https://github.com/anoyetta/ACT.Hojoring/files/3195289/ACT.Hojoring.2019-05-20.log)
[Advanced Combat Tracker.log](https://github.com/anoyetta/ACT.Hojoring/files/3195290/Advanced.Combat.Tracker.log)

恐れ入りますがご確認いただけますでしょうか。よろしくお願いいたします。

**Comment by anoyetta** [comment]
timeline.config が壊れていると思います。
そのファイルを一旦削除すると良いでしょう。
