### ISSUE TITLE
[SpecialSpellTimer]一時的に表示するチェックいれないと表示されない

### ISSUE THREAD

**Issue by theoricon** [anoyetta/ACT.Hojoring#19]
掲題の通り
チェック入れたら、表示されますが
![default](https://user-images.githubusercontent.com/33687775/32833047-84160da8-ca38-11e7-915f-230d9036633c.png)
チェックはずしたら、表示されなくなりました
![2](https://user-images.githubusercontent.com/33687775/32833093-ac1dddbc-ca38-11e7-965a-211c5e1ac794.png)
ACT本体とwindowsを再インストールもしてみましたが、同じ状況でした
どう設定したらいいでしょうか
ACT.SpecialSpellTimer-v1.19.4までは正常に表示されますが、v.1.20以降のバージョンは表示されません
いまもv1.19.4を使っています、新しいバージョン使いたいです、お助けください！

**Comment by anoyetta** [comment]
使い方を間違えているのではないでしょうか？
一時的表示する設定はレイアウトの確認用で無条件に常時表示します。それを外した場合は通常通りの動作であり、条件にマッチしたとき表示されます。バージョンは関係ありません。

**Comment by theoricon** [comment]
なに間違えてるのかわかりません・・・
使い方はいままで通りで設定してますが
v1.19.4ではタイマ追加したらすぐ画面に表示されて、ログマッチしたらカウントダウンがはじまりますが、いまのバージョンではログマッチする前に、いくらタイマ追加しても全部画面に表示されません。

v1.19.4使い続けるしかないか＞＜　ありがとうございました

**Comment by anoyetta** [comment]
それはカウント完了後に消去しない設定にしているか消去する設定にしているかの違いでは？

**Comment by theoricon** [comment]
普通タイマ追加したらすぐ下図の赤枠みたいなの表示されますよね？
![1](https://user-images.githubusercontent.com/33687775/32835802-7aae67ba-ca42-11e7-8af8-dcac5238ee44.png)
わたしの場合ではタイマ追加しても、一時的に表示のチェックいれないと赤枠みたいなの表示されません・・・

ちなみにリキャスト完了後に消去は０秒にしてます、リキャスト後に消去しないもチェック入れてます

動画撮りました、これで伝わりやすいかもしれません
https://youtu.be/ClfQsawe5v0

お返事ありがとうございます！

**Comment by anoyetta** [comment]
動画あってもなくても解決には影響ありません。
消去を0秒にしていても通常はFFXIVが起動していなければオーバーレイは表示されません。

**Comment by theoricon** [comment]
画面にうつってませんが、FFIVは起動しています・・・＞＜

**Comment by anoyetta** [comment]
ならログをくれない？

**Comment by theoricon** [comment]
[ACT.Hojoring.HelpMe.2017-11-15.zip](https://github.com/anoyetta/ACT.Hojoring/files/1474903/ACT.Hojoring.HelpMe.2017-11-15.zip)
ログはこれですか、お手数おかけしてすみません・・・

**Comment by anoyetta** [comment]
ログを見ましたが問題ありませんでした。
ゲーム内でも動作を確認しましたが再現しませんでした。

やはり設定で自分でそうしているのでは？
ジョブなどのフィルタが掛かっているとか。

**Comment by anoyetta** [comment]
あなたのスペルの設定を見てみたら、ジョブとゾーンのフィルタがびっしりでした。
おそらくは自分が該当ゾーンにいないだけだと思います。

**Comment by theoricon** [comment]
なるほど！本当にありがとうございます！
