### ISSUE TITLE
[UltraScouter] [Request] My Markerの表示条件の設定の追加

### ISSUE THREAD

**Issue by sheeva-r** [anoyetta/ACT.Hojoring#190]
UltraScouterに内蔵して頂いたMy Markerについて、**戦闘中のみ表示する**オプションを追加して頂きたいです。
（個人的に、戦闘コンテンツ以外では重要ではないため、非表示にしておきたい）

**Comment by anoyetta** [comment]
v6.9.5 で対応しました
