### ISSUE TITLE
続:プレースホルダのハイフン入りのキャラ名について

### ISSUE THREAD

**Issue by sobbat** [anoyetta/ACT.Hojoring#192]
前回はお世話になりました。
すぐにテストする機会がなかったため、リアクションが遅くなってしまい申し訳ないです。
最新バージョンを導入後、コンテンツで動作しない事に気付き、下記のように簡略化した上で試してみましたが、やはり上手くいかなかったので再度ご報告させて頂きます。

**現象の詳細**  
プレースホルダがハイフン入りのキャラ名にヒットしない。

**再現方法**  
1. マッチングワード「`<mex>」, 「<2>」, 「<DPS>」, 「<DPS1>」, 「<RANGE>」, 「ハイフン入り名前決め打ち」`のみのスペルを作成し、正規表現のチェックを入れる。
2. 木人にAAを入れ`「<mex>」`のスペルが動作する事を確認。
3. ハイフン入りの対象とPTを組み、木人にAAを入れてもらう。
4. `「ハイフン入り名前決め打ち」`のスペルのみヒットし、他は動作せず。

**環境**
- 補助輪のバージョン: v6.9.9
- FFXIV_ACT_Pluginのバージョン: v1.7.2.10
- OS: Windows 10 v1809

**追加のコメント**  
関係あるかは分かりませんが、Informationsタブを見ると、
「Yoshida Naoki-producer」という名前が「Yoshida Naoki-Producer」と、ハイフン-の次の文字が大文字になっていました。

* 注意  
[ACT.Hojoring.HelpMe.2019-05-26.zip](https://github.com/anoyetta/ACT.Hojoring/files/3220108/ACT.Hojoring.HelpMe.2019-05-26.zip)

**Comment by anoyetta** [comment]
fixed v6.9.10

**Comment by anoyetta** [comment]
一旦直してみましたが、やはりこの修正はやめました。

正規表現に大文字、小文字を無視するオプションを追加したのですがそれによる負荷の上昇が深刻だったためです。

なお内部的にハイフン後の文字が大文字になってしまうのは sharalayan の仕様です。sharlayan がキャラ名に名前としての正規化をかけています。これによって姓と名の頭が大文字になるようになど名前としての正規の形に整えられます。これによってハイフンの後の文字も大文字になってしまうのです。
逆に言えば、ハイフンを含む名前の場合ハイフン後は大文字始まりが一般的であるとも言えます。どうしてもハイフンを入れるとしてもその後の一文字目は大文字にしたほうがいいでしょう。

**Comment by sobbat** [comment]
ご対応ありがとうございます。
私自身はハイフン入りの名前ではないのですが、PTメンバーにいた場合、プレースホルダを使用しているとスキルの使用などを把握出来なかったため残念です。

また、キャラクリで試してみたところ、FF14の命名は姓名それぞれの頭文字は自動で大文字になり、それ以外に大文字は使えないようです。
