### ISSUE TITLE
Party Deaths?

### ISSUE THREAD

**Issue by majesticuni** [anoyetta/ACT.Hojoring#193]
Every time that someone dies the plugin shows the name, arrow, of who died. 

I cant find anywhere in the plugin on how to disable this, ive tried turning off everything but it still didnt work.

Is this an option? because this is pretty annoying to see.

**Comment by rdj** [comment]
Plugins > ULTRA SCOUTER > Config > Mob
Open target mob list
Remove the line
```
[DEADMEN] DEAD 1000 false
```
Reload target mob list

**Comment by majesticuni** [comment]
> Plugins > ULTRA SCOUTER > Config > Mob
> Open target mob list
> Remove the line
> 
> ```
> [DEADMEN] DEAD 1000 false
> ```
> 
> Reload target mob list

thank you!
