### ISSUE TITLE
Overlay Items are tiny

### ISSUE THREAD

**Issue by Jbols92** [anoyetta/ACT.Hojoring#194]
When I use this plugin my act overlay and my act window are resized and very small. Can i get everything to normal size?

**Comment by stu4355226** [comment]
I had to uninstall the plugin. Making font size fixed is a god damn bad idea....

**Comment by TamaZooo** [comment]
多分これで解決出来ると思います。
https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#hojoring%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%97%E3%81%9F%E3%82%89%E4%B8%80%E9%83%A8act%E3%81%AEui%E3%81%8C%E5%A4%A7%E3%81%8D%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E6%8F%8F%E7%94%BB%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%8B
