### ISSUE TITLE
ACT.Hojoring not support windows 10 Scale setting

### ISSUE THREAD

**Issue by xyuelin** [anoyetta/ACT.Hojoring#196]
### **before add hojoring plugin,act is fine,but after add hojoring plugin ,act's interface is abnormal。**

![before](https://user-images.githubusercontent.com/32188997/59195089-a5e77500-8bbd-11e9-8c74-db41351eef4a.png)
![after](https://user-images.githubusercontent.com/32188997/59195098-ab44bf80-8bbd-11e9-896c-6444f1cc7aa5.png)

**Comment by enemeone** [comment]
I have same issue

**Comment by TamaZooo** [comment]
try this faq

https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Hojoring%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%97%E3%81%9F%E3%82%89%E4%B8%80%E9%83%A8ACT%E3%81%AEUI%E3%81%8C%E5%A4%A7%E3%81%8D%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E6%8F%8F%E7%94%BB%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%8B
