### ISSUE TITLE
5.0 plugin

### ISSUE THREAD

**Issue by kagekitsune** [anoyetta/ACT.Hojoring#199]
**Describe the bug**
act Plugin updated for 5.0, using beta 7.1.5 getting this error when starting
System.TypeLoadException

Could not load type 'FFXIV.Framework.FFXIVHelper.FFXIVReaderStartingResult' from assembly 'FFXIV.Framework, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass25_0.<InitPluginCore>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
**To Reproduce**

**Screenshots**

**Environment**
- ACT.Hojoring Version: 7.1.5
- FFXIV_ACT_Plugin Version: 2.0.2.1
 - OS: win 10

**Additional context**

**Comment by ceanadh** [comment]
Same for me :(

**Comment by kris994** [comment]
Same here

**Comment by someONEgood** [comment]
This seems to be a conflict with old config files.
Go to C:\Users\%\AppData\Roaming\ and delete the Advanced Combat Tracker folder.
You will lose your previous configurations but at least it should launch and allow you to do a clean install of ACT etc.

**WARNING: YOU WILL LOSE YOUR PREVIOUS CONFIGURATIONS AND WILL NEED TO RECREATE THEM.**

**Comment by ceanadh** [comment]
Nah that one didnt work

**Comment by kagekitsune** [comment]
tried that, same error.

**Comment by citrouille** [comment]
delete your entire Hojoring folder and reinstall.

**Comment by kagekitsune** [comment]
Citrouille, i have Uninstalled ACT, deleted roaming folder and did a fresh install and still getting the same error
System.TypeLoadException

Could not load type 'FFXIV.Framework.FFXIVHelper.FFXIVReaderStartingResult' from assembly 'FFXIV.Framework, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass25_0.<InitPluginCore>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

is there anything else i could try?

**Comment by anoyetta** [comment]
DLLの配置などが正しくないのだと思います。
v7からはフォルダの構成を整理しました。その関係でv6にそのまま上書きすると正しくロードされない可能性があります。

正しいアップデート手順をリリースノートに書きました。
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v7.1.5-190630.1014
これを読んでアップデートしてください。

**Comment by aspaosa** [comment]
同じ現象が発生しております。
ACT及びHojoringフォルダと
C : \ Users \ (Your User) \ AppData \ Roaming \ 内のACT関連フォルダを削除し
再度ダウンロードからやってもやはり同じ状況になってしまいます。

Hojoringのプラグインを追加する段階で下記のようなエラーが出ます。

![aaa](https://user-images.githubusercontent.com/52389826/60405576-02054e00-9bec-11e9-86b1-b124850561f5.png)

**Comment by anoyetta** [comment]
メッセージの通りそのDLLがないのだと思います。
すなわち配置が間違っている

**Comment by kagekitsune** [comment]
thank you anoyatta that worked! used the pre release update option. :D

**Comment by aspaosa** [comment]
https://www.anoyetta.com/entry/2019/04/08/132603#3-%E8%A3%9C%E5%8A%A9%E8%BC%AA%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E4%BD%9C%E6%A5%AD
上記の導入記事を参照し、この通りdllを配置しているのですがこの配置の通りだと新バージョンだとエラーになるのでしょうか？

**Comment by anoyetta** [comment]
なりません。

**Comment by aspaosa** [comment]
ありがとうございます。
DLLの解凍がうまくいっていなかったようでDLし直しで起動できました。
お騒がせいたしました、

**Comment by ceanadh** [comment]
No offense, but can you write in english?
Still having the error with the new version.

**Comment by kagekitsune** [comment]
easy way to do it is to uninstall and reinstall then install the 6.0 version that worked, load the plugin it will tell you it wont work on the new 5.0 plugin but it will still show you the tabs, go to Hojoring tab and just under the update button check the box use Pre-Release then click update and profit.
