### ISSUE TITLE
Wrong Y position in Ultra Scouter

### ISSUE THREAD

**Issue by RKI027** [anoyetta/ACT.Hojoring#200]
**Describe the bug**
Since Shadowbringers, Y position in Ultra Scouter seems wrong

**To Reproduce**
Go next to mob from mob list, check 'Visible Me'
Review positions

**Screenshots**
![image](https://user-images.githubusercontent.com/3882253/60411631-384cc880-9c00-11e9-8965-7b3793606798.png)
My Y-position is 25.2, overlay shows Y-position for me and mob of 22.6.
This is in Kholusia zone (in case it's related to the map transforms which are zone-specific)

**Environment**
FFXIV_ACT_Plugin v2.0.2.2
ACT.Hojoring v7.1.5
ACT.SpecialSpellTimer v2.12.0
ACT.UltraScouter v1.9.1
ACT.TTSYukkuri v4.3.0
OS: Win10 1803

**Comment by anoyetta** [comment]
モブリストの座標はゲームで表示される座標と必ずしも一致するわけではありません。

**Comment by RKI027** [comment]
I'm sorry to insist but the difference doesn't seem to be within normal error.

Here's another, more visible example.
![image](https://user-images.githubusercontent.com/3882253/60419263-6c7fb380-9c17-11e9-967a-45b97e04c3cb.png)

お忙しいところ、すみません。もう一度見てもらえないですか。

**Comment by exeedz** [comment]
ultrascouter's coordinates is never as accurate as the in-game coordinates so far, treat it as its own coordinates.

**Comment by RKI027** [comment]
It was never as wrong as that, though... it seems the scaling factor for the Y coordinate is orders of magnitude to small: Ultra Scouter Y-pos barely changed when my in-game position changed from 25 to 11.

**Comment by RKI027** [comment]
I had a look at the code, I can't be certain after a cursory glance but it seems the conversion happens within Hojoring and with constant factors (offset/pitch). If that's the case, no surprise it's different but I am surprised it worked so well (as far as I have noticed) in pre-ShB zones, but that makes me think I'm probably missing something.

**Comment by anoyetta** [comment]
正しい計算式が分かるようならば、それを教えてもらえば搭載しますよ

**Comment by RKI027** [comment]
It's actually a bug in ACT_FFXIV. Y and Z were switched. I suppose Ravahn will release a fix soon.

**Comment by anoyetta** [comment]
i see. Ravahn known this issue?
I have to tell if he do not know.

**Comment by RKI027** [comment]
He knows, it was discussed on discord.
