### ISSUE TITLE
Could not load type 'FFXIV.Framework.FFXIVHelper.FFXIVReaderStartingResult' from assembly

### ISSUE THREAD

**Issue by PommeVerte** [anoyetta/ACT.Hojoring#202]
**Describe the bug**
I get the following error message at launch since the most recent update:
```
System.TypeLoadException

Could not load type 'FFXIV.Framework.FFXIVHelper.FFXIVReaderStartingResult' from assembly 'FFXIV.Framework, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass25_0.<InitPluginCore>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**To Reproduce**
1. Upgraded to recent build (for FFXIV ACT 2.0 > hojoring 7.1.6)
2. Run ACT
3. Enable FFXIV ACT plugin (nothing else)
4. Enable SpecialSpellTimer.dll plugin (version `2.12.0.0`)
5. Get error.

**Environment**
- ACT.Hojoring Version: 7.1.6
- ACT Version: 3.3.4.259
- FFXIV_ACT_Plugin Version: 2.0.2.2
 - OS: Windows 10

**Additional information**

I found the following on the FFXIV ACT plugin site : 
```
Two dlls are included. Most users should download FFXIV_ACT_Plugin.zip. Plugin authors can use FFXIV_ACT_Plugin_2.0.2.1.zip, which extracts the additional assemblies for reference. These assemblies are already embedded in the FFXIV Plugin dll.
````
I'm assuming I using the base plugin that doesn't have the added assemblies?

**Comment by PommeVerte** [comment]
Closed because I thought I might not be up to date but turns out I am. So reopening.

**Comment by ViciousBoss** [comment]
Also having the same issue as of the recent v7.1.7 update.

**Comment by Lifell** [comment]
This is apparently not a Hojoring issue. Had the same issue and a fresh install of the Hojoring files fixes this. I had a lot of old files that aren't used anymore.

Apparently copy and pasting (while overwriting everything) is a bad idea for updating Hojoring. Had a lot of old files that simply aren't used anymore. Simply delete all the files of Hojoring and backup the "MobList.en-US.txt" if you use it.

Download the latest release, unblock the .zip and just extract like usual again.

**Comment by ViciousBoss** [comment]
> This is apparently not a Hojoring issue. Had the same issue and a fresh install of the Hojoring files fixes this.
> 
> Apparently copy and pasting (while overwriting everything) is a bad idea for updating Hojoring. Had a lot of old files that simply aren't used anymore. Simply delete all the files of Hojoring and backup the "MobList.en-US.txt" if you use it.
> 
> Download the latest release, unblock the .zip and just extract like usual again. Of course placing the "MobList.en-US.txt" back in your "Resources" folder.

Will go ahead and try, but before I do, are there any other files I should backup? In particular, which files are associated with all of my spell timers?

**Comment by Lifell** [comment]
> 
> 
> > This is apparently not a Hojoring issue. Had the same issue and a fresh install of the Hojoring files fixes this.
> > Apparently copy and pasting (while overwriting everything) is a bad idea for updating Hojoring. Had a lot of old files that simply aren't used anymore. Simply delete all the files of Hojoring and backup the "MobList.en-US.txt" if you use it.
> > Download the latest release, unblock the .zip and just extract like usual again. Of course placing the "MobList.en-US.txt" back in your "Resources" folder.
> 
> Will go ahead and try, but before I do, are there any other files I should backup? In particular, which files are associated with all of my spell timers?

No idea. Those might be saved someplace else? %appdata% perhaps?

**Comment by anoyetta** [comment]
%APPDATA%\anoyetta

**Comment by valy1234** [comment]
I tried deleting the entirety of Hojoring once then starting with a fresh extraction of the ZIP, but I still got the error. So I went and did something else for a while then came back and tried the exact same thing again, and it works now. Not gonna press my luck trying to figure out why

**Comment by anoyetta** [comment]
原因が分かりました。
v6系のDLLとv7系のDLLが混ざって配置されているのが原因です。
v6系のDLLは一度全て消してv7を導入しましょう。

リリースノートにもそのように記載しています。
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v7.1.7-190702.0004

**Comment by Lifell** [comment]
For the english peeps: 

> 
> 
> I understand the cause.
> The cause is that v6 DLLs and v7 DLLs are mixed.
> Delete all v6 DLLs once and introduce v7.
> 
> It is stated in the release notes as such.
> https://github.com/anoyetta/ACT.Hojoring/releases/tag/v7.1.7-190702.0004

I don't understand japanese though. Suppose it doesn't hurt using google translate on the release notes next time.

**Comment by valy1234** [comment]
I read Japanese just fine, and followed the instructions under プランA to the letter. Still encountered the problem.

Nevertheless, it is resolved for me and no further investigation is necessary.

**Comment by W0rkingTitle** [comment]
I'm still getting the "Could not load file or assembly" error when I try to add the SpecialSpellTimer.dll and I am not coming from an older version. What do I do?
