### ISSUE TITLE
Can't load ACT.SpecialSpellTimer.dll

### ISSUE THREAD

**Issue by valy1234** [anoyetta/ACT.Hojoring#203]
When trying to add this plugin I get the error:

Could not load file or assembly 'ACT.SpecialSpellTimer.Core, Version= 2.12.00, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. )Exception from HRESULT: 0x80131515

This is with ACT v 3.3.4.259 and Hojoring v7.1.7

**Comment by anoyetta** [comment]
this issue is duplicate. #202

**Comment by W0rkingTitle** [comment]
I have been having this exact same error as well, I am not sure what to do. Help.
