### ISSUE TITLE
Fatal Error. Unhandled Exception.

### ISSUE THREAD

**Issue by 153p** [anoyetta/ACT.Hojoring#204]
System.TypeLoadException

アセンブリ 'FFXIV.Framework, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' から型 'FFXIV.Framework.FFXIVHelper.FFXIVReaderStartingResult' を読み込めませんでした。
   場所 ACT.TTSYukkuri.PluginCore.<>c__DisplayClass26_0.<InitPlugin>b__0()
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[https://gyazo.com/9b5178548a3f3302c90039d9c1ad5478](url)

**Comment by anoyetta** [comment]
#203

**Comment by 153p** [comment]
同じ物が三枚出ます
