### ISSUE TITLE
Load problem

### ISSUE THREAD

**Issue by sarari-chan** [anoyetta/ACT.Hojoring#205]
when i tried to load UltraScouter,it said

Could not load file or assembly 'file:///D;\%APPDATA\anoyetta\ACT\bin\ACT.UltraScouter.Core.dll' or one of its dependencies. Operation is not supported. )Exception from HRESULT: 0x80131515

so i tried to load UltraScouter.Core,

Could not load file or assembly 'Prism, Version=7.1.0.431, Culture=neutral, PublicKeyToken=400ee6c3ax184dc59' or one of its dependencies.

it seems like i lost some files of prism.How can i get it?

- ACT.Hojoring Version:Newest
- FFXIV_ACT_Plugin Version: Same
 - OS: Win 10
Already installed Framework 4.7.2 and Microsoft Visual C++ 2017 Redistributable

**Comment by anoyetta** [comment]
根本的にインストール方法が間違っていると思われます。
私のブログのほうでACT本体も含めて詳細なインストール手順を掲載しています。
そちらを参照して再セットアップを行いましょう。
https://www.anoyetta.com/

あとv7の取扱についてはリリースノートを読みましょう。
https://github.com/anoyetta/ACT.Hojoring/releases

**Comment by sarari-chan** [comment]
unziped with 7z instead of winrar,and it works.
ありがとうございました。
