### ISSUE TITLE
${victim} produces an NPC name with numbers attached to the front.

### ISSUE THREAD

**Issue by LokiFM** [anoyetta/ACT.Hojoring#208]
**Describe the bug**
The ${victim} now produces a string like "40008BC8:NPC NAME HERE". It randomly started doing this for me on every ${victim} while before it would only just but the NPC name there and not some weird number cope in front.

Is there a way for me to fix this? Have I accidentally enabled some setting or what is going on?

**Screenshots**
https://imgur.com/a/3jbID7y

**Environment**
- ACT.Hojoring Version: 7.1.7
- FFXIV_ACT_Plugin Version: 2019-07-04 update
 - OS: Windows 10 Pro 64-bit

**Additional context**
It was working fine yesterday morning and now it just seems to not want to produce a victim name without a number string attached to it.

**Comment by Sythalin** [comment]
It's something with the FFXIV_ACT_Plugin update that screwed it up.  For the time being, you can temp fix it by adjusting triggers with (.+).

For example:

`1A:(.+):(?<victim>.+?) gains blah blah blah`

**Comment by ShannonMasters** [comment]
you could also just use <id8>, ie;   `1A:<id8>:(?<victim>.+?) gains the effect of Dia from <mex>`
