### ISSUE TITLE
[TTSYukkuri]TTS(TCP) でエラー

### ISSUE THREAD

**Issue by alalwww** [anoyetta/ACT.Hojoring#21]
以下のようなエラーが頻発するので報告します。
```
2017-11-19 03:44:03.9869 [Error] 棒読みちゃんの読上げで例外が発生しました。 System.ArgumentException: ストリームに書き込めませんでした。
   場所 System.IO.BinaryWriter..ctor(Stream output, Encoding encoding, Boolean leaveOpen)
   場所 ACT.TTSYukkuri.Boyomichan.BoyomichanSpeechController.Speak(String text)
```
```
2017-11-19 03:47:32.9408 [Error] 棒読みちゃんの読上げで例外が発生しました。 System.ObjectDisposedException: 破棄されたオブジェクトにアクセスできません。
オブジェクト名 'System.Net.Sockets.NetworkStream' です。
   場所 System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   場所 ACT.TTSYukkuri.Boyomichan.BoyomichanSpeechController.Speak(String text)
```

## 症状
狙って再現できないので、正確に症状を確認できたわけではないですが、エラー発生時はエラーになった文章の読み上げはされてないと思います。また、エラー発生と同タイミングかの確認はできていませんが、エラーが発生する戦闘中などログ量が増えてる状態で、読み上げの音声がデフォルトに変わる、音量が変わる、読み上げ速度が非常に低速になる、などが発生することもあります。
また、棒読みちゃん側にエラーが出ることもあります。
(~~エラー内容を記録し忘れてたのでログ取れたら追記します。~~ しました)

## 発生時期
きちんと記録してないので記憶違いでなければですが、Discord連携が入ったか、UI変更がされたあたりから発生するようになったよう記憶しています。それ以前ではおきていませんでした。

## 再現性
確実な再現手順はないですが、ログ量の多いコンテンツほど発生頻度は上がるように思えます。
ソロではほぼ見ませんが、4人ID、8人レイド、モブハン、24レイドなど、高頻度でログが流れるコンテンツになるほど多発します。テストボタンの連打では今のところ再現してません。

## 環境
Win10Pro、DX11、棒読みちゃん Ver0.1.11.0 Beta 16
FFXIV_ACT_Plugin v1.6.1.8、ACT.Hojoring v4.0.9、ACT.TTSYukkuri v3.3.0

TTS.Yukkuri -> TCP -> 棒読みちゃんの環境です。
再生方式はWASAPIで、サブ再生デバイスは無効。

CustomTriggersは40程度、スペスペのSpells/Tickersはおよそ60程度あり、全てではないですが多くをTTSに流してます。

スタックトレースだけ見ると、GCされてしまったオブジェクトやGCされたことで閉じられてしまったストリームにアクセスして発生してそう？非同期処理に起因する問題とか、かも？

----
anoyetta/ACT.TTSYukkuri#10 から移動

**Comment by alalwww** [comment]
あまり参考になる情報ではないと思いますが、棒読みちゃん側で確認できたエラーも貼っておきます。

```
[2017/11/19(日) 05:19:46.674] - エラー
AddTalkTask
指定された声質は存在しません(-1)

[2017/11/19(日) 05:19:47.168] - エラー
ConvertToWavDataSAPI5
SAPI50のWAV生成でエラー
System.Runtime.InteropServices.COMException (0x80045012): HRESULT からの例外: 0x80045012
   場所 SpeechLibA.SpVoiceClass.Speak(String Text, SpeechVoiceSpeakFlags Flags)
   場所 FNF.Utility.BouyomiChan.ConvertToWavDataSAPI5(String sTalk, Int32 iSpeed, VoiceType vType, Byte[]& bWavData, SpVoice _SpVoice)

[2017/11/19(日) 05:20:31.104] - エラー
TCPサーバ
System.ArgumentException: 文字コードの指定に誤りがあります
   場所 FNF.BouyomiChanApp.BouyomiChanTcpServer.ProcessStream(Stream s)
   場所 FNF.BouyomiChanApp.BouyomiChanTcpServer.AcceptTcpClientCallback(IAsyncResult result)

[2017/11/19(日) 05:36:24.295] - エラー
TCPサーバ
System.ArgumentOutOfRangeException: 負の値ではない数値が必要です。
パラメータ名: count
   場所 System.IO.BinaryReader.ReadBytes(Int32 count)
   場所 FNF.BouyomiChanApp.BouyomiChanTcpServer.ProcessStream(Stream s)
   場所 FNF.BouyomiChanApp.BouyomiChanTcpServer.AcceptTcpClientCallback(IAsyncResult result)
```

**Comment by anoyetta** [comment]
次のバージョンで対策を入れます。

原因を明確に特定できないのですが、現象から察するに棒読みちゃんへのパケットの送信が非同期に複数発生し、ストリームの破棄と書き込みが同時に発生しているようです。
棒読みちゃん側のエラーからも前述の可能性が推察されます。

対策は下記の通り。
* ネットワークストリームへの書き込みに排他制御をかける
* 他の再生方式と同様に一定期間内のまったく同じテキストの発声を抑制する
これはこの現象への対策というよりも他との動作の整合性のため、ごく短期間に同じテキストを発声する意味がないためです。
