### ISSUE TITLE
Timers not triggering/displaying

### ISSUE THREAD

**Issue by Krojack** [anoyetta/ACT.Hojoring#211]
Ever since ShB and the updates my timers won't trigger or display.  Everything else seems to work such as logging.  I can "Temporarily Display" timers and they show up but when using something such as Lucid Dreaming it just won't trigger anymore.

I'm using the following regex:
`1A:10647899:<me> gains the effect of Lucid Dreaming from <me> for 21\.00 Seconds\.`

The ONLY thing I see that might be broken is when I go to Zone Filters nothing shows up. It's just a large grey dialog window.

I've tried deleting everything and redoing the plugins. I even deleted my **%APPDATA%\anoyetta** folder.  Still didn't fix anything.

**Comment by anoyetta** [comment]
```1A:10647899:<me> gains the effect of Lucid Dreaming from <me> for 21\.00 Seconds\.```
これの「10647899」は不定のIDです。よって固定値でパターンを定義してもマッチしません。
8桁の16進数としてパターンを定義しましょう。

**Comment by Krojack** [comment]
That's right from the log file that the plugin saves.
```
[01:09:05.116] 15:10647899:Avellin Adorel:1D8A:Lucid Dreaming:10647899:Avellin Adorel:F40F:4B40000:0:0:0:0:0:0:0:0:0:0:0:0:0:0:70234:70234:8400:10000:0:1000:-912.3367:183.3043:0.1527065:-1.711838:70234:70234:8400:10000:0:1000:-912.3367:183.3043:0.1527065:-1.711838:
[01:09:05.879] 1A:10647899:Avellin Adorel gains the effect of Lucid Dreaming from Avellin Adorel for 21.00 Seconds.
[01:09:26.820] 1E:10647899:Avellin Adorel loses the effect of Lucid Dreaming from Avellin Adorel.
```

Even if I change the regex to just
`:<me> gains the effect of Lucid Dreaming from <me> for 21\.00 Seconds\.`
It still doesn't trigger the timer.

Those extra digits weren't there before SbH was released either. I use to have the following as the trigger:
`1A:<me> gains the effect of Lucid Dreaming from <me> for 21\.00 Seconds\.`

Now if I use the standard Custom Triggers that's built into ACT it works.  I would just rather have these awesome looking timers
`<Trigger R="1A:10647899:Avellin Adorel gains the effect of Lucid Dreaming from Avellin Adorel for 21\.00 Seconds\." SD="Lucid Dreaming" ST="3" CR="F" C="WHM" T="F" TN="" Ta="F" />`
