### ISSUE TITLE
Plugin error after update to v7.3.3

### ISSUE THREAD

**Issue by beamioo** [anoyetta/ACT.Hojoring#214]
Hi,
I just recently updated to v7.3.3 via the auto updater and yukkuri and everything won't load up. 
I tried manually installing also, but I'm still getting the error.
Here's the error message.

![image](https://user-images.githubusercontent.com/53119626/61579751-d7981800-ab3b-11e9-98ac-0b6cc446ab87.png)

**Comment by Surged28** [comment]
Also getting an error since the update https://i.imgur.com/EMSDtmL.png

**Comment by omegasrevenge** [comment]
Cactbot stopped working (without any error messages in any log) after updating to 7.3.3. Rerolling to an older version got cactbot working again. Very weird interaction!

**Comment by Rasbar430** [comment]
I'm also getting that error in the imgur link, not sure how to roll back to an older version though :(

**Comment by beamioo** [comment]
Thanks for the fix!
