### ISSUE TITLE
3s Ticker cannot sync to MP ticks anymore

### ISSUE THREAD

**Issue by jjvliu** [anoyetta/ACT.Hojoring#218]
After MP Timer was changed to 3s Ticker, I can no longer use it in the original way. I really miss this feature on BLM. Please add an option to use it as MP timer again!

- ACT.Hojoring Version: v7.3.x+ (v7.4.8)
- FFXIV_ACT_Plugin Version: v2.0.2.7
 - OS: Windows 10

**Comment by onikirimaruchan** [comment]
me too.

**Comment by jjvliu** [comment]
I just returned to FFXIV and found that the MP ticker is working again. It was probably fixed in v7.8.7.

- ACT.Hojoring v7.15.5

ありがとう anoyetta!
