### ISSUE TITLE
Cannot change language from default Japanese

### ISSUE THREAD

**Issue by CallMeSai** [anoyetta/ACT.Hojoring#219]
**Describe the bug**
After loading ACT and accessing plugins, SPESPE, options, language and clicking on the UI and FFXIV language to EN-US and rebooting ACT, the language in triggers, timeline, options and informations is still written in japanese.

I have checked the config file and the language is set to EN in there.

Waiting until timers appear on screen before checking plugin settings and still in Japanese

**To Reproduce**
Launch ACT,
Plugins,
SPESPE,
Options,
Language,
UI and FFXIV Language set to en-US.
Reboot ACT,
Plugins,
SPESPE,
Observe no language change.

**Screenshots**
(had to change to .txt to upload
[ACT.SpecialSpellTimer.txt](https://github.com/anoyetta/ACT.Hojoring/files/3428205/ACT.SpecialSpellTimer.txt)

**Environment**
- ACT.Hojoring Version: 7.4.9
- ACT.SpecialSpellTimer: 2.12.0
- FFXIV_ACT_Plugin Version: 2.0.2.7
 - OS: Windows 10

**Additional context**

**Comment by bushymark** [comment]
Same issue. Upon restart, the language has not changed from JP, and the configuration has reset itself to JP

**Comment by anoyetta** [comment]
thank you for reporting.

it's bug.
i'll fix to next version.
