### ISSUE TITLE
would like to select which timer is announced on discord and which one is announced to me only

### ISSUE THREAD

**Issue by G0li4th** [anoyetta/ACT.Hojoring#22]
on a timer configured on specialspell timer if i dont check the box "notify discord" the sound is always announced on discord.

for me its a pb because i would like to have some timer announced on discord and other announced to me only (not on discord).

could we have an option to selevt the one announced on discord and the one announced to the user only.

**Comment by anoyetta** [comment]
Implemented on v5.x.x.

**Comment by G0li4th** [comment]
Thx you rocks ! I'll test it asap
