### ISSUE TITLE
ACT.Hojoring.Updater.dll is missing

### ISSUE THREAD

**Issue by Sehrz** [anoyetta/ACT.Hojoring#221]
Ahoi ! First of all, thanks for reading, maybe helping me, and sorry for my bad english.

I've got an issue with this dll item, my firewall keeps shooting it up into quarantine.
That's a prob because I never can update Hojoring.
I tried to restaure it and set an exception but still. I now can have it on my desktop, but can't drag'n'drop it into Hojoring folder (it says I ain't got admin rights to do this).

Any suggestion ? 

Again, thanks a lot to the ones who might try to help me !
Cheers !

**Comment by JamieAzure** [comment]
Set up an exception for your antivirus for that particular file (or the folder you want to put it in).  Mine detects that that file has a Perseus variant virus in it, but I'm assuming it's a misdiagnosis.  Once you have the exception in place then you can extract the file to the location you need it.
