### ISSUE TITLE
補助輪が出力する一部のEncounter Logが、スペスペのタイムラインのトリガーでマッチしない

### ISSUE THREAD

**Issue by IrisAinsworth** [anoyetta/ACT.Hojoring#223]
**現象の詳細**  
補助輪が出力する下記のようなEncounter Logが、スペスペのタイムラインのトリガーでマッチしない。

```
[hh:mm:ss.fff] 00:0000:Hojoring:[TL] エレボスの巨腕 starts using 虚ろなる悪意. X=24.50 Y=23.50 Z=0.00. ID=3E59 duration=5.2
```

**再現方法**  
1. 下記のようなタイムライン定義を作成する
```
<?xml version="1.0" encoding="utf-8"?>
<timeline>
  <name>希望の園エデン零式：覚醒編2</name>
  <rev>rev1</rev>
  <zone>Eden's Gate: Descent (Savage)</zone>
  <locale>JA</locale>
  <entry></entry>
  <author>iris</author>
  <license>CC BY-SA</license>

  <t text="ドゥームヴォイド・ギロチン" sync="starts using ドゥームヴォイド・ギロチン" notice="直線範囲" >
    <v-notice text="直線範囲" duration="6" duration-visible="false" />
  </t>
  <t text="虚ろなる悪意" sync="エレボスの巨腕 starts using 虚ろなる悪意. X=22.50 Y=23.50 Z=0.00. ID=3E59" notice="左側移動" >
    <v-notice text="左側移動" duration="5" duration-visible="false" />
  </t>
  <t text="虚ろなる悪意" sync="エレボスの巨腕 starts using 虚ろなる悪意. X=24.50 Y=23.50 Z=0.00. ID=3E59" notice="右側移動" >
    <v-notice text="右側移動" duration="5" duration-visible="false" />
  </t>
</timeline>
```

2. `希望の園エデン零式：覚醒編2` に突入し、戦闘を開始する
3. `虚ろなる悪意` のトリガーが反応しない

**環境**
- FFXIV_ACT_Plugin v2.0.2.9
- ACT.Hojoring v7.5.0
- ACT.SpecialSpellTimer v2.12.0
- ACT.UltraScouter v1.9.2
- ACT.TTSYukkuri v4.3.0
- OS:  Windows 10 v1809

**追加のコメント**  

下記の事項は確認済みです。
* `ドゥームヴォイド・ギロチン` は読み上げが行われる
  * FFXIV_ACT_Plugin側が出力するログにマッチしていると思われる
* ACT本体の `Custom Trigers` の機能で、虚ろなる悪意のsyncに指定している内容を `Regular Expression` に設定して作成すると読み上げは行われる
* 他のコンテンツ (魔神セフィロト討滅戦)でタイムラインを作成し、 `ID=16DB` といった単純なトリガーを作成しても反応しない

同じくEncounter Logに出力されるETTickは反応するため、当該のログもマッチすることを期待しておりました。
マッチしないのは仕様なのでしょうか。

**Comment by anoyetta** [comment]
[TL] が付いているログはTLではヒットしません。
なぜならば、TLが生成しているログであるためです。
ログの生成→ログのヒット→ログの生成・・・
と無限ループを起こしてしまう可能性があるからです。

**Comment by IrisAinsworth** [comment]
当該ログが使えるとタイムラインが楽に書けると思ったのですが、そのような背景があるのですね。
`expressions` タグを使って書くようにします。
ありがとうございました。
