### ISSUE TITLE
Error for Ultra Scouter and Special Spell Timer 7.5.1

### ISSUE THREAD

**Issue by aldotsk** [anoyetta/ACT.Hojoring#228]
Keep getting this issue and never had one since yesterday before ACT updates happened. Please fix this.

![image](https://user-images.githubusercontent.com/53849967/62596426-469d9c80-b8b0-11e9-8de3-c828f2eb698d.png)

![image](https://user-images.githubusercontent.com/53849967/62596419-3daccb00-b8b0-11e9-937e-341c6067352d.png)

![image](https://user-images.githubusercontent.com/53849967/62596409-338acc80-b8b0-11e9-945a-40fcc9e0feb4.png)

**Comment by majesticuni** [comment]
getting the same as well once i updated it today
