### ISSUE TITLE
ワンポイントテロップ

### ISSUE THREAD

**Issue by tts2017** [anoyetta/ACT.Hojoring#23]
スペシャルスペルタイマのようにルートフォルダで項目を一括管理できるようにしてほしい。

**Comment by anoyetta** [comment]
いろいろと勘違いしているようなので解説します。

まず、スペルのほうにはパネルという概念があります。これはスペルを配置するためのWindowです。位置などはWindow単位で決定するためであったり、スペルの位置をまとめるために存在します。一括して設定を変更するような機能はありません。

対してテロップは、一つ一つが独立したWindowであるためスペルのようなパネルの概念が必要ありません。位置などはそれぞれが単独で持っています。

したがって、スペルのほうはパネルがあるので必然的にその設定が必要なのでその設定がある。テロップの方はその必然性がないのでないということになります。また、スペルのほうも一括設定という機能はありません。

**Comment by anoyetta** [comment]
その後、特にないようなのでクローズします
