### ISSUE TITLE
ACT crashing after latest hojoring update

### ISSUE THREAD

**Issue by REVERSE-MISAYA** [anoyetta/ACT.Hojoring#230]
**Describe the bug**
act crashes after updating hojoring to latest version

**To Reproduce**
i dont know

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/dd473918eaad6ea6785854a9339593e9/raw)](https://gyazo.com/dd473918eaad6ea6785854a9339593e9)

**Environment**
- ACT.Hojoring Version: v7.6.3
- FFXIV_ACT_Plugin Version:  v2.0.2.9 // ACT says: 3.4.1 release 261 ???
 - OS: windows 10

**Comment by maja6791** [comment]
I'm getting the same error.

**Comment by anoyetta** [comment]
手動で [v7.6.5](https://github.com/anoyetta/ACT.Hojoring/releases/tag/v7.6.5-190810.0249) に更新しましょう。

1. v7.6.5 の7zアーカイブをダウンロードする
2. 7zアーカイブを解凍する
3. Hojoringのインストールディレクトリに上書きする
