### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by tiptop99** [anoyetta/ACT.Hojoring#234]
I am attempting to get 5.9.5 to work on windows 7 with ACT so i can just solely just use the distance feature for my mnk rotations. i have managed to get the plugin to boot etc but nothing shows on my screen. i have noticed under the help section i get this message.
2019-08-11 22:24:29.1422 [Error] Attach FFXIV_ACT_Plugin error System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIV.Framework.FFXIVHelper.FFXIVPlugin.LoadSkillToFFXIVPlugin()
   at FFXIV.Framework.FFXIVHelper.FFXIVPlugin.MergeSkillList()
   at FFXIV.Framework.FFXIVHelper.FFXIVPlugin.<Start>b__31_0(Object s, ElapsedEventArgs e)

is this stating its not finding act due to being out of date? or is there another way to get hojo to work with win 7? any help would be great.
thanks

-ACT.Hojoring Version:5.9.5
- FFXIV_ACT_Plugin Version: 2.0.2.9
 - OS: win7

**Comment by Tsunayoshi** [comment]
https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-7-support

I know u dont wanna hear it but u should change ur os. its time - even u dont wanna hear it, it wont change the fact that win7 is 10!! years old and outdated.
Just change to win10 and all is working fine.

**Comment by tiptop99** [comment]
I do prefer 7 to 10 yes. But this was back in August I moved on since then.
And the pc in question won't upgrade as it comes up with a boot OS installation failure so that option was out of the question with win10.
So thanks for the comment but it's old news.
