### ISSUE TITLE
[Feature Request] SPESPE: Evaluate placeholder as a Trigger Condition

### ISSUE THREAD

**Issue by sheeva-r** [anoyetta/ACT.Hojoring#245]
プレースホルダの内容をスペルの前提条件として評価する
（例）代名詞 <4ex> が \<HEALER\> に含まれる（または一致する）場合、このスペルが有効になる

**Comment by anoyetta** [comment]
前提条件というか現在の実装上の名称としてはフィルタに搭載しますわ。

1. テキストボックスを2つおいて、それぞれにプレースホルダを設定する
2. 2つのプレースホルダの内容が一致したらスペルが有効

こんな機能ですかね。
