### ISSUE TITLE
[Feature Request] SPESPE Timeline: Define default values for iterated activity

### ISSUE THREAD

**Issue by sheeva-r** [anoyetta/ACT.Hojoring#246]
スペスペたいむのタイムライン定義に関する機能要望です。
コンテンツ内で複数回繰り返されるアクティビティに対するデフォルト設定を定義したいです。
そのアクティビティに対するデフォルトのiconやnotice等を一括で設定し、必要ならアクティビティ内で上書きする運用を想定しています。
ご検討頂けると幸いです。

```
<activity-default target-name="タイダルロア"
 text="タイダルロア"
 sync="リヴァイアサンは「タイダルロア」を唱えた。"
 notice="タイダルロア。"
 icon="AllRangeAttack.png" />
```
呼び出し
```
<a time="xxx" name="タイダルロア" />
```
呼び出して上書き
```
<a time="xxx" name="タイダルロア" notice="ここ痛いから回復しっかり" />
```

**Comment by anoyetta** [comment]
便利ですね。OK、搭載します。

**Comment by anoyetta** [comment]
少し違う概念になりましたが搭載しました。
すべてのタグに inherits（継承）という属性を追加しました。
```
inherits="[name]"
```
と指定するとその名前のタグの属性を継承するという仕組みです。
