### ISSUE TITLE
Ultrascouter FFLogs not distinguishing rDPS and aDPS

### ISSUE THREAD

**Issue by TrentGear** [anoyetta/ACT.Hojoring#247]
FFLogs introduced the distinction between aDPS and rDPS recently. When trying out UltraScouter, a friend and I noticed UltraScouter was reporting aDPS instead of rDPS which is the default when browsing the web interface of FFLogs. There was no option inside UltraScouter to choose which result to use.

Speaking to Kihra on the FFLogs discord, they stated "rdps" needs to be passed as the metric, as "dps" is now assumed to mean "adps". Ideally we could choose which report type was used inside the UltraScouter options.

**Comment by majesticuni** [comment]
how do you get this fflogs thing to work? i put the public key in and it says 401 on it and no parses etc

**Comment by wbonbon** [comment]
対応しました
