### ISSUE TITLE
[SPESPE] Spell triggers : Caster DPS JOB filter doesn't exist.

### ISSUE THREAD

**Issue by fenethtool** [anoyetta/ACT.Hojoring#255]
**現象の詳細**  
スペスペのSpell Triggerにて、Generalタブから"自身のジョブによるフィルタ" "パーティメンバのジョブによるフィルタ"の項目があるが、
Caster DPS(召喚士、黒魔導士、赤魔導士）のフィルタリング項目が存在しない。

**再現方法**  
現象の再現方法を記載します。
1. Go to 'SPESPE→Triggers→すべてのスペル'
2. Click on 'General'
3. Scroll down to '"自身のジョブによるフィルタ" or "パーティメンバのジョブによるフィルタ"'

**環境**
- 補助輪のバージョン: v7.7.2
- FFXIV_ACT_Pluginのバージョン: v2.0.4.0
- OS: Windows 10 Pro 

**Screenshot URL**
    * [SS1](https://gyazo.com/7646551d28dd8e40bee09eff63429fbc)
    * [SS2](https://gyazo.com/4fce9632ff4ce5dcf7cd778746313363)

**Comment by anoyetta** [comment]
単純に横スクロールしていないだけではないでしょうか？

**Comment by fenethtool** [comment]
すみません、初歩的な見落としをしていました。ご返信ありがとうございます。
