### ISSUE TITLE
Special spell Timer circle style Border

### ISSUE THREAD

**Issue by DaneelReventelov** [anoyetta/ACT.Hojoring#259]
In circle style I have a thick border, impossible to change nor to make transparent.
Can you solve this?
Ty

**Comment by TamaZooo** [comment]
Try to make 'Stroke color' and 'Fill color' the same color.

**Comment by DaneelReventelov** [comment]
But the animation is always too little. I solved changing point of view.
W=49
H=-16
I also used Reverse direction but I don't think/remember is part of the solution.
