### ISSUE TITLE
スペスペのエラー

### ISSUE THREAD

**Issue by raylaysz** [anoyetta/ACT.Hojoring#261]
**現象の詳細**  
他問題でのブルースクリーン強制再起動後、ACTのSpecialSpellTimerのプラグイン読み込み時にエラーを吐くようになってしまいました

**環境**
- 補助輪のバージョン: v7.8.7
- FFXIV_ACT_Pluginのバージョン: v2.0.4.0
- OS: Windows 10
[ACT.Hojoring.HelpMe.2019-10-08.zip](https://github.com/anoyetta/ACT.Hojoring/files/3699947/ACT.Hojoring.HelpMe.2019-10-08.zip)
![error](https://user-images.githubusercontent.com/56280273/66354854-17cf9f80-e9a1-11e9-8c97-b635bac4bc52.png)

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
    * 現象のスクリーンショットを添付してください

**Comment by TamaZooo** [comment]
BSODが発生した際に、一部の設定が飛んでしまっています。
今回は以下ファイルが破損していますので、Hojoringの自動バックアップ機能で退避されているファイルから復元してみてください。

破損したファイル：`%appdata%\anoyetta\ACT\ACT.SpecialSpellTimer.Panels.xml`

以下ファイルを上記ファイルにまるまるコピーするか、ファイル自体を上書きしてください。
自動退避ファイル：`%appdata%\anoyetta\ACT\backup\ACT.SpecialSpellTimer.Panels.2019-10-01.bak`

**Comment by raylaysz** [comment]
ACT.SpecialSpellTimer.Panelsを削除、ACT.SpecialSpellTimer.Panels.2019-10-01.bakをコピー後
正常に起動するようになりました　本当にありがとうございました
