### ISSUE TITLE
Plugin Crashing ACT

### ISSUE THREAD

**Issue by Krojack** [anoyetta/ACT.Hojoring#264]
**Describe the bug**
ACT crashing when it starts to load the SpecialSpellTimer plugin. I see the Hojoring splash screen popup then the message below pops up and ACT closes.  I have to edit the ACT config to disable/remove the plugin to get back into a working ACT.

**To Reproduce**
Just add ACT.SpecialSpellTimer.dll and activate it in plugins

**Screenshots**
![act-error](https://user-images.githubusercontent.com/908461/69001807-38015100-08b3-11ea-8c07-d70319e5aba3.jpg)

**Environment**
- ACT.Hojoring Version: 7.8.17
- FFXIV_ACT_Plugin Version: ProductVersion: 2.0.4.4
 - OS: Win10
 - ACT version: 3.4.5 Release 265

**Additional context**
It was loading and working for a few days then this started happening out of the blue when I tried to add some custom spell icons into the folder 'resources' folder.  I've since removed everything even configs within my windows user folders.

EDIT: Sorry I put the version of ACT and not the FFXIV ACT plugin. I fixed that.

**Comment by jj19971130** [comment]
You can try to change the game language setting to ja-jp and spespe still works while my ffxiv use the chinese in game.

**Comment by TamaZooo** [comment]
現在リリースされているFFXIV_ACT_Pluginは2.0.4.4が最新ですが、JP/NA/EUリージョン環境でしょうか？

もしCNリージョンの場合、サポート対象外となりますのでご了承ください。

サポート対象外の理由はFAQを参照してください。
https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ

**Comment by Krojack** [comment]
Sorry I fixed the original post. 3.4.5 is the version of ACT.  I am using 2.0.4.4 of FFXIV plugin though.

**Comment by jj19971130** [comment]
I met the same problem as you met and I saw your issue. Now I solved my problem and hope my experience can help you too. 
From the error information at the bottom I found mscorlib and google can autofill mscorlib AggregateException. There might be some problem about mscorlib.dll. As the page https://stackoverflow.com/questions/15061977/what-does-mscorlib-stand-for . mscorlib may means muiltilanguage standard common object runtime library. So I change the plugin language setting(I can click on the act and change things if you don't close the error message box and also can save the changes by close act normally don't care message box at least for me). In the plugin settings there is a setting called "game language"(My plugin use the chinese and I'm not sure the name in english called this, but it means this) and anothor is "language of plugin"(also). I change the "game language" from zh-cn to ja-jp and the error fixed. The plugin I download have a lot of languages I test some of them and some may cause this error some won't. I'm not sure wheather this setting is not same as the one in the real game will cause what problem. For me it still work as normal if you can't I have no ideas and you may try to out put the log of the plugin and find out the prpblem.

**Comment by Krojack** [comment]
No luck for me.  I tried changing the FFXIV plugin to JP and also the language in the SpecialSpellTimer plugin as well and nothing, still get the error.  I had all of them set to JP and still got the error and crashed ACT.  I even tried going to the previous version of ACT (v3.4.4) and still no luck.

I did some searching and from other programs with a similar error, it seems to have happened after a Windows update that modified the .NET files.  Well mine did one the other day and I'm wondering if that is what happened.

**Comment by TamaZooo** [comment]
多分セットアップミスに起因するエラーだと思いますが、次のログファイルを貰えませんか？
（Googleドライブなどにアップロードしてそのリンクを教えてください。）

```%APPDATA%\Advanced Combat Tracker\Advanced Combat Tracker.log
%APPDATA%\anoyetta\ACT\logs\ACT.Hojoring.YYYY-MM-DD.log```

**Comment by Krojack** [comment]
Log Files: https://drive.google.com/open?id=1kL4xEzDA4rOVGZPhLEZhO0XrS82yIWf_

**Comment by TamaZooo** [comment]
confirm. Is Advanced Combat Tracker set up to `N: \ ACTv3`?

**Comment by Krojack** [comment]
Yup, I've had ACT on my N: drive pretty much every since I started using it several years ago.

**Comment by TamaZooo** [comment]
#265 で設定ファイルを初期化したら問題なく起動できたらしいので、一度設定ファイルを待避してみて下さい。

①:`%APPDATA%\Advanced Combat Tracker` を待避＆削除
②:ACTを起動 → プラグインのロード
③:この状態で、同じエラーが発生し無ければ終了
④:ACTを終了させる
⑤:`%APPDATA%\anoyetta` を待避＆削除 
⑥:この状態で、同じエラーが発生し無ければ終了
⑦:ACTを終了させる
⑧:①と⑤を実施して、②、③を実施
⑨:ロードできると信じたい

**Comment by Krojack** [comment]
Completely fresh ACT install. Only the FFXIV parse plugin and SpecialSpellTimers.  Same crash message for me.

**Comment by hyskylord** [comment]
This happened to me once, and it turns out that you need to change the language settings both for UltraScouter.dll and SPESPE.dll. I cannot load SPESPE before changing the settings of UltraScouter, oops.

**Comment by Krojack** [comment]
So you load up the ACT.UltraScouter.dll file then change the language to what? 

I'll delete all saved configs for the plugin (the entire anoyetta folder) then the second I activate the plugin ACT.UltraScouter.dll I get that crash message.  ACT works fine if I just move the error message off to the side, this plugin however won't. I've tried changing the ACT.UltraScouter.dll language to JP and still crashes.  I've all but given up and tried everything I can think of other than a full OS reinstall which I'm not going to do.  I might try on my laptop the next time I have it out if I can remember to.

**Comment by Krojack** [comment]
Just tested with the latest version and the ACT.SpecialSpellTimer.dll is still completely crashing ACT.  ACT.UltraScouter.dll also crashes with the same error however ACT.TTSYukkuri.dll seems to work just fine.

---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.AggregateException - One or more errors occurred.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at FFXIV.Framework.XIVHelper.XIVApi.Load()

   at FFXIV.Framework.XIVHelper.XIVPluginHelper.<>c__DisplayClass48_0.<Start>b__2()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at FFXIV.Framework.XIVHelper.XIVPluginHelper.<Start>d__48.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

System.Threading.Tasks.Task, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
---------------------------
OK   
---------------------------
