### ISSUE TITLE
エラーがでますがどうすればいいですか

### ISSUE THREAD

**Issue by izayoikaito** [anoyetta/ACT.Hojoring#265]
いつもお世話になっております。アップデート後に下記エラーが発生しております。
お手数ですが、解決方法をご教示いただければ幸甚です。

**現象の詳細**  
Act起動後、「Fatal Error - Unhandled Exception」ok押しの後、Actが閉じました

**再現方法**  
現象の再現方法を記載します。

**環境**
- Hojoring v7.9.4
- FFXIV_ACT_Pluginのバージョン: v3.4.5.265
- OS: Windows 10

**追加のコメント**  
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.AggregateException - 1 つ以上のエラーが発生しました。
   場所 System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)

   場所 FFXIV.Framework.XIVHelper.XIVApi.Load()

   場所 FFXIV.Framework.XIVHelper.XIVPluginHelper.<>c__DisplayClass45_0.<Start>b__2()

   場所 System.Threading.Tasks.Task.Execute()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   場所 FFXIV.Framework.XIVHelper.XIVPluginHelper.<Start>d__45.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   場所 System.Threading.ThreadPoolWorkQueue.Dispatch()

System.Threading.Tasks.Task, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
---------------------------
OK   
---------------------------

**Comment by TamaZooo** [comment]
セットアップミスが濃厚と思われるので、一度anoyettaのブログに従って再セットアップしてみて下さい。
なお、FFXIV_ACT_PLUGINについてはブログ通りではなく、以下ディレクトリに格納して下さい。
　`[ACT Dir]\plugin\FFXIV_ACT_Plugin`

セットアップ手順
https://www.anoyetta.com/entry/hojoring-setup

**Comment by Krojack** [comment]
This is the same problem I'm having over on the post https://github.com/anoyetta/ACT.Hojoring/issues/264

**Comment by izayoikaito** [comment]
返事ありがとうございます。一度anoyettaのブログに従って再セットアップしましたが同じのエラーがでました

FFXIV_ACT_Pluginののバージョンは 2.0.4.4 です

**Comment by izayoikaito** [comment]
さっき%APPDATA%にAdvanced Combat Trackerとanoyettaを削除したら　もう大丈夫みたいです
