### ISSUE TITLE
SharlayanHelper module in FFXIV.Framework request server data every 5s lead to wrong version data structure

### ISSUE THREAD

**Issue by hbq0449** [anoyetta/ACT.Hojoring#266]
``` c#

                    MemoryHandler.Instance.SetProcess(
                        model,
                        gameLanguage: ffxivLanguage,
                        useLocalCache: false);

```
around 173 line in SharlayanHelper the useLocalCache is fixed to false. cause MemoryHandler to request https data every 5s. cause banwidth lose. Make local data structure unusable, As Chinese server is not the latest version...

suggest change is to true. if the file not exist, MemoryHandler will download the data files.

**Comment by TamaZooo** [comment]
anoyettaが管理するHojoringはFFXIV Patch 5.11 にのみ対応しており、中国および韓国サーバのFFXIVにはサポートできません。
理由は、anoyettaが中国および韓国サーバでPlayできないので、十分なデバッグをする事ができません。

これは、FAQにも書いてあります。
https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ

**Comment by anoyetta** [comment]
fixed it.
