### ISSUE TITLE
Hojoringを入れるとACTのタブの表記がおかしくなる

### ISSUE THREAD

**Issue by Sachimitama** [anoyetta/ACT.Hojoring#269]
どのDLLのプラグインを追加してもACT上のタブが異常に小さくなったりフォントが大きくなったりして読め無くなりほかのプラグインが運なく使えなくなります。Hojoringの最新版やACTの最新版やFFXIV_ACT_Pluginの最新版を使っても同様です。ACTでフォントの大きさなど変えられますがこれをするとさらに状況が悪化してよけ読めなくなります。

**Comment by TamaZooo** [comment]
こちらを参照してください。

https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Hojoring%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%97%E3%81%9F%E3%82%89%E4%B8%80%E9%83%A8ACT%E3%81%AEUI%E3%81%8C%E5%A4%A7%E3%81%8D%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E6%8F%8F%E7%94%BB%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%8B

**Comment by TamaZooo** [comment]
誤クリックでCloseしてしまったので再オープン

**Comment by Sachimitama** [comment]
> 
> 
> こちらを参照してください。
> 
> Hojoringを導入したら一部ACTのUIが大きく表示され描画が崩れる
> https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Hojoring%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%97%E3%81%9F%E3%82%89%E4%B8%80%E9%83%A8ACT%E3%81%AEUI%E3%81%8C%E5%A4%A7%E3%81%8D%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E6%8F%8F%E7%94%BB%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%

> 
> 
> こちらを参照してください。
> 
> Hojoringを導入したら一部ACTのUIが大きく表示され描画が崩れる
> https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Hojoring%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%97%E3%81%9F%E3%82%89%E4%B8%80%E9%83%A8ACT%E3%81%AEUI%E3%81%8C%E5%A4%A7%E3%81%8D%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E6%8F%8F%E7%94%BB%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%8B

ありがとうございます。直りましたがこれによって今度はActwebsocketの表記のみが崩れてしまいました。これは ZCubeさんに相談するしかないですかね。何かどうしようもないような気もしますが・・・

**Comment by TamaZooo** [comment]
この事象が発生する原因が、[設定]→[システム]→[ディスプレイ]→[拡大縮小とレイアウト]→[テキスト、アプリ、その他の項目のサイズを変更する]の項目が100%になっていないから起こりえるんですが、４K環境やノートPC環境だと150％や200％にしたくなりますから何とも言えないですね。。。

ご認識の通りActwebsocketは製作者側にお願いします。

**Comment by anoyetta** [comment]
ActWebSocketは文字通りWebSocketとのI/Fを提供しているだけで描画には関係ないと思います。扱っているレイヤーが遠すぎる。
またゲームだと高DPIスケーリングは使用しないのが一般的かと思います。レガシーアプリと新しいメトロ系アプリでのギャップ、ゲーム及びDirectX系アプリとのギャップとなにかと問題が生じます。仮に高DPIスケーリングを使用するとしてもそれらを扱える知識を持った上で自己責任でやることかと思います。

**Comment by Sachimitama** [comment]
高DPIスケ`リングは出来るだけ使用しないようにします。ありがとうございました。

Windows 10 版のメ`ル<https://go.microsoft.com/fwlink/?LinkId=550986>から送信

差出人: anoyetta<mailto:notifications@github.com>
送信日r: 2019年12月1日 14:59
宛先: anoyetta/ACT.Hojoring<mailto:ACT.Hojoring@noreply.github.com>
CC: Sachimitama<mailto:sachimitama.ichireishikon@outlook.jp>; Author<mailto:author@noreply.github.com>
件名: Re: [anoyetta/ACT.Hojoring] Hojoringを入れるとACTのタブの表がおかしくなる (#269)


ActWebSocketは文字通りWebSocketとのI/Fを提供しているだけで描画にはvSないと思います。Qっているレイヤ`がhすぎる。
またゲ`ムだと高DPIスケ`リングは使用しないのが一般的かと思います。レガシ`アプリと新しいメトロ系アプリでのギャップ、ゲ`ム及びDirectX系アプリとのギャップとなにかと}が生じます。烁DPIスケ`リングを使用するとしてもそれらをQえる知Rを持った上で自己任でやることかと思います。

―
