### ISSUE TITLE
Outdated Discord Library Breaks TTSYukkuri

### ISSUE THREAD

**Issue by KhloeLeclair** [anoyetta/ACT.Hojoring#270]
**Describe the bug**
TTSYukkuri fails to initialize correctly if another plugin loaded before it has a different version of the Discord library. It displays and logs an error message during initialization, and the settings UI appears functional, but it does not generate or play audio.

**To Reproduce**
1. Install another plugin that uses a different version of the Discord library, such as https://github.com/easly1989/ffxiv_act_dfassist
2. Ensure that the other plugin is loaded before TTSYukkuri.
3. Restart ACT.
4. See error.

**Screenshots**
![ACT TTSYukkuri_2019-12-02_22-44-21](https://user-images.githubusercontent.com/41554123/70019599-c9312280-1557-11ea-9810-c46a63d96854.png)

**Environment**
- ACT.Hojoring Version: Tried on both v7.10.2 and v7.8.17
- FFXIV_ACT_Plugin Version: 2.0.4.5
- OverlayPlugin: v0.11.2.0
- DFAssist: v2.2.11
 - OS: Windows 10 build 18363

**Additional Context**
Hojoring Log: https://gist.github.com/KhloeLeclair/29d9a5d127afebbf77415a175b24aa0e
ACT Log: https://gist.github.com/KhloeLeclair/8ac36b3ec139e5ba6eb148182eee3f6c
DFAssist Issue: https://github.com/easly1989/ffxiv_act_dfassist/issues/56

While updating TTSYukkuri to the latest version of the Discord library would be preferable, all I want is TTSYukkuri to continue functioning even if the Discord features cannot be initialized. I don't personally use them, and it is inconvenient to load TTSYukkuri before other plugins using Discord that I *do* want to use.

Thank you for your work.

**Comment by Tsunayoshi** [comment]
ACT.Hojoring Version: 7.12.4.7
    FFXIV_ACT_Plugin Version: 2.0.4.13
    OverlayPlugin: v0.13.2.0 (!! 13 had special changes caution!)
    DFAssist: v2.2.13.0 (use the one from act website no forks!)
    OS: Windows 10 build 18363.592

I did a clean install yesterday and everything is working fine BESIDE Yukkuri wont connect to a Discord (while discord triggers working)

Also using:
cactbot 0.15.1.0
triggernometrie 1.1.3.0
act_discrodtriggers 1.0.0.0

**Comment by anoyetta** [comment]
fixed https://github.com/anoyetta/ACT.Hojoring/releases/tag/v7.13.7-200123.1345
