### ISSUE TITLE
スペスペエラー

### ISSUE THREAD

**Issue by Hiroyu-h** [anoyetta/ACT.Hojoring#271]
**現象の詳細**  
https://github.com/anoyetta/ACT.Hojoring/issues/261
上記URLの事象と酷似しております。
ブルースクリーン強制再起動後、ACTのSpecialSpellTimerのプラグイン読み込み時にエラーを吐くようになりました。

**再現方法**  
起動時（SpecialSpellTimer読み込み時）

**環境**
FFXIV_ACT_Plugin v2.0.4.5
ACT.Hojoring v7.8.17
ACT.SpecialSpellTimer v2.12.0
ACT.UltraScouter v1.9.2
ACT.TTSYukkuri v4.3.0
Windows 10

**追加のコメント**  
#261 のご回答にあります対処法を試しましたが解決しませんでした。
お忙しいところ恐れ入りますが解決法をご教示いただけますと幸いです。

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
    * 現象のスクリーンショットを添付してください
[ACT.Hojoring.HelpMe.2019-12-03.zip](https://github.com/anoyetta/ACT.Hojoring/files/3916488/ACT.Hojoring.HelpMe.2019-12-03.zip)
![plugin_init_error](https://user-images.githubusercontent.com/32827146/70050466-5c2e9300-1612-11ea-977a-87f85d8253fe.png)

**Comment by TamaZooo** [comment]
こちらのFAQを参照して下さい。
https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Plugin-init-error%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%82%8B

**Comment by Hiroyu-h** [comment]
複数のxmlファイルおよびconfigファイルの破損が確認できました。
configファイルを戻せないため時間があるときに再インストールをします。
ご回答ありがとうございました。
