### ISSUE TITLE
オブジェクト参照がオブジェクト インスタンスに設定されていません。

### ISSUE THREAD

**Issue by Crescr** [anoyetta/ACT.Hojoring#273]
以下のエラーが頻繁にログに記録されます。
ACT起動時は即記録される時もあればされない時も。
補助輪はウルスカとゆっくりのプラグインのみ使用。
各プラグインは全て正常動作しており、支障は全くないのですがあまりにも出るため報告しておきます。

ACT.Hojoring Version: Tried on both v7.11.3
FFXIV_ACT_Plugin Version: 2.0.4.6
Qitana OverlayPlugin: v0.11.5.0
Qitana DFAPlugin: v2.2.0.0
OS: Windows 10 build 18363.476

以下現象のエラーログ
[Error] ThreadWorker - scanFFXIVWorker error. System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 FFXIV.Framework.XIVHelper.XIVPluginHelper.RaiseZoneChanged(UInt32 zoneID, String zoneName)
   場所 FFXIV.Framework.XIVHelper.XIVPluginHelper.DetectConditionChanges(IEnumerable`1 party)
   場所 FFXIV.Framework.XIVHelper.XIVPluginHelper.RefreshCombatantList()
   場所 FFXIV.Framework.XIVHelper.XIVPluginHelper.<>c__DisplayClass45_0.<Start>b__1()
   場所 FFXIV.Framework.Common.ThreadWorker.DoWorkLoop()

**Comment by satsuya0114** [comment]
+1
