### ISSUE TITLE
It shows me horojoring is not allowed for you

### ISSUE THREAD

**Issue by dybq** [anoyetta/ACT.Hojoring#276]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Environment**
- ACT.Hojoring Version:
- FFXIV_ACT_Plugin Version: 
 - OS: 

**Additional context**

**Comment by danyubaoqi** [comment]
FFXIV_ACT_Plugin v2.0.4.0
ACT.Hojoring v7.8.11
