### ISSUE TITLE
TTSYukkuriのプラグインエラー

### ISSUE THREAD

**Issue by primavera0407** [anoyetta/ACT.Hojoring#280]
**現象の詳細**  
TTSYukkuriをプラグインしようとしたら、エラーが出て困っています

**再現方法**  
System.MissingMethodException

メソッドが見つかりません: 'System.Threading.Tasks.Task`1<Discord.ITextChannel> Discord.IGuild.CreateTextChannelAsync(System.String, Discord.RequestOptions)'
   場所 ACT.TTSYukkuri.Discord.Models.DiscordNetModel..ctor()
   場所 ACT.TTSYukkuri.Discord.Models.DiscordNetModel.get_Instance()
   場所 ACT.TTSYukkuri.PluginCore.<>c.<InitPlugin>b__30_4()
   場所 System.Threading.Tasks.Task.Execute()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 ACT.TTSYukkuri.PluginCore.<>c__DisplayClass30_0.<<InitPlugin>b__0>d.MoveNext()

**環境**
- 補助輪のバージョン: ACT.Hojoring-v7.13.6
- FFXIV_ACT_Pluginのバージョン: FFXIV_ACT_Plugin_2.0.4.13
- OS: Windows 10

**追加のコメント**  
お忙しいところ恐れ入りますが、対処方法を教えていただけると幸いです。
よろしくお願いいたします。

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
    * 現象のスクリーンショットを添付してください

**Comment by anoyetta** [comment]
> ACT.Hojoring, ACT本体のログを添付してください
このとおりです。
