### ISSUE TITLE
SpespeTimeでのシミュレーションについて

### ISSUE THREAD

**Issue by LuiceCreek** [anoyetta/ACT.Hojoring#281]
要望になります。
SpespeTimeで過去ログを使用してシミュレーションする際に、
PTメンバーの名称、およびジョブを設定出来るようにした上で実行したい。
(Triggersのシミュレータの **テスト条件** に相当する機能です。)

**Comment by wbonbon** [comment]
ParsedLogでシミュレーションする機能を以前追加したので、
それを使うと本来やりたかったことが出来ると思います
