### ISSUE TITLE
UltraScouter

### ISSUE THREAD

**Issue by Kaiay** [anoyetta/ACT.Hojoring#285]
ごめんなさい　Pull requestsの使い方がわかりませんのでここで書きます
UltraScouterもSpecialSpellTimerのように「非アクティブのときオーバーレイを隠す」のオプション追加できますか？

**Comment by anoyetta** [comment]
出来ると思いますよ。基本的にリジェクトしませんのでなんでも送ってください。
多少バグっていてもこちらので直しますので気軽にPull Requestしてください。
