### ISSUE TITLE
最新の補助輪にアップデート後からスペスペタイムラインの音声が出ない

### ISSUE THREAD

**Issue by shacoop** [anoyetta/ACT.Hojoring#286]
最新の補助輪にアップデート後からスペスペタイムラインの音声が出なくなってしまいました。
TTSゆっくりをEnabledすると音声も出力されるのですが、ACT本体のTTSの音声を使うことは出来ませんでしょうか？
よろしくお願いいたします。

**Comment by TamaZooo** [comment]
正しくセットアップ出来ていないのが原因だと思います。
一度あのさんのブログ通りセットアップしてみてください。

TTSYukkuriを使わない場合は以下の設定を弄ってみて下さい。
![image](https://user-images.githubusercontent.com/43776206/79334302-02908a80-7f5b-11ea-82c6-a21fb6d47428.png)
