### ISSUE TITLE
SPESPEでタイムラインの挙動がおかしい

### ISSUE THREAD

**Issue by sector0718** [anoyetta/ACT.Hojoring#288]
**現象の詳細**  

共鳴編零式でのタイムラインで以前のバージョン（v7.15.3以前）ではボスの挙動やギミック、範囲攻撃などのアナウンスがありましたが、最新のHojoringにアップデートするとそれらがアナウンスされなくなります。
でも一部ですがログを拾ってアナウンスされるいるものもあります。
実際にタイムラインの入れ直しやACT、Hojoring全てをインストールし直したりもしましたが変わりませんでした。
使用しているタイムラインはhttps://blog.sheeva.me/entry/e8s-timeline に置いてあるものになります、1～4全層で確認済みです。

Yukkuriなどはエラーは出ておらず、音声も正常に出ております。

**再現方法**  
現象の再現方法を記載します。

**環境**
- 補助輪のバージョン: [不具合が出たのがv7.15.4～8] 現在はv7.15.2を使用中

- FFXIV_ACT_Pluginのバージョン: 最新

**追加のコメント**  
なにか追加するコメントがあれば記載します。

* 注意  
    * ACT.Hojoring, ACT本体のログを添付してください
    * 現象のスクリーンショットを添付してください

**Comment by TamaZooo** [comment]
サブデバイス等で再生させていませんか？

こちらを読んで下さい。

[v7.15.5](https://github.com/anoyetta/ACT.Hojoring/releases/tag/v7.15.5-200328.0130)

**Comment by sector0718** [comment]
ご連絡ありがとうございます、Hojoringでいつもお世話になっております、指摘された箇所も確認済でございます。
実際拾っているログも少しだけあるみたいで、その場合はYukkuriで音声通知もされております。
4層に関しては例えば側面から背面へなどの表示がある閑寂（静寂）の双剣技、
後半の聖竜の咆哮で何番目に解呪などの表示がこのタイムラインではあるのですが、それも表示されなくなっている状況です。

2020年4月15日(水) 20:05 Velaciela <notifications@github.com>:

**Comment by TamaZooo** [comment]
それではサポート情報を下さい。
(ログファイル)

**Comment by sector0718** [comment]
https://13.gigafile.nu/0422-b608fc1386177a1746e332644db62d7ac

こちらでよろしいでしょうか？
もし追加で何か必要なものがあれば送りますのでよろしくお願いいたします。
Gmailでの送信容量が超えておりますのでギガファイル便のアドレスを付属致します、こちらからダウンロードしていただければ幸いです。

2020年4月15日(水) 21:16 I/O LABO <firmware.downgrade@gmail.com>:

**Comment by TamaZooo** [comment]
既に更新されなくなった古いOverlayPluginを使っていたり、あのさん推奨のセットアップ方法出なかったりと、原因を探そうにも砂漠で米粒を探すような状態なので、一度以下を試して下さい。

他の方も古いOverlayPluginを使っていたりで不具合が多数発生しています。

①ACTを終了する。
②`%appdata%\Advanced Combat Traqcker` フォルダを任意のフォルダに移動。(コピーでは無く移動
③`%appdata%\anoyetta` フォルダを任意のフォルダに移動。(コピーでは無く移動
④あのさんの[ブログ](https://www.anoyetta.com/entry/hojoring-setup)通りセットアップ
⑤新しくセットアップしたACTを使って色々再設定。(このときめんどくさいけどバックアップは使わない方が良い
⑥この状態で同じ事象になるかチェック。
