### ISSUE TITLE
Plugin Init Error

### ISSUE THREAD

**Issue by ghost** [anoyetta/ACT.Hojoring#289]
Happens when attempting to enable the special spell timer plugin. The FAQ says that this is cause of corrupted files but this is happening on a clean install. I've also read through the file it tells you to check and there's nothing wrong with the file. Multiple re-downloads and re-installs proves that this is not an issue with corrupted files.

[Plugin Init Error](https://user-images.githubusercontent.com/55117631/80073628-63d3e180-858b-11ea-91a0-f87762aafda8.png)

**Environment**
- ACT.Hojoring Version: v7.15.10
- FFXIV_ACT_Plugin Version: v2.0.5.10
 - OS: Windows 10 Home

**Comment by TamaZooo** [comment]
https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#systeminvalidoperationexception

**Comment by TamaZooo** [comment]
サポートファイルを下さい。

**Comment by angelicrequiem** [comment]
i have the same error. Been using it just fine up until this update.

**Comment by SlaynDragadaleFFXIV** [comment]
Start getting this same error yesterday. Worked fine the day before.

**Comment by CalionSilus** [comment]
System.InvalidOperationException

XML 문서(0, 0)에 오류가 있습니다.
   위치: System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   위치: System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   위치: ACT.SpecialSpellTimer.Models.TagTable.Load()
   위치: ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass26_0.<<InitPluginCore>b__0>d.MoveNext()

Inner Exception :
System.Xml.XmlException

루트 요소가 없습니다.
   위치: System.Xml.XmlTextReaderImpl.Throw(Exception e)
   위치: System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   위치: System.Xml.XmlReader.MoveToContent()
   위치: Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTagTable.Read7_TagTable()

**Comment by miomoru** [comment]
The same thing happened to me after my pc crashed, I uninstalled ACT and all plugins and re-downloaded and reinstalled it all and the problem still persisted. What ended up fixing the issue for me was to go to _username_ /AppData/Roaming and deleting the anoyetta folder there.

**Comment by dlevine3** [comment]
Has anyone found a solution to this yet?  After patch 5.4 i got plugin init error.

ACT.SpecialSpellTimer
Plugin init error !
System.InvalidOperationException

There is an error in XML document (0, 0).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at ACT.SpecialSpellTimer.Models.TagTable.Load()
   at ACT.SpecialSpellTimer.PluginCore.<>c__DisplayClass26_0.<<InitPluginCore>b__0>d.MoveNext()

Inner Exception :
System.Xml.XmlException

Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTagTable.Read7_TagTable()
