### ISSUE TITLE
Player IDs appearing in ${target} and ${victim}

### ISSUE THREAD

**Issue by geekgirl101** [anoyetta/ACT.Hojoring#300]
I'm seeing player IDs appearing in front of names when using them in the spell name.  For example: Raise >> ${target} is displaying Raise >> 1A:1A2B3C4D:Jane Doe when I or someone else casts a raise spell on them.  Up until recently this was only happening with ${victim} but today it's now also happening with ${target}

**Comment by njtwiseman** [comment]
Confirmed

**Comment by wbonbon** [comment]
Maybe it's because your matching words are vague.
Please modify it by referring to the following example
before:
(?&#60;victim>.+?) gains effect ～
after:
**1A:&#60;id8>:**(?&#60;victim>.+?) gains effect ～
