### ISSUE TITLE
Feature Request - Stack Counting

### ISSUE THREAD

**Issue by Sythalin** [anoyetta/ACT.Hojoring#303]
There are a lot of abilities that stack, would be nice if we could use SPESPE to display the counts.

For example, using SMN's *Further Ruin* (since this is the most common I waste casts on):

### General Tab
**Keyword to show**
mex gains the effect of Further Ruin
**Use Regex**: True (boolean)
**Stack On Cast?**: True (boolean)
**Number of Stacks to Add**: 1 (int)
**Max Stacks**: 4 (int)

**Keyword to extend**
mex loses the effect of Further Ruin
**Remove stack?**: True (boolean) 
**Number of Stacks to Remove**: 1 (int)

### Visual Tab (Misc)
**Show Stack Count**: True (boolean)

**Comment by wbonbon** [comment]
First, remove the 0x26 ignore in the Log Filter in Options.
Then create a trigger like this
This will display a spell timer that behaves like your request.
Not satisfied with this?

General tab
**Spell name**
${_count}
**Keyword to show**
(^26:<id8>:<mex>:.*:0:0:0:.*(?<_count>[0-9]{2})04BC|^00:<id4>:<mex>loses the effect of Further Ruin)
**Recast time**
9998.00sec
**Keyword to extend**
^00:<id4>:<mex>loses the effect of Further Ruin -9999.00

Visual tab
Progress bar
**☑Circle Style**
W0 H0

**Comment by Sythalin** [comment]
This actually help out quite a bit.  Although your example took a little editing, (for example, _count quantifier needed to be 1 instead of 2), I got it working.  I also trimmed it down a bit.  The final result (for anyone curious or looking to do this for SMN):

**Spell Name**
${_count}
**Keyword to show**
<mex>:.*:0:0:0:.*(?<_count>[0-9]{1})04BC
**Recast time**
9998.00
**Keyword to extend**
<mex> loses the effect of Further Ruin -9999.00

The example was helpful, but the real thing that you helped with is letting me know WHERE to find stack counts in the log (which of course were hidden).  I spent 2 hour digging through the default log trying to find that info to make this.  Maybe now I can also get my BLM Enochian watcher working (since default doesn't display it either).

Thanks!

**Comment by chimera74** [comment]
How do I go about showing charges or showing proper cooldowns for the stackable abilities like Plunge or Intervene?

**Comment by Sythalin** [comment]
> 
> 
> How do I go about showing charges or showing proper cooldowns for the stackable abilities like Plunge or Intervene?

I've been playing around with stackable auto-refreshing abilities and haven't found an "easy" way to do it as of yet.  Without having a reliable way to figure out spell and effect ids (such as 04BC = Further Ruin above), it would require hours of start-cast-stop combat with dummies for every single spell/ability/effect, don't think I'll ever find it.  Maybe someone who is already familiar with all the definitions of the log numbers can pitch in on that.
