### ISSUE TITLE
Also getting Init Error

### ISSUE THREAD

**Issue by MeekaTe** [anoyetta/ACT.Hojoring#305]
**Describe the bug**

**To Reproduce**
1. down the latest version
2. try to add the .dll file in ACT as usual
3. See error

**Environment**
- ACT.Hojoring Version: latest
- FFXIV_ACT_Plugin Version: latest 
 - OS: windows latest version

**Additional context**
Maybe its because ACT needs updating? I don't know. This sucks
![hojoring](https://user-images.githubusercontent.com/69590013/90025482-6bdc9c00-dcb6-11ea-9e8f-2dc9f10a70ad.JPG)

**Comment by karlongkar** [comment]
i deleted this folder and it works.

C:\Users\xxxxx\AppData\Roaming\anoyetta\ACT

**Comment by aklein13** [comment]
In my case I removed line `<Filter Key="NetworkTargetMarker" Value="false" />` from C:\Users\xxxxx\AppData\Roaming\anoyetta\ACT\FFXIV.Framework.config and it works
