### ISSUE TITLE
actorの導入について

### ISSUE THREAD

**Issue by taneememe** [anoyetta/ACT.Hojoring#31]
DPSの測定ができません
知識不足でなんどか入れなおしたりしているのですがうまく起動しないので導入方法をよりくわしく教えていただけませんか？

**Comment by anoyetta** [comment]
Actorそのものは私のプロダクトではないのでお答えできません。
ACT本体についても同様です。

しかし、セットアップを代行してあげるのは出来ます。
TeamViewer でインストールしてIDとパスワードを教えてください。
あとリアルタイムな連絡手段が必要ですのでDISCORDのほうで改めてコンタクトしてください。
