### ISSUE TITLE
Oops！と表示され利用出来ない件

### ISSUE THREAD

**Issue by YOCHi23** [anoyetta/ACT.Hojoring#314]
![image](https://user-images.githubusercontent.com/76613140/103149262-3d65e600-47ab-11eb-9852-30842e57a827.png)
![image](https://user-images.githubusercontent.com/76613140/103149271-5078b600-47ab-11eb-8fbe-e3462ac3712c.png)
![image](https://user-images.githubusercontent.com/76613140/103149303-946bbb00-47ab-11eb-9e6b-5dc5cff9b570.png)

以前は普通に利用出来ていたが、ある日を境にbin folder NotFound（1枚目と2枚目参照）と出て利用できなくなった。
ACTでプラグインを設定し起動してみるとエラー画面となり何も出来ない。（3枚目参照）
Hojoringに含まれるスペスペ、ユックリ等全て利用できない。
問題発生後、下記は試してみましたが変化はありませんでした。

・framework等の最新確認
　→ 既にPCにDLされているが、念の為サイトからDLを試みた結果、既にDL済みとなっている
・ACT／Hojoringともにアンインストール→インストールのし直し
　→ 全てやり直したが、変化なし
・HojoringのAppData配下を削除し再度インストールしなおし
　→ 変化なし

**Comment by TamaZooo** [comment]
Windowsのバージョン情報と、サポート情報を下さい。

**Comment by TamaZooo** [comment]
ログの収集方法 プランB -ACTもしくはプラグインが起動できない場合- 

  1. エクスプローラを開く
  2. アドレスバーに %APPDATA% と入力する
  3. エクスプローラで表示された下記の2つのフォルダを圧縮する
    Advanced Combat Tracker
    anoyetta
  4. 圧縮したログ（zip）を Google Drive にアップロードする
  5. アップロードしたファイルのリンクを回答者に伝える

**Comment by YOCHi23** [comment]
![image](https://user-images.githubusercontent.com/76613140/103150263-c41fc080-47b5-11eb-93d5-1735d48769c8.png)
Windowsのバージョン情報はこちらです。
サポート情報についてですが、無知で申し訳ございませんが確認方法をご教示ください。

下記にアップロードさせて頂きました。
Hojoring設定については一度全て削除してしまった為、中身がありません。
https://drive.google.com/drive/folders/1r0kghPTwXTiFvz7QwFaA-l_OGpab-pSu?usp=sharing

**Comment by TamaZooo** [comment]
もう一度、あのさんのブログ通りセットアップし直してみて下さい。
https://www.anoyetta.com/entry/hojoring-setup

再セットアップするときに、以下フォルダを元のフォルダ名に `_old` をつけてリネームしておいて下さい。
`%appdata%\Advanced Combat Tracker`
`%appdata%\anoyetta`
