### ISSUE TITLE
UI doesn't respect UI scaling

### ISSUE THREAD

**Issue by Unspec7** [anoyetta/ACT.Hojoring#318]
When Hojoring is installed and user has UI scaling enabled within Windows (150%, in my case), Hojoring reverts ACT to the default scale (100%). This is a problem on 4k monitors, as it makes text in buttons squished and overlays near unreadable. Problem goes away once Hojoring is uninstalled.

Hojoring:
<img width="667" alt="UI" src="https://user-images.githubusercontent.com/11931584/106964483-2b635580-6710-11eb-9f1f-870dc9fa3430.png">

No Hojoring:
<img width="1020" alt="UI" src="https://user-images.githubusercontent.com/11931584/106964680-78472c00-6710-11eb-8843-ec8afb9ad57a.png">

**Environment**
- ACT.Hojoring Version: 8.1.7
- FFXIV_ACT_Plugin Version: 2.0.8.0
 - OS: Windows 10

**Comment by wbonbon** [comment]
[https://blogs.windows.com/windows-insider/2017/01/09/announcing-windows-10-insider-preview-build-15002-pc/#B4p617eIRYORoHM1.97](url)

"Improved high-DPI support for desktop apps"
refer to this
