### ISSUE TITLE
Fatal error bug when closing ACT

### ISSUE THREAD

**Issue by Nellieh** [anoyetta/ACT.Hojoring#319]
![yJiYBkf](https://user-images.githubusercontent.com/39604109/107736152-a70d6580-6d01-11eb-96d4-b4ef87b9333c.png)
**Describe the bug**
I get this fatal error every time i close ACT with Yukkuri plugin enabled

**To Reproduce**
1. Have Yukkuri enabled.
2. Close ACT .
3. Doesn't happen if Yukkuri is disabled in plugin list.

**Environment**
- ACT.Hojoring Version: 5.0.0.0
- FFXIV_ACT_Plugin Version: 2.0.8.0
 - OS: Windows 10 Pro 20H2

**Comment by msoltyspl** [comment]
Can confirm this - same exact message. Disabling Hojoring makes ACT exit cleanly.

**Comment by Krojack** [comment]
I still get this same error 2 years later when trying this plugin again only I get it when the plugin loads.

Posted here: https://github.com/anoyetta/ACT.Hojoring/issues/338
