### ISSUE TITLE
SPESPE Triggers only show after making ACT active window

### ISSUE THREAD

**Issue by jackrush257** [anoyetta/ACT.Hojoring#320]
When using SPESPE, if I change jobs, my trigger icons will only appear on screen after alt-tabbing to ACT and alt-tabbing back.

**Comment by jackrush257** [comment]
Update. The triggers are still loading but are for some reason loading behind the ffxiv application window.

**Comment by natyusha** [comment]
This has been an issue for quite some time. Maybe ask someone who can speak Japanese to talk to the developer about it.
