### ISSUE TITLE
SPESPE. Thick stroke around circular progress bars

### ISSUE THREAD

**Issue by chimera74** [anoyetta/ACT.Hojoring#325]
**Describe the bug**
There is a thick stroke around circular progress bars for spells. It can not be made transparent. I don't know what happened. It broke on 27th April 2021. On screenshot 1 it is how it was before..

**To Reproduce**
1. Create a Spell
2. Check screenshot 3 for Visual settings and set the important ones to make bars circular.
2. Go to Stroke color for Progress bar.
3. Try to enter "# 00000000" (black transparent) as a color.
4. Confirm.
5. See Thick black bar around the progress bar.
6. Go back to Stroke color for Progress bar.
7. See that it is reverted to "#FF000000" (full opaque black).

**Screenshots**
1. https://prnt.sc/125yzdp How it was before
2. https://prnt.sc/125r26g How it is now
3. https://prnt.sc/125r4mp Visual settings

**Environment**
- ACT.Hojoring Version: FFXIV_ACT_Plugin v2.0.9.0
- FFXIV_ACT_Plugin Version: v9.0.3
- ACT.SpecialSpellTimer v2.12.0
 - OS: Win 10

**Comment by chimera74** [comment]
This is decimal separator problem for handling Progress Bard Stroke Thickness. If I use point (.) as a decimal separator in my system everything is ok.
これは、プログレスバードストロークの厚さを処理するための小数点の問題です。 システムで小数点記号としてポイント（。）を使用すれば、すべて問題ありません。

**Comment by wbonbon** [comment]
現時点ではシステムロケールに関する事象は仕様となります
