### ISSUE TITLE
UltraScouter enemy list does not support enemies with the same name

### ISSUE THREAD

**Issue by fly1n** [anoyetta/ACT.Hojoring#328]
**Describe the bug**
HP display of UltraScouter -> Mob -> Enemy List does not support enemies with the same name, only one enemy is displayed.

**To Reproduce**
Try attacking 2 striking dummies, only one gets displayed in UltraScouter.

**Comment by wbonbon** [comment]
Enemy List is a function for specific content and does not support such usage.
