### ISSUE TITLE
壊れた設定ファイルとバックアップ

### ISSUE THREAD

**Issue by eai04191** [anoyetta/ACT.Hojoring#33]
不具合報告というか機能拡張というか微妙な感じの相談です。

プレイ中気がついたらSpeSpeのテロップの読み上げが聞こえなかったので設定を見てみると見事に何もなくなっていました。

設定ファイルが破損したのだろうと予想し、覗いてみると完全に壊れているようでした。

![image](https://user-images.githubusercontent.com/3516343/35281988-b722d196-0097-11e8-9b7b-84ed7edf310b.png)

![Image](https://user-images.githubusercontent.com/3516343/35281995-b9b683b2-0097-11e8-98a2-ada5ee1d72b7.png)

---

backupフォルダに過去のxmlのバックアップらしきものがあるので見てみましたが、読み書きができないからか更新日時はおそらく壊れた日付で止まっていました。内容も壊れていました。

![無念](https://user-images.githubusercontent.com/3516343/35282058-e72b3612-0097-11e8-90cf-9b82bbe32208.png)

xmlが壊れている場合はxmlの初期化をして、壊れたファイルをバックアップしてしまわないようになるとありがたいです。

なお壊れたのはACTを強制終了や多重起動したりしたせいだと思います。

以下xmlが壊れているときに出ていたエラーです。

```
2018-01-20 11:00:41.2794 [ERROR] ACT.SpecialSpellTimer.Utility.Logger.Write() XMLファイルの読み込みで例外が発生しました System.InvalidOperationException: XML ドキュメント (0,0) でエラーが発生しました。 ---> System.Xml.XmlException: ルート要素が見つかりません。
   場所 System.Xml.XmlTextReaderImpl.Throw(Exception e)
   場所 System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   場所 System.Xml.XmlReader.MoveToContent()
   場所 Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read4_ArrayOfOnePointTelop()
   --- 内部例外スタック トレースの終わり ---
   場所 System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   場所 System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   場所 ACT.SpecialSpellTimer.Models.OnePointTelopTable.Load(String file, Boolean isClear)
```

**Comment by anoyetta** [comment]
かなりのレアケースであるため本格的なフェールセーフとはいきませんが、それなりに対策を入れました。
