### ISSUE TITLE
Yukkuri blank screen

### ISSUE THREAD

**Issue by Jared0811** [anoyetta/ACT.Hojoring#335]
**Describe the bug**
Yukkuri stopped working, just shows blank screen

**To Reproduce**
1. Turn on ACT
2. Yukkuri is blank

**Screenshots**
![image](https://user-images.githubusercontent.com/92589089/137500352-d5d4424d-091c-4bdf-95dd-785ac2c5507b.png)

**Environment**
- ACT.Hojoring Version: 9.3.6
- FFXIV_ACT_Plugin Version: 2.2.1.6
 - OS: Windows 10

**Additional context**
Suddenly happened, unsure when. Was fine like a month ago.

**Comment by hyskylord** [comment]
Please post logs, directory should be %AppData%\anoyetta\ACT\logs
