### ISSUE TITLE
[TTSYukkuri] VOICEROIDが紐付けされていない状態でTriggerが発動するとACTが操作できなくなる

### ISSUE THREAD

**Issue by maeshu84** [anoyetta/ACT.Hojoring#34]
いつもVOICEROIDでTTSYukkuriを使わせてもらっています。
VOICEROIDがTTSYukkuriと紐付けされていない時にTriggerが発動すると以下のエラー文が出ます。
![default](https://user-images.githubusercontent.com/21168119/35309530-4c4debb8-00f0-11e8-8f5e-89a33959255f.PNG)
ウィンドウを消すと以下のメッセージが出てACTが動作を停止します。
![2](https://user-images.githubusercontent.com/21168119/35309532-51db1c36-00f0-11e8-954e-925bf5822502.PNG)

対処法としてはTTSYukkuriの設定タブを開いてVOICEROIDをTTSYukkuriと紐付けるだけなのですが、たまに設定タブを開くのを忘れてコンテンツに行ったりするとウィンドウが大量に生成されてしまいます。

ACT起動時にVOICEROIDを自動で紐付けるようになったら便利なのですが、エラーが出ないだけでもありがたいです。

**Comment by anoyetta** [comment]
エラーが出ないようにするのはおそらく出来るとは思います。
そのためにはエラー箇所を特定する必要があります。

なので、Helpタブからサポート情報を保存して送ってください。

**Comment by maeshu84** [comment]
> Unhandled Exception
> System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
>    場所 ACT.TTSYukkuri.Voiceroid.VoiceroidSpeechController.<Start>d__12.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 ACT.TTSYukkuri.Voiceroid.VoiceroidSpeechController.<Speak>d__13.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    場所　System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    場所 System.Threading.ThreadPoolWorkQueue.Dispatch()
エラー箇所こちらになると思われます。

**Comment by anoyetta** [comment]
すみません。
ログファイル全体をください。

**Comment by maeshu84** [comment]
すみません、こちらになります。
[ACT.Hojoring.2018-01-24.log](https://github.com/anoyetta/ACT.Hojoring/files/1658371/ACT.Hojoring.2018-01-24.log)
[Advanced Combat Tracker.log](https://github.com/anoyetta/ACT.Hojoring/files/1658372/Advanced.Combat.Tracker.log)

**Comment by anoyetta** [comment]
一応、対策はしてみますが効くかどうかは分かりません。
VOICEROIDはオマケ的な対応ですし、例外とはいえ使い方の問題ではあるので気をつけて使ってください。

**Comment by maeshu84** [comment]
了解です。ありがとうございます。
