### ISSUE TITLE
UI scaling  issue 

### ISSUE THREAD

**Issue by jenkshi** [anoyetta/ACT.Hojoring#340]
**Describe the bug**
hi, I Hojoring rescale my ACT window every time I install it. 
//こんにちは、私はホジョリングがACTウィンドウをインストールするたびに再スケーリングします。

this is with Hojoring installed in ACT:
//これは、ACTにHojoringがインストールされている場合です。
![image](https://user-images.githubusercontent.com/47603870/141653044-54cb5a85-016f-4f31-a061-702e26cd5026.png)

this is Hojoring uninstalled in ACT:
//これは、ACTでアンインストールされたHojoringです。
![image](https://user-images.githubusercontent.com/47603870/141611149-4aaedb52-17aa-45ad-b586-aba143207a9b.png)

as you can see Hojoring changes the content size of ACT and make it hard for me to read please help me.
//ご覧のとおり、HojoringはACTのコンテンツサイズを変更し、読みにくくしています。助けてください。

**To Reproduce**
Click on 'ACT.exe'

**Screenshots**
this is with Hojoring installed in ACT:
//これは、ACTにHojoringがインストールされている場合です。
![image](https://user-images.githubusercontent.com/47603870/141653044-54cb5a85-016f-4f31-a061-702e26cd5026.png)

this is Hojoring uninstalled in ACT:
//これは、ACTでアンインストールされたHojoringです。
![image](https://user-images.githubusercontent.com/47603870/141611149-4aaedb52-17aa-45ad-b586-aba143207a9b.png)

**Environment**
- ACT.Hojoring Version: 9.3.7
- FFXIV_ACT_Plugin Version: : 2.2.1.6
 - OS: Windows 10

**Additional context**
as I said before the UI size will change just by (add/enable plugin) any of .dll Hojoring files. Removing them will bring the UI scale back to normal. please help me I want to use your plugin but not have my UI too small to read.

/** 前に言ったように、UIサイズは.dll Hojoringファイルのいずれか（プラグインを追加/有効化）によって変更されます。 それらを削除すると、UIスケールが通常に戻ります。 プラグインを使用したいのですが、UIが小さすぎて読めないようにしてください。*/

**Comment by wbonbon** [comment]
read this FAQ

https://github.com/anoyetta/ACT.Hojoring/wiki/FAQ-jp#Hojoring%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%97%E3%81%9F%E3%82%89%E4%B8%80%E9%83%A8ACT%E3%81%AEUI%E3%81%8C%E5%A4%A7%E3%81%8D%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E6%8F%8F%E7%94%BB%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%8B
