### ISSUE TITLE
補助輪が動かなくなりました

### ISSUE THREAD

**Issue by TwinAngel777** [anoyetta/ACT.Hojoring#341]
いつも便利に利用させて頂いてありがとうございます

２週間位前から補助輪が動かなくなり大変不便になっております
もし原因等わかるようであればご助力頂ければ助かります

ACT.SpecialSpellTimer.dllは初期化エラーとなり、
ACT.TTSYukkuri.dllはステータスなしの状態で
その２つについてはタブ自体は登録されますが、タブ内は何も表示されません。
ACT.UltraScouter.dllはACTにDLLを登録する時点でエラーとなります。

詳細は画面のハードコピーを添付しますのでそちらをご確認下さい。
あと必要な情報があれば言って下さい。

![001](https://user-images.githubusercontent.com/94295202/141680486-96277392-cc2c-407e-a441-60fcf6e38ca7.jpg)
![002](https://user-images.githubusercontent.com/94295202/141680488-c22fe9b0-0bc2-4798-998c-3ca2e7652086.jpg)
![004](https://user-images.githubusercontent.com/94295202/141680490-3f684fd2-235c-46ad-8e91-0a8bb947c13d.jpg)

**Comment by TwinAngel777** [comment]
ログも添付しておきます

[ACT.Hojoring.2021-11-14.log](https://github.com/anoyetta/ACT.Hojoring/files/7533680/ACT.Hojoring.2021-11-14.log)
[activator.2021-11-14.log](https://github.com/anoyetta/ACT.Hojoring/files/7533681/activator.2021-11-14.log)

**Comment by wbonbon** [comment]
おそらく
\AppData\Roaming\anoyetta\ACT\FFXIV.Framework.config
このファイルが破損しています
backupフォルダにあるファイルをコピーしてリネームするか
FFXIV.Framework.configを削除してからACTを起動してみてください

**Comment by TwinAngel777** [comment]
ありがとうございます
FFXIV.Framework.configファイルを削除したり、バックアップからリカバリしても
ACT.TTSYukkuri.dll以外は正常に登録出来ませんでしたが
\AppData\Roaming\anoyetta\ACTフォルダをリネームして新規に作り直し
プラグインを登録し直すと全て問題なく登録出来ました。

ありがとうございます
