### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Kaiay** [anoyetta/ACT.Hojoring#344]
I got a lot of red error while update from 5.x to 6.0(v10.0.3) by update_hojoring.ps1
here is the update log
[https://1drv.ms/u/s!Ap7_PFWyRrGdyhVyhKhflOnJudbF](url)
after the error update act start with error and closed itself quickly.
can anyone send some help please?

**Comment by wbonbon** [comment]
Do not install ACT on C: \Program Files (x86)\Advanced Combat Tracker
Must be installed in C: \ACT etc.

**Comment by Kaiay** [comment]
Ok thanks for the reply. So I move act file to C:/ . And try update with update_hojoring.ps1,this time it runs great and finish without red error. But when I try to reenable all the plugins, everything works fine expect all the Hojoring's plugins.
When I add UltraScouter, this error comes out.
[https://1drv.ms/u/s!Ap7_PFWyRrGdyhe_yEooXbK5iIYw](url)
When I add SpecialSpellTimer ,another error comes out.
[https://1drv.ms/u/s!Ap7_PFWyRrGdyhbaI-dbVIHOJTy_](url)

What should I do?

**Comment by wbonbon** [comment]
Have you updated FFXIV_ACT_Plugin to 2.6.2.3?

**Comment by Kaiay** [comment]
(just find that i can copy and paste here lol sorry)
![image](https://user-images.githubusercontent.com/43386053/144899499-f20a6bc4-fac3-42da-b4ee-07c6de640d1c.png)
yes I have 2.6.2.3

**Comment by wbonbon** [comment]
Delete ACT WebSocket
This plugin is no longer available

**Comment by Kaiay** [comment]
I use mopimopi by ACTWebSocket, so I change it to overlay plugin and delete ACTWebSocket. Restart and everything works!
Thank you so much!
