### ISSUE TITLE
"Hide in not in combat" not Working

### ISSUE THREAD

**Issue by wrathfulmonkey** [anoyetta/ACT.Hojoring#347]
Triggers (TTS) work correct. But the option "Hide in not in combat" is not working.

FFXIV_ACT_Plugin v2.6.2.3
ACT.Hojoring v10.0.4
ACT.SpecialSpellTimer v3.0.0

**Comment by wbonbon** [comment]
Hojoring uses [FFXIVAPP/sharlayan](https://github.com/FFXIVAPP/sharlayan)
Some features do not work properly as sharlayan is not yet compatible with 6.0
If you turn on "Simplify detection in combat" the feature may work

**Comment by wrathfulmonkey** [comment]
Thx for the reply. I tried "Simplify detection in combat" and it works "better".
If it is a known issue i will wait until its fixed.

**Comment by wbonbon** [comment]
It will be fixed when the 6.0 compatible version of sharlayan is released.
Please wait for a moment.

**Comment by wbonbon** [comment]
"Hide in not in combat" now works in 10.0.5
