### ISSUE TITLE
Spell Extend not working correctly?

### ISSUE THREAD

**Issue by Shiriow** [anoyetta/ACT.Hojoring#349]
I'm trying to make a Death's Design trigger from Shadow of Death/Whorl of Death to make it easier to check it, but I'm having trouble with the extend feature.
If I add 30s on the trigger, and 30s on the extension it always gives me 60s, even when I first apply it
Making the trigger 0s and the extension 30s caps at 30s, even though I have the upper limit at 60s

![Advanced_Combat_Tracker_sXrGccZqGo](https://user-images.githubusercontent.com/22687973/145435683-85eb02dd-18b5-443a-a894-91a6bfb7befb.png)

**Comment by wbonbon** [comment]
https://github.com/anoyetta/ACT.Hojoring/wiki/SpecialSpellTimer_Examples
refer to the first example.
No need to extend.
1A:<id8>:(?<victim>.+?) gains the effect of (?<effect>Death's Design) from <mex> for (?<duration>[0-9\.]+)

**Comment by Shiriow** [comment]
That worked, thank you!
