### ISSUE TITLE
InitPlugin eroorとFatal Error

### ISSUE THREAD

**Issue by packetstorm0** [anoyetta/ACT.Hojoring#351]
**現象の詳細**  
記載された手順どおりアップデートを行いましたがエラーがでてしまいました。
過去のものを全て消して新規で追加してみても同様のエラーが発生してしまいました。

**再現方法**  
アプリケーション:Advanced Combat Tracker.exe 
フレームワークのバージョン:v4.0.30319 説明: ハンドルされない例外のため、プロセスが中止されました。
例外情報:System.InvalidOperationException 
場所 System.Windows.Input.InputManager..ctor() 
場所 System.Windows.Input.InputManager.GetCurrentInputManagerImpl() 
場所 System.Windows.Input.KeyboardNavigation..ctor() 
場所 System.Windows.FrameworkElement+FrameworkServices..ctor() 
場所 System.Windows.FrameworkElement.EnsureFrameworkServices() 
場所 System.Windows.FrameworkElement..ctor() 
場所 System.Windows.Controls.Control..ctor() 
場所 System.Windows.Window..ctor() 
場所 FFXIV.Framework.WPF.Views.ModernMessageBox..ctor() 
場所 FFXIV.Framework.WPF.Views.ModernMessageBox.ShowDialog(System.String, System.String, System.Windows.MessageBoxButton, System.Exception) 
場所 ACT.TTSYukkuri.PluginCore+<InitPlugin>d__30.MoveNext() 
場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
場所 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 
場所 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 
場所 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() 
場所 System.Threading.ThreadPoolWorkQueue.Dispatch()</Data> 

**環境**
- 補助輪のバージョン: v10.0.7
- FFXIV_ACT_Pluginのバージョン: : 2.6.2.8
- OS: Windows 10 Pro 1903

**追加のコメント**  
記載された手順に従いXIVとACTを落としresource以外を削除し新しいものを上書きしましたが
プライグイン追加をするとこのエラーでACTごと終了してしまいます。

補助輪を7zipでの解凍
Visual Studio 2017 用 Microsoft Visual C++ 再頒布可能パッケージ
.NET Framework 4.8
この二つを再度確認しましたがこれよりも新しいバージョンがインストール済みとでました。
ENDWALKER前までは全て問題なく動作していました。
.NET Framework関係の原因かと思いましたがインストールに必要と記載されているものは
既に入っているようで原因がわかりませんでした。

* 注意  
    * 現象のスクリーンショットを添付してください
![ACT-error-4](https://user-images.githubusercontent.com/95953641/145665925-79c049fc-4cf0-42ae-affc-ad6db3570b95.png)
![ACT-error-3](https://user-images.githubusercontent.com/95953641/145665934-f63938ce-4129-4af1-af2c-e2aae842d8cf.png)

**Comment by wbonbon** [comment]
ACTWebSocketを削除してください
ACTWebSocketはもうサポートされていません
代わりの機能が必要ならngld/OverlayPluginに実装されています

**Comment by packetstorm0** [comment]
大変失礼しました。
ACTWebSocketがサポートされていないとは思いませんでした。
まさか他に原因があるとは考えが及ばず試しもせずお手数すみませんでした。
解決しました。本当にありがとうございます。
