### ISSUE TITLE
スペスペ使用時、不規則にDPS計測がリセットされる

### ISSUE THREAD

**Issue by subarun777** [anoyetta/ACT.Hojoring#361]
■詳細
スペスペを使用しDPS計測を実施していると、不規則（2秒～60秒ほど）に計測がリセットされる。
スペスペ未使用時には本現象は発生せず、DPSの計測は正常に行われる。
木人やID、討滅戦などコンテンツに関わらず当該現象が発生。

■再現方法
1.スペスペを有効にする
2.任意のコンテンツで戦闘を開始
3.DPSの計測中、不規則な感覚で計測がリセットされ、新しく計測が開始される

※ACTの再インストールやプラグインの再導入、設定の削除などを試みたものの変化なし。

■環境
ACT v3.6.0
FFXIV_ACT_Plugin v2.6.4.1
OverlayPlugin v0.18.0.0
ACT.Hojoring v10.1.0
ACT.SpecialSpellTimer v3.0.0
ACT.UltraScouter v2.0.0
ACT.TTSYukkuri v7.0.0
OS: Windows10 v20H2

**Comment by wbonbon** [comment]
PCの時計が狂っている場合そのようになります
[https://time.is/](url)
確認してみてください
