### ISSUE TITLE
SPESPE上のゾーン設定で特定のコンテンツが表示されていない

### ISSUE THREAD

**Issue by RodyPhan** [anoyetta/ACT.Hojoring#371]
**現象の詳細**  
現象の詳細を明確に記載します。
スぺスぺの設定をしている時。
特定のトリガーを設定している際にゾーン設定の所で煉獄編や絶竜詩のチェックボックスがない

**再現方法**  
現象の再現方法を記載します。
1. Go to 'SPESPE'
2. Click on 'スペル'
3. 特定スペル上で Scroll down to 'ゾーン設定'

**環境**
- 補助輪のバージョン: v10.2.0
- FFXIV_ACT_Pluginのバージョン:  v2.6.7.1
- OS: Windows ? Win10 Home 64 bit 10.0 build 19045

**追加のコメント**  
なにか追加するコメントがあれば記載します。

* 注意  
    * 現象のスクリーンショットを添付してください

**Comment by wbonbon** [comment]
[TerritoryType.ja-JP.csv](https://github.com/anoyetta/ACT.Hojoring/files/10147541/TerritoryType.ja-JP.csv)
このファイルを上書きコピーして、プロパティで「読み取り専用」をチェックしてください
（anoyettaさん多忙に付き暫定対応）

**Comment by wbonbon** [comment]
日本語のみの対応であればそれで良いです

ファイルをanoyettaさんに渡しておいたので
そのうち起動時のリソースダウンローダが更新されたcsvをダウンロードするようになると思います
すぐに利用したいなら上書き＆読み取り専用で使ってください
いずれ使えればいいのであれば更新されるのを待った方が良いと思います

**Comment by RodyPhan** [comment]
返信ありがとうございます。

特に急ぎではないのanoyettaさんがアップデートされるのを待とうと思います。

**Comment by torakiti2017** [comment]
表題の件、オルトエウレカのエリアを表示させたいのですが、パッチ6.35に対応したファイルはありますでしょうか。
もしよろしければ使わせていただきたいです。

**Comment by wbonbon** [comment]
[TerritoryType.ja-JP.csv](https://github.com/anoyetta/ACT.Hojoring/files/10964684/TerritoryType.ja-JP.csv)

ちなみにこのファイルの作り方は
[https://github.com/xivapi/SaintCoinach](url)
を使って
\> lang ja
\> exd TerritoryType
このコマンドで取り出したcsvを
TerritoryType.ja-JP.csv
にリネームで作っています

**Comment by torakiti2017** [comment]
対応ありがとうございます。
また、作成方法の情報もありがとうございます。
必要になった際、試してみたいと思います。

**Comment by torakiti2017** [comment]
上記の方法で作成してみたのですが、六根山／異聞六根山が表示出来ませんでした。
csvデータ内には六根山などの文字があるのですが、スペスペ上では表示されていない状態です。
スペスペ上で表示させる条件などありますでしょうか？
添付したファイルはSaintCoinachで出力したリネーム前のcsvです。
[TerritoryType.csv](https://github.com/anoyetta/ACT.Hojoring/files/12506630/TerritoryType.csv)

**Comment by wbonbon** [comment]
ゾーンフィルタに使うゾーンをcsvからリストアップする関数が
[https://github.com/anoyetta/ACT.Hojoring/blob/c560e1b35238b03f7ff696e271f406e6830cd159/source/FFXIV.Framework/FFXIV.Framework/XIVHelper/Zone.cs#L46](https://github.com/anoyetta/ACT.Hojoring/blob/c560e1b35238b03f7ff696e271f406e6830cd159/source/FFXIV.Framework/FFXIV.Framework/XIVHelper/Zone.cs#L46)
[https://github.com/anoyetta/ACT.Hojoring/blob/c560e1b35238b03f7ff696e271f406e6830cd159/source/FFXIV.Framework/FFXIV.Framework/XIVHelper/Zone.cs#L107](https://github.com/anoyetta/ACT.Hojoring/blob/c560e1b35238b03f7ff696e271f406e6830cd159/source/FFXIV.Framework/FFXIV.Framework/XIVHelper/Zone.cs#L107)
ヴァリアントダンジョン・アナザーダンジョンに対応していないため表示されないようですね
これは小細工ではどうにもなりませんな…

**Comment by wbonbon** [comment]
resources\xivdbのcsvを全て6.51版に更新しました
また、次のリリースでヴァリアントダンジョンに対応します #383
