### ISSUE TITLE
Plugin init errorが出ました

### ISSUE THREAD

**Issue by hun2010111** [anoyetta/ACT.Hojoring#372]
**現象の詳細**  
PCがフリーズした為強制終了させた際にACTがエラーをはいて動かなくなってしまったので一度ACT関連をすべてインストールし直しました。
しかしSpesialSpellTimerを導入した際に以下のエラーが出るようになってしまいスぺスぺが動きません
どうすればいいでしょうか

**再現方法**  
現象の再現方法を記載します。
1. SpesialSpellTimer.dllをEnable Pluginする
２. 以下のエラーが出る

**環境**
- 補助輪のバージョン: v10.2
- FFXIV_ACT_Pluginのバージョン: v2.6.7.1
- OS:  #Windows１０
![2022-12-08 (4)](https://user-images.githubusercontent.com/120069605/206333252-d1efb94c-3f1f-4921-8cc6-c046fe1dfc34.png)
![2022-12-08 (6)](https://user-images.githubusercontent.com/120069605/206333474-a06f1f27-4b32-4cdf-b084-d1ec8defbc6b.png)

**Comment by wbonbon** [comment]
%appdata%\anoyetta\ACT
このフォルダの中の複数のファイルが破損してると思われるので
A.テキストエディタで開いて真っ白なファイルを消してバックアップから戻す
B.フォルダごと消す
のどっちか

**Comment by hun2010111** [comment]
フォルダごと消すを試しましたが同様のエラーがでます

**Comment by wbonbon** [comment]
resourcesフォルダまたはその中にあるファイルを読み取るときの操作に失敗しているようなので
補助輪のフォルダも全部消して入れなおしたら直ると思います
それでも直らない場合はDiscordへ来て下さい
