### ISSUE TITLE
Plugin Init Error !

### ISSUE THREAD

**Issue by ashr420** [anoyetta/ACT.Hojoring#378]
**Describe the bug**
Getting this error when trying to install TTSYukkuri

**To Reproduce**
1. Go to plugin listing
2. Click on browse
3. Scroll down to yukkuri.dll
4. Add/enable

**Screenshots**
![Screenshot 2022-12-28 215215](https://user-images.githubusercontent.com/96807889/209842376-f65794de-2743-43aa-ae02-f1f48311b132.png)

**Environment**
- ACT.Hojoring Version: 10.2.5
- FFXIV_ACT_Plugin Version: 3.6.1
 - OS: Windows 10

**Additional context**

**Comment by wbonbon** [comment]
your internet problems
If you still haven't solved it, come to Discord
