### ISSUE TITLE
Fatal Error Unhandled exception

### ISSUE THREAD

**Issue by NiceManiac** [anoyetta/ACT.Hojoring#381]
Unhandled exception on startup leading to audiodevices not working.

**To Reproduce**
1. Install ACT
2. Install FFXIV parser plugin
3. Install Overlayplugin
4. Install Cactbot
5. Install TTSYukkuri
6. See error

**Screenshots**
![image](https://github.com/anoyetta/ACT.Hojoring/assets/3496098/d94c3731-f4da-4cfd-b27f-d31b758575dd)

**Environment**
- ACT.Hojoring Version: 3.6.2
- FFXIV_ACT_Plugin Version: 2.6.8.9
- ACT.Hojoring: v10.2.5
- ACT.SpecialSpellTimer: v3.0.0
- ACT.UltraScouter: v2.0.0
- ACT.TTSYukkuri: v7.0.0
 - OS: Windows 11 Pro

**Comment by wbonbon** [comment]
tell me what sound device you have
It seems that creating the sound device list has failed
It may improve in the next release which includes updates to NAudio #383
