### ISSUE TITLE
Yukkuri Discord Botのドロップ問題

### ISSUE THREAD

**Issue by Tsunatus** [anoyetta/ACT.Hojoring#382]
ユックリプラグインのDiscord機能が、設定したチャンネルにBotを留めることができず、どんどん落としてしまいます。あなたのガイドを参考にボットをセットアップしました。Yukkuriの他の機能はすべて動作しますが、Discordボットだけが問題を抱えています。また、ログに表示されているエラーを含むファイルを投稿しましたので、ご確認ください。

何かありましたら、よろしくお願いします。
[Yukkuri bot logs.txt](https://github.com/anoyetta/ACT.Hojoring/files/11594093/Yukkuri.bot.logs.txt)

The Discord function of the Yukkuri plugin is not able to keep the bot in the channel I set it to and keeps on dropping it. I set up the Bot using your guide. All other functions of Yukkuri work but just the discored bot is having problems. I have also posted the errors that are appearing in my logs for your review.

Any help would be appreciated.
[Yukkuri bot logs.txt](https://github.com/anoyetta/ACT.Hojoring/files/11594093/Yukkuri.bot.logs.txt)

**Comment by wbonbon** [comment]
Discord APIを更新しなければならないのですが、
TTSYukkuriはまだ更新されておらず現在のところ対応していません(anoyetta氏が多忙のため）

**Comment by wbonbon** [comment]
次のリリースで修正されます #383
