### ISSUE TITLE
[SpecialSpellTimer] ガイドグリットをサブディスプレイにも表示してほしい

### ISSUE THREAD

**Issue by alalwww** [anoyetta/ACT.Hojoring#40]
デュアルディスプレイ環境で使用しています。
ガイドグリット表示を試したところ、ガイドグリッドがサブディスプレイに表示されませんでした。
以下を試しましたが、全てメインディスプレイのみにガイドグリッドが表示されました。

- ACT本体をメインディスプレイで起動し、ガイドグリッドのチェックをONにする
- ACT本体をサブディスプレイに移動し、ガイドグリッドのチェックをONにする
- ACT本体をサブディスプレイで一度終了し、サブディスプレイで起動し、ガイドグリッドのチェックをONにする

メイン設定にしているディスプレイにACTやその他のウィンドウを配置しサブディスプレイでFF14を表示してプレイしているため、サブディスプレイでのグリッド表示にも対応してもらえるとうれしいです。

**Comment by anoyetta** [comment]
すべてのディスプレイに表示するようにします。
基本的に細かいところではマルチディスプレイでの運用をあまり考慮していません。よってある程度は我慢せざるを得ないところもあるかと思います。例えばダイアログの表示位置とか。
「これはどうしても」という部分があれば言ってもらえれば対応します。

**Comment by anoyetta** [comment]
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v5.0.9
リリースしておきました。
シングルディスプレイで動作確認はしましたが、私の環境がマルチディスプレイではないので実際にすべてのディスプレイで本当に表示されるかは定かではありません。
ダメだったら言ってください。ディスプレイつなげて確認しますんで。

**Comment by alalwww** [comment]
@anoyetta サブディスプレイにも表示されるようになりました。ありがとうございます。:bow:
