### ISSUE TITLE
SPESPE使用時の現在のゾーンによるフィルタが利用できない

### ISSUE THREAD

**Issue by fil997** [anoyetta/ACT.Hojoring#407]
SPESPE使用時、「現在のゾーンによるフィルタ」を開くとまっさらな状態になっており、選択ができない状態です。

下記URLに記載されているTerritoryType.ja-JP.csvを読み取り専用にしたうえで利用してみたところ、「現在のゾーンによるフィルタ」でゾーンを選択できる状態にはなりましたが、2年ほど前のデータになっているため、最新のゾーンが利用できない状態です。
https://github.com/anoyetta/ACT.Hojoring/issues/371

こちらにつきまして、ご教示いただけますと幸いです。

FFXIV_ACT_Plugin v2.7.1.2
ACT.Hojoring v10.3.7
ACT.SpecialSpellTimer v3.0.0
ACT.UltraScouter v2.0.0
ACT.TTSYukkuri v7.0.0

**Comment by wbonbon** [comment]
起動時にresourcedownloaderが
2024-08-05 09:59:08.8364 [Info ] Downloaded... C:\Advanced Combat Tracker\plugin\ACT.Hojoring\resources\xivdb\TerritoryType.ja-JP.csv, verify is completed. 
っていうログをだすと思うんですが、
そのあと一度ACTを再起動して下さい。
最新の状態でゾーンフィルタが使えるようになるはずです

**Comment by wbonbon** [comment]
あーーーーーー
わかりました
7.05のリソース更新時に手順を一つ忘れていました
今から直します

**Comment by wbonbon** [comment]
すみません、修正しました
勝手に更新されたcsvがダウンロードされるはずなのでゾーンフィルタが表示されるようになるはずです

**Comment by fil997** [comment]
Hojoring更新後、ゾーンフィルタの表示を確認しました。
お早いご対応ありがとうございました。
