### ISSUE TITLE
スペスペのテロップの「表示したときの通知」が動作しない

### ISSUE THREAD

**Issue by sasakiba** [anoyetta/ACT.Hojoring#408]
スペスペ→Triggers→テロップ→Noriceの「表示したときの通知」が動作しません。
「テロップに表示するメッセージ」に記述した内容は画面に表示されます。
「マッチしたときの通知」は動作しています。
「疑似的にマッチさせる」を押したときは「表示したときの通知」も動作しています。

例えば下記の設定した時の動作はこうなります。
・「テロップに表示するメッセージ」：テスト
・マッチから10秒後に3秒間表示する
・「マッチしたときの通知」のTTS：音声テスト1
・「表示したときの通知」のTTS：音声テスト2

1．ログがマッチしたときに「音声テスト1」が再生される
2．10秒後に「テスト」と画面に表示されるが、「音声テスト2」が再生されない

**環境**
FFXIV_ACT_Plugin v2.7.1.2
ACT.Hojoring v10.3.7
OS: Windows10

**Comment by wbonbon** [comment]
以前プラグインの高速化のために可能な限りDateTime.NowをDateTime.UtcNowに変更した際に、
避けなければいけないところを避けてやったつもりだったんですがやってしまったようです

**Comment by wbonbon** [comment]
修正しましたー
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v10.3.7-240805.1118

**Comment by sasakiba** [comment]
ありがとうございます！
問題なく動作しました。

**Comment by neko8** [comment]
同じ症状が生じていましたので修正後のものをインストールしたのですが症状が消えません。ACT本体ごと再インストールすべきでしょうか。教えて頂けたらありがたいです。

**Comment by wbonbon** [comment]
本当に同じケースなら直ってるはずなので同じではないはずです
別の原因があるかどうかわからないので再現の仕方をおしえてください

**Comment by neko8** [comment]
早速のお返事ありがとうございます。
強化薬のリキャストが戻ったときの注意喚起のためにTTSを鳴らしていたのですが、少し前の時期から鳴らなくなっていました。
テスト用にテロップを作成し、マッチ時のWAVEとTTS、表示時の(ディレイ後の)WAVEとTTSを設定し、ディレイ時間を5秒に設定の上、擬似的にマッチさせるをクリックしました。
マッチ時のものはWAVE、TTSとも鳴りますが、ディレイ後のものはいずれも鳴りません。

2024年8月7日(水) 17:45 bonbon ***@***.***>:

**Comment by wbonbon** [comment]
![Advanced_Combat_Tracker_20240807-180528](https://github.com/user-attachments/assets/ec556129-5bfe-44cc-acc8-779b7fed7098)
![Advanced_Combat_Tracker_20240807-180538](https://github.com/user-attachments/assets/bb33b925-ade9-4492-a8a9-6600bc7e19cb)

これでゲーム内で
/e 遅延通知テスト
って喋ると動くことを確認しています

**Comment by wbonbon** [comment]
![Advanced_Combat_Tracker_20240807-181745](https://github.com/user-attachments/assets/8333d818-fe14-4ac1-95b5-b05766d45a17)
![Advanced_Combat_Tracker_20240807-181805](https://github.com/user-attachments/assets/784896e3-47a6-49fd-9fa0-31645aa3409b)

ためしにテロップではなくスペルで同じようなことをしてみましたがこれも動作しました

**Comment by neko8** [comment]
ゲーム内にて確認したところ、想定される動作が確認できました。大変ありがとうございました。
なお、擬似的にマッチさせる では変化がありませんでした。
ゲーム内で確認すべきでした。申し訳ありませんでした。

2024年8月7日(水) 18:08 bonbon ***@***.***>:

**Comment by wbonbon** [comment]
あー
「擬似的にマッチさせる」
も同じエンバグがありました
すみません、修正します

**Comment by neko8** [comment]
そうなのですね。
重ね重ねありがとうございます。

2024年8月7日(水) 18:26 bonbon ***@***.***>:
