### ISSUE TITLE
スペスペのスペルパネルで高度なレイアウトを使用した場合にソート順が適用されない。

### ISSUE THREAD

**Issue by chocoboman** [anoyetta/ACT.Hojoring#411]
**現象の詳細**  
スペルパネルのGeneralでソート順を「表示順を最優先にする」を、
Advanced Layoutで「高度なレイアウト設定を使用する」、「Right」を設定していますが。
表示順を優先してアイコンが並んでくれません。
「高度なレイアウト設定を使用する」のチェックを外すと表示順にならんでくれます。

スペルパネルを右詰で表示順にソートする方法はないでしょうか。

**環境**
FFXIV_ACT_Plugin v2.7.1.8
ACT.Hojoring v10.3.7
OS: Windows11

**Comment by wbonbon** [comment]
今どういう設定で、結果どうなってほしいのかよく分かんないです
試しに
Advanced Layout (スペルのレイアウトでX Yを指定されたように表示する)
Advanced Layout + Stacked Layout (スペルのレイアウト順に積んで表示する)
Advanced Layout無し
の三種類が動く様を録画してみましたがこうならないってことですか？

https://github.com/user-attachments/assets/a53044dd-86ca-49ba-a677-d3b8ef18cb6d

**Comment by wbonbon** [comment]
Stacked Layoutがオンなので2番目ということは1番目になにか表示されてるはずなんですが、
タンクの場合は他に何を表示してるんでしょうか
それを再現するための全ての情報が必要です（Advanced Layoutだけではなく）

手っ取り早いのはDiscordにサポート情報を貼り付けに来ることですねー
![Advanced_Combat_Tracker_20240809-205106](https://github.com/user-attachments/assets/d9b3b8d0-daf2-49bf-8761-fb5889047a6b)

**Comment by chocoboman** [comment]
回答が遅くなってしまい申し訳ありません。
私の設定がおかしそうなので、設定を見直したり再作成などをしていたところ問題が発生しなくなりました。
情報出せず申し訳ありません。
