### ISSUE TITLE
Korea server, hojoring 10.4.3 crashed

### ISSUE THREAD

**Issue by Bing-su** [anoyetta/ACT.Hojoring#433]
![Advanced_Combat_Tracker_ee9kokN9Tx](https://github.com/user-attachments/assets/eb0309a5-cfd8-4a68-b2b5-eee54081bfed)

hojoringが10.4.2バージョンであったり、オフにしている場合はこの問題は発生しません。

韓国語のエラーの内容はindex out of boundです。

[Advanced Combat Tracker 2024-11-29.log](https://github.com/user-attachments/files/17960738/Advanced.Combat.Tracker.2024-11-29.log)
[ACT.Hojoring.HelpMe.2024-11-29.zip](https://github.com/user-attachments/files/17960739/ACT.Hojoring.HelpMe.2024-11-29.zip)
[ACT.Hojoring.2024-11-29.log](https://github.com/user-attachments/files/17960743/ACT.Hojoring.2024-11-29.log)

**Comment by wbonbon** [comment]
#434

**Comment by Bing-su** [comment]
ありがとうございます。うまく動きますね。
