### ISSUE TITLE
Spespe - 「ウェポンブレイク」アイコンがありません。

### ISSUE THREAD

**Issue by Bing-su** [anoyetta/ACT.Hojoring#435]
**Describe the bug**
機工士のウェポンブレイクアイコンがありません。

![003011](https://github.com/user-attachments/assets/265c5c30-91be-4215-8845-dba5aa9bb23a)

https://ffxivteamcraft.com/db/ko/action/2887/%EB%AC%B4%EA%B8%B0-%ED%8C%8C%EA%B4%B4

**Screenshots**
![Advanced_Combat_Tracker_MTronkqKSy](https://github.com/user-attachments/assets/a98bf688-60a0-4901-8d57-29c05f70b48d)

**Environment**
- ACT.Hojoring Version: v10.4.3
- FFXIV_ACT_Plugin Version: 2.4.4.0 (KR)
 - OS: Windows 11

**Comment by wbonbon** [comment]
ざっと調べましたがアクションに機工士のウェポンブレイクと同じ名前で実際には使われない別のウェポンブレイクがあり、
現在の補助輪は
「同じ名前のアクション」が
「該当するジョブで利用可能」な場合に
「最後にxivapiから取得できたアクション」を取得する
構造になっていました
同じ名前のアクションを全て取得するように変更しようと思います
（それが正しい実装なのかしらんけど）
具体的には
https://github.com/anoyetta/ACT.Hojoring/blob/6cbd48d7b1ee24e114d07f511e262f7c0783763a/source/FFXIV.Framework/FFXIV.Framework/xivapi/XIVAPIController.cs#L200
ここでgroup  byしているため、同じ名前のアクションが1つのグループにまとまり、
https://github.com/anoyetta/ACT.Hojoring/blob/6cbd48d7b1ee24e114d07f511e262f7c0783763a/source/FFXIV.Framework/FFXIV.Framework/xivapi/XIVAPIController.cs#L217
ここでグループの先頭（最後にgroupに追加された物）だけを取得しています

なのでgroup byをやめてselectにします

**Comment by wbonbon** [comment]
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v10.4.4-241214.1641

**Comment by Bing-su** [comment]
![image](https://github.com/user-attachments/assets/09280c73-3bcb-4f4b-94d7-60b7f13ba9ef)

~~ 😊
