### ISSUE TITLE
TTS設定がよくわかりません

### ISSUE THREAD

**Issue by ar600m9** [anoyetta/ACT.Hojoring#47]
タイムラインをTTSで読ませたいのですがエラーで読み込めません。あまり詳しくないのでご教授をお願いできますでしょうか？お忙しいところ恐縮ですがよろしくお願いします！

**Comment by ar600m9** [comment]
[ACT.Hojoring.HelpMe.2018-02-08.zip](https://github.com/anoyetta/ACT.Hojoring/files/1704221/ACT.Hojoring.HelpMe.2018-02-08.zip)

**Comment by anoyetta** [comment]
タイムラインか、むかし私が改造版を作ったけど自分では使ってないので今じゃ記憶が曖昧ですね。
教えてあげるにせよGitHubだとコミュニケーションが難しいのでDISCORDのフォーラムの方に来てください。
https://discord.gg/n6Mut3F
