### ISSUE TITLE
TTSYukkuri導入時にACTのUIフォントサイズが小さくなる

### ISSUE THREAD

**Issue by join-mtst** [anoyetta/ACT.Hojoring#48]
https://github.com/anoyetta/ACT.TTSYukkuri/issues/7
にも上がってましたが、TTSYukkuriをHojoring経由で導入した所ACT全体のフォントが小さくなりました。4K解像度のせいかと思いましたが何か原因を知ってますでしょうか？

環境
windows10
4Kディスプレイ

**Comment by anoyetta** [comment]
正直わたしもなんでか分からない。
わたしも4Kではないけど、DSRで高解像度かしつつスケーリングかけてるからこの現象はでています。
で、解消させるために考えられる手を打ってみたけどなぜだから直らない。

**Comment by anoyetta** [comment]
とはいっても、対処して普通に使う方法はあります。

1. 起動時のオプション（ショートカットの[プロパティ] → [互換性]）から、DPIスケーリングのモードを「アプリケーション」にする
2. ACTを起動する
3. その後ACTのフォントの設定で見やすいように変える

これで実用に困らないようにはなります。

そもそもWindows Formで作られたアプリは高解像度とスケーリングには弱いです。やや思いと異なりますが設定変更でレイアウトの乱れ等なく使えるなら、それはそれでまあいいかなと。

**Comment by join-mtst** [comment]
ありがとうございます。
対応方法があるんですね。
試してみます。
