### ISSUE TITLE
スペスペの文字のアウトラインについて

### ISSUE THREAD

**Issue by onigirinori7653** [anoyetta/ACT.Hojoring#49]
![default](https://user-images.githubusercontent.com/36393376/36083319-66f8b566-0ff4-11e8-8c53-8617e06d8953.png)
今回ACT.Hojoringのv4.12からv5.0.16に変えたのですが
スペスペの文字のアウトラインがうまく表示されてないみたいで困っています
ウルスカのほうは文字のアウトラインが表示されるのですが
スペスペのほうがオプションのテキストのアウトライン増幅率をいじっても
表示されないです

**Comment by anoyetta** [comment]
ふつうに使っててそれらの現象は再現しないですね。
なにか特殊な条件があるのではないでしょうか？
私の環境でもその他の人のほとんどの環境でもアウトラインは描画されています。
