### ISSUE TITLE
[SpecialSpellTimer]テロップのジョブフィルターが保存されない

### ISSUE THREAD

**Issue by alalwww** [anoyetta/ACT.Hojoring#50]
チェックボックスをONにしタブを切り替えた後戻ると、赤文字 filterd! は表示されますがチェックボックスが空になります。設定ファイルを確認したところ、スペルのJobFilterと差異があるようなので、保存時の不具合なのではないかとおもい、報告します。

----

ACT.SpecialSpellTimer.Telops.xml の JobFilter
```
<JobFilter>CNJ,WHM,AST</JobFilter>
```

ACT.SpecialSpellTimer.Spells.xml の JobFilter
```
<JobFilter>6,24,28,33</JobFilter>
```

**Comment by alalwww** [comment]
数字に書き換えてみたところ、ロードされました。

**Comment by anoyetta** [comment]
以前スペルのほうが同様にバグってて直したのですが、テロップの方は抜けてたみたいです。
