### ISSUE TITLE
ゆっくり読み上げが使えなくなってしまいました

### ISSUE THREAD

**Issue by mochi-ksw** [anoyetta/ACT.Hojoring#51]
こんばんは、いつも利用させて頂いております。

先日、PCがフリーズし強制終了した際にACT全ての調子が悪くなってしまいました。
その際ACTフォルダ、設定フォルダを全て削除し、インストールし直した所、使えるようになりました。
ですがACT.Hojoringのプラグインを登録する際にエラーが出て使えなくなってしまいました。
ACT.Hojoringの設定フォルダも削除し、最新版、プレリリース版も使ってみましたがダメでした。

ログファイル等添付したいのですが、どこから添付するのでしょうか？
そもそも問い合わせ自体初めてで、使い方がわかっておりません。
ご迷惑おかけしますが、よろしくお願いします。

**Comment by anoyetta** [comment]
書き込みエリアにファイルをD&Dすれば添付できると思うよ。
もしくはDISCORDのほうに来たらよろしい。
DISCORDのほうがリアルタイムにやり取りできるし、ファイルの送付とかも簡単。

https://discord.gg/n6Mut3F
