### ISSUE TITLE
スペスペ、延長マッチングワードの2の時間が反映されない

### ISSUE THREAD

**Issue by Ponkoro** [anoyetta/ACT.Hojoring#52]
いつもありがたく使わせてもらっています。
ACT.Hojoring v5.3.1のスペスペで、延長マッチングワードの2の時間が反映されないようです。
マッチングはされているようでプログレスバーに変化はありますが、時間は+-どちらも適用されません。
ご確認ください。
また、こちらは要望になりますが、
ゾーンフィルタで各一般フィールド、街、ゴールドソーサー等を追加していただけると有り難いです。

**Comment by anoyetta** [comment]
フィールドやゴールドソーサー、街を限定してフィルタする必要性がないので追加することはないです。
ただ、その辺は外部ファイルなので自分で追加すれば動くのではないかと思います。
