### ISSUE TITLE
Special Spell Timers bug

### ISSUE THREAD

**Issue by donneee** [anoyetta/ACT.Hojoring#53]
One of my panels always list "Sample Skill" when it goes off. It's not suppose to say anything at all however since i have skill names hidden.
https://i.imgur.com/z1bzcj5.png

I can't figure out how to correct it, or if i even did something wrong.

**Comment by anoyetta** [comment]
調査を行うには状況を再現させる必要があります。
Helpタブからサポート情報を取得して私に送付してください。

**Comment by donneee** [comment]
私は実際にそれを考え出したと思う。他のパネルにあっても同じタイマーに同じアイコンが設定されていると、（写真のように）アイコンの上にSample Spellが表示されます。これは悪い日本人ならごめんなさい。私はLOLを翻訳していますが、後でそれを再現し、ヘルプタブから情報を送信しようとします。私は私のタイマーの初期のビルドを持っているので、私はそれらを確認することができます。

**Comment by thorgard** [comment]
Hello since version v5.28 spelltimer dont work i have just error sound every 30 sec but no cd on screen no sound nothing work . if i clic on try match the icon and vocal are ok but ingame i have no icon or vocal just alarm sound every 20 sec. 
i have upload my version but nothis 
help please
