### ISSUE TITLE
[TTSYukkuri] CeVIO Creative Studio、スペースの持続時間

### ISSUE THREAD

**Issue by citrouille** [anoyetta/ACT.Hojoring#54]
すみません、日本語をうまく使えない。

CeVIO Creative Studioを使う、優秀でした。単語登録と辞書管理は便利で効果的です。でも、CeVIOの「ポーズの設定」は影響がありません。そして、ACTの空白文字のタイミングが長過ぎる。CeVIO自体の問題ではないって、期待どおりの働くです。

![Setting](https://i.imgur.com/H21whrr.png)
ACT内、Yukkuriで変更されません。

たぶん問題の解決策あるに思うかな。

誠にお世話になりました。

Hello, my Japanese is not very good, and I apologize in advance.

CeVIO Creative Studio is a very good piece of software, and the custom dictionary works like a charm. However, CeVIO's "pause setting" feature has no effect, and ACT's whitespace pause durations are too long. There is no problem inside CeVIO itself, and it works as expected when I reduce the timing.

As the image above, Yukkuri does not defer to CeVIO to process the pauses.

I wonder if there is a solution to this problem?

Thank you for your hard work on this project.

**Comment by anoyetta** [comment]
CeVIO Creative Studio の設定項目は外部からのWAVEの出力時には反映されない項目がいくつかあります。ポーズの長さもその一つなのでしょう。CeVIO Creative Studio 自体の質問については、私は開発者ではないので分かりません。

CeVIO Creative Studio に限らず、TTSの生成時にポーズの長さを任意に指定することは出来ません。TTSとして解析させる文字列として、読点か句点かによってポーズ長さが決まります。日本語であれば、「、」「。」の違いによってポーズの長さが決まります。
英語であれば「,」「.」の違いによってポーズが変わることになりますが、CeVIO Creative Studio は英語を発する事ができません。よって、「,」「.」を正しく処理することが出来ないでしょう。
