### ISSUE TITLE
4k monitor resolution

### ISSUE THREAD

**Issue by donneee** [anoyetta/ACT.Hojoring#55]
when loading up hojoring, it scales it really small. here's an example. https://cdn.discordapp.com/attachments/337386688202670081/421850617301041153/acttinytext.PNG

**Comment by anoyetta** [comment]
互換性の設定で高いDPIスケールの動作を変更してください。
その後、ACT本体の設定でフォント及びフォントサイズを調整してください。
過去のissueに同様の事例があります。
