### ISSUE TITLE
[スペスペたいむ] シグマ4層　前半後半識別について

### ISSUE THREAD

**Issue by 1woo** [anoyetta/ACT.Hojoring#56]
v5.3.8において

t sync="「マジックチャージ」の構え" sync-count="1"
    load target="ケフカ" truncate="true" /
  /t
  t sync="「心ない天使」の構え" sync-count="1"
    load target="PHASE1 心ない大天使" truncate="true" /

最初の1回目以降、識別でません。
sync-countは全滅時にリセットされないのでしょうか？

**Comment by anoyetta** [comment]
最新のバージョン（その前など）で直っています。
