### ISSUE TITLE
FFXIV_MemoryReader.dll and ACT.UltraScouter Actions

### ISSUE THREAD

**Issue by Vuzrak** [anoyetta/ACT.Hojoring#58]
If FFXIV_MemoryReader.dll is enabled ACT.UltraScouter Actions do not display, it works fine if FFXIV_MemoryReader.dll is disabled.

**Comment by anoyetta** [comment]
ログをください。

**Comment by Vuzrak** [comment]
[ACT.Hojoring.HelpMe.2018-03-21.Action.zip](https://github.com/anoyetta/ACT.Hojoring/files/1832433/ACT.Hojoring.HelpMe.2018-03-21.Action.zip)
[ACT.Hojoring.HelpMe.2018-03-21.NoAction.zip](https://github.com/anoyetta/ACT.Hojoring/files/1832434/ACT.Hojoring.HelpMe.2018-03-21.NoAction.zip)

Action is the one that the action bar shows correctly while casting. NoAction is the one where it doesn't show with FFXIV_MemoryReader.dll loaded.
