### ISSUE TITLE
数日前からスペスペが動かなくなりました。

### ISSUE THREAD

**Issue by celeslane** [anoyetta/ACT.Hojoring#61]
数日前からスペスペが動かなくなり、Actorをインストールしましたが動きません。
どうすればよいのでしょうか。
ログファイルですが、「スペスペのサポート情報を保存する」を選択して保存したのですが、圧縮ファイルの送り方がわかりません。
どうやって送ればよいのでしょう。

**Comment by celeslane** [comment]
[ACT.Hojoring.HelpMe.2018-03-25.zip](https://github.com/anoyetta/ACT.Hojoring/files/1845248/ACT.Hojoring.HelpMe.2018-03-25.zip)
これで大丈夫ですか？

**Comment by anoyetta** [comment]
環境の設定ミスか何かではないでしょうか。

Hojoringのログには異常は見られません。
ACT本体のログのほうには数点のエラーが出力されていますが、要領を得ません。

一応、抜粋しておくと。

1. ACT.SpecialSpellTimer.dll が見つからないというエラー
***** 2018-03-25T14:50:32 - Loading plugin from config
System.IO.IOException: E:\あいすんACTハングル削除\Advanced Combat Tracker\ACT.SpecialSpellTimer.dll does not exist.
   場所 Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   場所 Advanced_Combat_Tracker.FormActMain.AddPluginPanel(String PluginPath, Boolean SuppressErrors)
   場所 Advanced_Combat_Tracker.FormActMain.LoadXmlActPlugins(XmlTextReader xReader)
   場所 Advanced_Combat_Tracker.FormActMain.LoadNewSettings(XmlTextReader xReader)
   場所 Advanced_Combat_Tracker.FormActMain.InitACT()
   場所 Advanced_Combat_Tracker.ActLoader..ctor(String[] args)
   場所 Advanced_Combat_Tracker.ActLoader.Main(String[] args)

2. ACT.SpecialSpellTimer\AssemblyResolver.cs のコンパイルで発生しているエラー
***** 2018-03-25T15:12:55 - Enabling plugin: E:\あいすんACTハングル削除\Advanced Combat Tracker\ACT.SpecialSpellTimer\AssemblyResolver.cs
***** 2018-03-25T15:12:56 - Plugin compilation: AssemblyResolver.cs
Line: 16 - (CS1002) ; が必要です。
Line: 17 - (CS1519) 無効なトークン '??' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 17 - (CS1519) 無効なトークン '=' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 17 - (CS1002) ; が必要です。
Line: 28 - (CS1519) 無効なトークン '=' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 28 - (CS1519) 無効なトークン '(' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 50 - (CS1513) } が必要です。
Line: 66 - (CS1525) '.' は無効です。
Line: 66 - (CS1003) 構文エラーです。':' が必要です。
Line: 66 - (CS1031) 型が必要です。
Line: 66 - (CS1519) 無効なトークン ')' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 66 - (CS1519) 無効なトークン ';' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 67 - (CS1519) 無効なトークン '.' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 67 - (CS1520) メソッドは戻り値の型を持たなければなりません。
Line: 67 - (CS1001) ID がありません。
Line: 67 - (CS1002) ; が必要です。
Line: 69 - (CS1519) 無効なトークン '(' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 69 - (CS1519) 無効なトークン '=>' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 69 - (CS1519) 無効なトークン '==' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 69 - (CS1519) 無効なトークン ')' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 71 - (CS1519) 無効なトークン '(' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 71 - (CS1519) 無効なトークン ')' が クラス、構造体またはインターフェイスのメンバー宣言で使用されています。
Line: 76 - (CS0116) 名前空間にフィールドやメソッドのようなメンバーを直接含めることはできません。
Line: 86 - (CS1022) 型、名前空間の定義、またはファイルの終わりが必要です。

しかし、そもそもコンパイルさせる意味もないですし、意味がわからないエラー。

3. 頻発しているACT本体のエラー
***** 2018-03-25T16:16:01 - ED: DirectHitPct
System.InvalidOperationException: コレクションが変更されました。列挙操作は実行されない可能性があります。
   場所 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   場所 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   場所 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   場所 System.Linq.Enumerable.Sum(IEnumerable`1 source)
   場所 FFXIV_ACT_Plugin.FFXIV_ACT_Plugin.<UpdateACTTables>b__24_142(AttackType Data)
   場所 FFXIV_ACT_Plugin.FFXIV_ACT_Plugin.<>c.<UpdateACTTables>b__24_149(DamageTypeData Data)
   場所 Advanced_Combat_Tracker.FormActMain.lvDG_RetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   場所 Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   場所 Advanced_Combat_Tracker.FormActMain.lvDG_RetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   場所 System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   場所 System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
   場所 System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   場所 Advanced_Combat_Tracker.FormActMain.ResizeLVCols(ListView listview)
   場所 Advanced_Combat_Tracker.FormActMain.tv1_AfterSelect(Object sender, TreeViewEventArgs e)
   場所 Advanced_Combat_Tracker.FormActMain.tmrTick_Tick(Object sender, EventArgs e)
   場所 System.Windows.Forms.Timer.OnTick(EventArgs e)
   場所 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   場所 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   場所 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   場所 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   場所 Advanced_Combat_Tracker.ActLoader.Main(String[] args)

まずはこれらを解消してみてどうなるかと言ったところでしょうか。
