### ISSUE TITLE
Language Settings DE not working

### ISSUE THREAD

**Issue by sundandfun** [anoyetta/ACT.Hojoring#62]
after installation i set the locale to "de-de" (german-deutsch)  now i get this error. The language file is in this directory and i am unable to reset the configuration to default values. Reinstalling the plugin and ACT itself does not solve the problem.

http://imagizer.imageshack.com/img923/5057/kctVoW.jpg

**Comment by anoyetta** [comment]
v5.4.8a を使用してください。
https://github.com/anoyetta/ACT.Hojoring/releases/tag/v5.4.8a

ただし、日本語、英語以外の言語での動作には制限があります。
* UIが翻訳されていない
言語ファイルは外部ファイルになっているので自分で翻訳してください。
* タイムラインの一部の機能が動作しない
タイムラインの中核の機能は動作しますが、分析や自動開始、終了などの機能は動作しません。ソースコード中に定義された各種トリガのキーワードを提供してもらえれば組み込む可能性はあります。
