### ISSUE TITLE
[SpecialSpellTimer] No way of selecting Icon

### ISSUE THREAD

**Issue by PommeVerte** [anoyetta/ACT.Hojoring#64]
I've been trying to set icons for spells but the option is missing. Any idea why this is? 
![image](https://user-images.githubusercontent.com/1415875/38481428-c2d6ffe4-3b98-11e8-8482-08079237b295.png)

[ACT.Hojoring.HelpMe.2018-04-09.zip](https://github.com/anoyetta/ACT.Hojoring/files/1888578/ACT.Hojoring.HelpMe.2018-04-09.zip)

**Comment by anoyetta** [comment]
icon settings is in "Visual" tab.
and you must install icon png files.

**Comment by PommeVerte** [comment]
Ok I figured it out thanks. It's because there is no horizontal scroll so the icon options could not be seen. Thanks!!
