### ISSUE TITLE
Special Spell Timers Issue

### ISSUE THREAD

**Issue by Tidds** [anoyetta/ACT.Hojoring#65]
I don't know if this is a bug or caused by something else, but my spell timers for Aero II + III stopped working. They used to work fine and then just suddenly stopped displaying.

Worked perfectly for ages and then suddenly does nothing, other timers work fine so I know the plugin is working, I've updated everything and have no other issues, just my DoTs.

![2018-05-06](https://user-images.githubusercontent.com/39018204/39669464-70c04524-50e4-11e8-9ae3-4e74f7632e2d.png)

**Comment by anoyetta** [comment]
パターン文字列が間違っているのではないでしょうか？
冒頭の ] は、ログ行頭のタイムスタンプの末尾を示していると思いますが、現在のマッチング用文字列にはタイムスタンプは付与されていません。そのせいでマッチしないのだと思われます。
