### ISSUE TITLE
Ultrascouter mob overlay / font size issue

### ISSUE THREAD

**Issue by windup-moon** [anoyetta/ACT.Hojoring#68]
Dear anoyetta,
thx for that amazing plugin.

I got an similar issue like one reported long time ago:
[github.com/anoyetta/ACT.Hojoring/issues](https://github.com/anoyetta/ACT.Hojoring/issues/1)

If i enter the value 4 at Mob font, the value 40 will be used/displayed in the field.
If i enter 0.4 as Mob font size, i got the value 4 used/displayed in the field.
I tried several fonts, even the Meiryo/Meiryo UI.

The overlay looks like this:
![ultrascouter_small](https://user-images.githubusercontent.com/39856879/40877299-eaf9575e-667e-11e8-8b4e-c7c8e15f64dd.jpg)

Versions used:
ACT.Hojoring v5.9.3
ACT.SpecialSpellTimer v2.4.5
ACT.UltraScouter v1.3.5
ACT.TTSYukkuri v4.0.3

Tbh, i'm kinda new in using hojoring and using Win7-64 pro. As Win10 is recommended, i hope you have an idea how to fix this. Is there another overlay to get the mob/mob position displayed?

Best regards
Moon

**Comment by MrSigy** [comment]
fixed by typing a "," behind fontsize
