### ISSUE TITLE
スペスペたいむでsync-countを使用した時の動き

### ISSUE THREAD

**Issue by sasamag** [anoyetta/ACT.Hojoring#71]
スペスペたいむでsync-countを使用した時、
sync-count="1"の場合、1回目と2回目のマッチに反応してしまいます。
それ以降は、
sync-count="2"の場合、3回目
sync-count="3"の場合、4回目
と、sync-countに設定した値+1回目の回数で反応するようです。

定義ファイルの書き方ページ見ると、下記のように記載があったため、報告させていただきました。
ご確認よろしくおねがいします。
>  sync-count :
>    int, 任意項目, 既定値0
>    何回目のマッチングでこのトリガを実行するか？
>    0ならば、毎回のマッチングでトリガを実行する。
>    1ならば、1回目のマッチング時のみトリガを実行する。
>    2ならば、2回目のマッチング時のみトリガを実行する。
>  ...
>    という仕組み。

追記：
シミュレータで下記のような状態の場合にカウントがうまくいきませんでした。
aタグの方のtimeを2にした場合、正常にカウントされました。

[test.zip](https://github.com/anoyetta/ACT.Hojoring/files/2124779/test.zip)

使用しているプラグインのバージョンは下記のものです。
FFXIV_ACT_Plugin v1.7.0.11
ACT.Hojoring v5.11.7
ACT.SpecialSpellTimer v2.6.2
ACT.UltraScouter v1.3.7
ACT.TTSYukkuri v4.1.5

**Comment by anoyetta** [comment]
再現しません。

添付のtest.xml, test.log を使用してシミュレーションしたところ、問題なく動作しました。

**Comment by anoyetta** [comment]
と思ったら、再現した。

必ずしも再現するわけではないようです。
実運用時には問題がありません。
起動直後の１回目だけか、手動でロードした１回目だけか、限られた条件のときのみ再現する様子。

**Comment by anoyetta** [comment]
タイムラインの初回の実行時のみ発生する。

おそらくタイムラインの開始トリガを検知してから最初のトリガ対象となるログの発生までに処理が間に合っておらず、最初のログに対するトリガが無視されていると思われる。
例えば、最初のログの発生を3秒から6秒に変更するとどのような場面でも発生しなくなる。

2回目以降の実行ではこれらの現象は発生しない。

実運用時はほぼ発生しないシチュエーションであるため対応は保留する。
