### ISSUE TITLE
SPESPEのエリアフィルターに一部のコンテンツが登録されていない

### ISSUE THREAD

**Issue by LuiceCreek** [anoyetta/ACT.Hojoring#72]
**現象の詳細**  
Patch4.3以降の一部のコンテンツが、SPESPEのエリアフィルターに登録されていない
例)
ツクヨミ討滅戦
極ツクヨミ討滅戦
絶アルテマウェポン討滅戦
封じられた聖塔 リドルアナ

**再現方法**  
任意のスペルを開き、エリアフィルターを参照する

**環境**
- 補助輪のバージョン: v5.14.8
- FFXIV_ACT_Pluginのバージョン: v1.7.0.11
- OS:  Windows 10

**追加のコメント**  
スペルのエリアフィルターは、"FFXIV_Plugin"と"Zones.csv"をマスターに
xivdbの"Placename.ja-JP.csv"で日本語化していると思われます。(違ったらごめんなさい)
その為、現状の作りですとFFXIV_Pluginが更新されるまで、
Zones.csvの中身は維持する必要があると思われます。

**Comment by anoyetta** [comment]
ゾーンフィルタの作りはお察しのとおりです。

しかし...
ツクヨミ討滅戦
極ツクヨミ討滅戦
絶アルテマウェポン討滅戦
封じられた聖塔 リドルアナ

これらはFFXIV_ACT_Pluginにすでに登録されています。
よって、これらがゾーンフィルタに出てこなくなった理由はZone.csvに登録されていないからではなく、なんらかの別の不具合の可能性があります。

というわけで、確認します。

**Comment by LuiceCreek** [comment]
回答ありがとうございます。

historyを辿って絶アルテマの情報をZone.csvに追記した所、
エリアフィルターに絶アルテマが登録されたので
それが原因かと思った次第です。

引き続き確認よろしくお願いします。

**Comment by anoyetta** [comment]
アメノミハシラをZone.csvに追加したときに

ツクヨミ討滅戦
極ツクヨミ討滅戦
絶アルテマウェポン討滅戦
封じられた聖塔 リドルアナ

これらのゾーンIDと同じIDでアメノミハシラのゾーンを登録したからですね。
よって↑のゾーンは、FFXIV_ACT_Plugin に登録されているが、Zone.csvによってアメノミハシラの名前に置き換えられてしまっている
という状態でした。

どうもアメノミハシラのゾーンIDは間が飛んでいるようで

ZoneIDの並び的に
```
アメノミハシラ1-10
アメノミハシラ11-20
アメノミハシラ21-30
アメノミハシラ31-40
アメノミハシラ41-50
アメノミハシラ51-60
ツクヨミ討滅戦
極ツクヨミ討滅戦
絶アルテマウェポン討滅戦
封じられた聖塔 リドルアナ
アメノミハシラ61-70
アメノミハシラ71-80
アメノミハシラ81-90
アメノミハシラ91-100
アメノミハシラ41-50
アメノミハシラ51-60
```
という並びのようですね。

**Comment by LuiceCreek** [comment]
なるほど了解しました。
ミハシラ61～100までのIDを直せば問題なさそうなので、
Zone.csvを手直して運用しておきます。
