### ISSUE TITLE
こんばんわ

### ISSUE THREAD

**Issue by collett120** [anoyetta/ACT.Hojoring#78]
つい最近までACT.hojoringで導入したゆっくりをディスコードに共有して使っておりましたけど
突然ファイルデータがなくなり
再度インストールして設定して見た所自分のヘッドセットで読み上げはするものの
ディスコードのbotでは読み上げなくなってしまいました
ぜひ改善点などありましたら教えてもらってもよろしいでしょうか・・・よろしくお願いします
[ACT.Hojoring.HelpMe.2018-07-31.zip](https://github.com/anoyetta/ACT.Hojoring/files/2242261/ACT.Hojoring.HelpMe.2018-07-31.zip)

**Comment by collett120** [comment]
後DPSの計測とかもできなくなったりしてます・・・
すいませんがよろしくお願いします

**Comment by anoyetta** [comment]
補助輪側の問題ではなくFFXIV_ACT_Plugin側の問題だと思います。
