### ISSUE TITLE
[TTSYukkuri] 英語版Windows でAquesTalkが動かない

### ISSUE THREAD

**Issue by anoyetta** [anoyetta/ACT.Hojoring#8]
掲題の通り。
IMEの逆変換ができないせいかと思ったらそうではなかった。英語版WindowsでIMEを有効にしても改善しない。英語版Windowsでデバッグする必要がある。

**Comment by eai04191** [comment]
システムロケールを`英語 (米国)`にしているとAquesTalkが音声を作れない？みたいです。
![2017-11-07_14 32 00](https://user-images.githubusercontent.com/3516343/32478780-fbf22cdc-c3c9-11e7-9894-a348fd727174.png)

`Roaming\anoyetta\ACT\tts cache`に作成されるwavは無音でした。
システムロケールが英語の場合でも`IMEによる逆変換`にすれば数字だけならば読み上げることができました。

**Comment by anoyetta** [comment]
ありがとうございます。
アクエストが評価用のDLLと一緒に配布している評価用アプリですと英語ロケールでも発声できるようです。先日問合せてきた英語圏の方に試してもらいました。
というわけで、AquesTalk.dl 呼び出し方の問題かなーと推測してたりします。英語版Windowsの仮想PCを作ったのでこれから詳しく調べるつもりです。

**Comment by anoyetta** [comment]
メモ
* IME逆変換はIMEがインストールされていても日本語ロケールでなければ動作しない
これは想定通り。
* AqKanji2Koe はロケールに依存せずに動くただし文字コードをUNICODEで扱わなければならない
* AquesTalk はロケールに依存せずに動くただし文字コードをUNICODEで扱わなければならない

トータルとしてはごく当たり前の挙動だった。AquesTalkのUNICODEの扱いに若干のクセがあって苦戦した。
