### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by syd-h** [anoyetta/ACT.Hojoring#81]
Since it turns out Windows 7 is arbitrarily dropped and the updater had no mention of this... What is the latest useable version I can grab? Looking at the log file it seems I had v5.13.1 before update it today. ACT wasn't working after the minor patch this tuesday I think it was. Figured I would update the Hojoring set to see if it was that it to only find this. 

Additionally, what was changed to drop support for 7/8? If it really is arbitrary I'll just see if I can't rewrite the portions for W7.

**Comment by syd-h** [comment]
No, but I came across a file that giving an edit might be worth a try. 
https://github.com/anoyetta/ACT.Hojoring/blob/495a04d3cb2d3817923341cb3452266a29e0214e/source/FFXIV.Framework/FFXIV.Framework/Config.cs
`private const bool SupportWin7Default = false;`

I haven't had a chance to grab the source, edit the .dll, and rebuild it yet.

**Comment by Pirate144** [comment]
Sorry for late reply, would appreciate a followup whenever you do get a chance to see if it works. Thank you.
