### ISSUE TITLE
スペスペの文字アウトラインについて

### ISSUE THREAD

**Issue by onigirinori7653** [anoyetta/ACT.Hojoring#84]
スペスペをスキルのリキャスト管理で使っているのですが
スペスペの文字のアウトラインがリキャスト時間をアイコンに重ねるにチェックを入れると
文字のアウトラインが適用されなくなります。これは仕様なのでしょうか？
画像も添付しておきます。
![default](https://user-images.githubusercontent.com/36393376/45306834-8bae3700-b558-11e8-9a9b-591c33fa040f.png)
![2](https://user-images.githubusercontent.com/36393376/45306847-923cae80-b558-11e8-82c1-d0d0d1ddc2f7.png)

テキストのアウトライン増幅率をいじらずに、リキャスト時間をアイコンに重ねるにチェック入れるか
入れないかでこのようなかんじになっています。

**Comment by anoyetta** [comment]
たしかに再現しますね。
バグとして修正ます。

**Comment by anoyetta** [comment]
Released v5.17.2a

**Comment by onigirinori7653** [comment]
素早い対応ありがとうございます。
