### ISSUE TITLE
スペスペのトリガーについて要望

### ISSUE THREAD

**Issue by Ponkoro** [anoyetta/ACT.Hojoring#85]
スペスペのトリガーに個別に「全滅時にカウントをリセットする」をキャンセルする設定があればと思います。
用途として、フロントライン制圧戦でドローンのPOP管理をしているのですがPTが全滅時にリセットされるためです。
ご検討お願い致します。

**Comment by anoyetta** [comment]
FLのときだけ、当該チェックを外せばよいのではないでしょうか？

**Comment by anoyetta** [comment]
うーん、微妙なところなんですよね。
チェックを外すのを忘れてしまう不便さであったり、そもそもいちいちチェックを切り替えないといけない不便さというのは理解できます。また実装コストそのものもたいしたことないので実装してもよいのですが。

気になるのは、この経緯を知らない人にとっては意味不明な機能になることです。
意味のわからない設定はさわらなければよいということではあるんですが、そういうよくわからない設定の数が多いとというのは全体的ななんとなくの敷居を上げてしまう。

気が向いたら次のパッチ時の対応のときについでにやるかもです。
