### ISSUE TITLE
Issue with Keyword to Extend

### ISSUE THREAD

**Issue by Fiorinol** [anoyetta/ACT.Hojoring#86]
Hi, I'm having an issue with keyword to extend. When I reduce the duration of a timer, the whole recast bar resets under the new duration. I'm wondering if this is intended behavior.

Example;

I just used Aetherflow;
https://i.imgur.com/83rHP6Q.png

After a few seconds, I use Energy Drain, which triggers Keyword to Extend for -5 seconds, the timer bar graphic resets under the reduced duration;
https://i.imgur.com/tKdW7Sb.png

Is this intended behavior? If not, is there a way to not reset the progress bar like this; https://i.imgur.com/eu9dFPX.png ?

ACT Version 3.3.2
FFXIV_ACT_Plugin v1.7.0.11
ACT.Hojoring v5.17.1
ACT.SpecialSpellTimer v2.8.3

https://anonfiles.com/v5f31bhabb/ACT.Hojoring.HelpMe.2018-09-15_zip

**Comment by anoyetta** [comment]
Yes, it's intended behavior.
