### ISSUE TITLE
UltraScouterとTTSYukkuri が有効にできない

### ISSUE THREAD

**Issue by eai04191** [anoyetta/ACT.Hojoring#9]
issueの前にまず、素晴らしいプラグイン群を作ってくださり、ありがとうございます。

`%appdata%`にある`Advanced Combat Tracker`フォルダと`anoyetta`フォルダを削除し、ACT（ポータブル版）を用意して、`ACT.Hojoring-v4.0.2`フォルダを作り中に補助輪を展開しました。

その後UltraScouter、TTSYukkuri を追加して有効化しようとするとエラーが出ます。

エラーメッセージはFFXIV_ACT_Pluginの有効無効では変わっていない様子でした。

- FFXIV_ACT_Plugin.dll のバージョン
1.6.1.6

- ACT.SpecialSpellTimer.dll のバージョン
1.2.3.0.5

- ACT.UltraScouter.dll のバージョン
1.1.0.4

- ACT.TTSYukkuri.dll のバージョン
3.0.2.4

- ACT本体のログファイル
https://pastebin.com/rHbi9dE7

- ACT.SpecialSpellTimer のログファイル
- ACT.UltraScouter のログファイル
- ACT.TTSYukkuri のログファイル
- %APPDATA%\anoyetta\ACT\log\ACT.Hojoring.YYYY-MM-DD.log
logフォルダが存在しませんでした

- （あれば）エラーダイアログのスクリーンショット
![UltraScouter ](https://user-images.githubusercontent.com/3516343/32426395-65ba304c-c2fd-11e7-8c82-5295bb47ac28.png)

![TTSYukkuri ](https://user-images.githubusercontent.com/3516343/32426425-a543e4b0-c2fd-11e7-8290-cf2ef7a0fb09.png)

**Comment by anoyetta** [comment]
古いFFXIV.Frameworkがロードされたままの状態なのでは？

古いプラグインのチェックを外しても内部的にロードされたFFXIV.Frameworkはそのままです。そのまま新しいプラグインをONにしても内部にろーどされている古いFFXIV.Frameworkを参照してしまいます。古いプラグインのチェックを外したら一度ACT本体を再起動してください。

また、プラグインをバージョンアップする場合は・・・
1. 古いフォルダを丸ごとコピーしてバックアップする
2. その後に新しいものを上書きする
この手順のほうがよいです。
要するに新しいものを新しいパスの場所に配置すると、ACT起動後に古いプラグインの解除→新しいプラグインの再登録の作業が発生するからです。前述の通り、その場合は古い周辺ライブラリがロードされてしまっているためACTの再起動が必要になってしまいます。

**Comment by eai04191** [comment]
古いSpecialSpellTimerのファイル群をACT直下に入れたのを忘れていました……
ちゃんとプラグインごとに分けて導入したらうまくいきました。
バージョンアップの件も承知しました。ありがとうございます。

**Comment by anoyetta** [comment]
exe（EntryAssembly）と同じ場所にあるDLLは最優先でロードされちゃいますね。
気をつけてください。
